### ISSUE TITLE
unexpected behaviour with angr.options.unicorn

### ISSUE THREAD

**Issue by Kyle-Kyle** [angr/angr#1014]
I was testing [hitcon2017_sakura](https://github.com/angr/angr-doc/blob/master/examples/hitcon2017_sakura/solve.py) in `angr-doc`.
Since it is too slow, I tried to use `angr.options.unicorn` to speed up thing. However, this option messes up everything. It can not find those addresses I tell it to find and it keep using a lot of resources and finally got killed.
As @rhelmot suggested, I tried `add_options=angr.options.unicorn - {angr.options.UNICORN}`. Although it can find addresses I tell it to find with this option, the final answer is wrong.

**Comment by ltfish** [comment]
I wonder why this is the case... will look into this later.

**Comment by ltfish** [comment]
> It can not find those addresses I tell it to find and it keep using a lot of resources and finally got killed.

This is actually the expected behavior. The unicorn engine does not care about what you provided in `find` and `avoid` when exploring states. It only takes `extra_stop_points`. So you want to pass in an extra parameter `extra_stop_points` to `simgr.explore()` so that the unicorn engine knows when to stop.

**Comment by rhelmot** [comment]
I thought someone made the explorer automatically populate the extra stop
points?
