### ISSUE TITLE
I cannot get corrent cfg when analyzing a program with indirect calls

### ISSUE THREAD

**Issue by brokendragon** [angr/angr#104]
Hi
I analyzing a program with indirect calls by Angr. However, it seems that the constructed cfg is incorrect. Below is my tested program.

```
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <fcntl.h>
#include <stdlib.h>
void fun1()
{
  printf("fun1\n");
}
void fun2()
{
  printf("fun2\n");
}
void fun3()
{
  printf("fun3\n");
}
void fun4()
{
  printf("fun4\n");
}

void (*fun[4])(void) = {fun1, fun2, fun3, fun4};

void callsites(int x)
{
  (*fun[x])();
  //fun1();
}

void main(int argc, char** argv)
{
  int i = atoi(argv[1]);
  printf("%d\n", i);
  callsites(i);
}
```

Below is the commands.

```
import angr
b = angr.Project("indirect_call", load_options={'auto_load_libs': False})
cfg = b.analyses.CFG(keep_state=True, enable_symbolic_back_traversal = True)
print cfg.graph
print "----------------------------------------------"
print "It has %d nodes and %d edges" % (len(cfg.graph.nodes()), len(cfg.graph.edges()))
target_func = cfg.kb.functions.function(name="callsites")
print "----------------------------------------------"
print target_func
print "----------------------------------------------"
target_func = cfg.kb.functions.function(name="fun1")
print target_func
target_func = cfg.kb.functions.function(name="fun2")
print target_func
target_func = cfg.kb.functions.function(name="fun3")
print target_func
target_func = cfg.kb.functions.function(name="fun4")
print target_func
```

The result is showing as follows.

```
WARNING | 2016-05-07 19:06:02,381 | simuvex.s_run | Exit state has over 257 possible solutions. Likely unconstrained; skipping. <BV64 reg_18_47_64>

----------------------------------------------
It has 43 nodes and 58 edges
----------------------------------------------
Function callsites [0x40060a]
  Syscall: False
  SP difference: 0
  Has return: False
  Returning: Unknown
  Arguments: reg: [], stack: []
  Blocks: []
  Calling convention: UnknownCC - AMD64 [] sp_delta=0
----------------------------------------------
None
None
None
None
```

I am not sure whether I need to set the option enable_symbolic_back_traversal as True. But no matter whether I set the option or not, the result is more or less the same.

I find that, Angr can find the function callsites, but it did not give me detailed information about it. Besides, Angr fails to find fun1, fun2, fun3, and fun4 at all, that are called indirectly by callsites.

If I comment all statements in callsites, i.e., let callsites empty. The experimental result is changed as follows.

```
----------------------------------------------
It has 43 nodes and 59 edges
----------------------------------------------
Function callsites [0x40060a]
  Syscall: False
  SP difference: 0
  Has return: True
  Returning: True
  Arguments: reg: [72], stack: [0L]
  Blocks: []
  Calling convention: System V AMD64 - AMD64 [<rdi>]
----------------------------------------------
None
None
None
None
```

I find that Angr gives detailed information of callsites this time, and find 59 edges (1 more edge than previous experiment). 

Then I uncomment the statement fun1(); in callsites. In other words, I make callsites call fun1 directly. Experimental result is as follows.

```

----------------------------------------------
It has 48 nodes and 66 edges
----------------------------------------------
Function callsites [0x40060a]
  Syscall: False
  SP difference: 0
  Has return: True
  Returning: True
  Arguments: reg: [72], stack: [0L]
  Blocks: [0x40060a, 0x40061f]
  Calling convention: System V AMD64 - AMD64 [<rdi>]
----------------------------------------------
Function fun1 [0x4005c6]
  Syscall: False
  SP difference: 0
  Has return: True
  Returning: True
  Arguments: reg: [], stack: [0L]
  Blocks: [0x4005d4, 0x4005c6]
  Calling convention: System V AMD64 - AMD64 []
None
None
None
```

I can see that Angr gives detailed information of callsites and fun1 now. Moreover, Angr finds more nodes and edges than previous two experiments.

So, I suspect Angr fails to handle indirect calls? Or are there any errors in above commands?

Thanks a lot!

Ting Chen

**Comment by brokendragon** [comment]
Hi there
When I changed cfg = b.analyses.CFG into cfg = b.analyses.CFGAccurate, the result has no much difference. But if I replace cfg = b.analyses.CFG with cfg = b.analyses.CFGFast, Angr succesfully finds all functions as follows. But CFGFast finds fewer edges.
```
 74% |//////////////////////////////////////////////////////////////////////////////////////////////                                | Elapsed Time: 0:00:00 ETA:  0:00:00




100% |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| Elapsed Time: 0:00:00 Time: 0:00:00

----------------------------------------------
It has 45 nodes and 30 edges
----------------------------------------------
Function callsites [0x40060a]
  Syscall: False
  SP difference: 0
  Has return: False
  Returning: Unknown
  Arguments: reg: [], stack: []
  Blocks: [0x40060a]
  Calling convention: None
----------------------------------------------
Function fun1 [0x4005c6]
  Syscall: False
  SP difference: 0
  Has return: False
  Returning: Unknown
  Arguments: reg: [], stack: []
  Blocks: [0x4005d4, 0x4005c6]
  Calling convention: None
Function fun2 [0x4005d7]
  Syscall: False
  SP difference: 0
  Has return: False
  Returning: Unknown
  Arguments: reg: [], stack: []
  Blocks: [0x4005e5, 0x4005d7]
  Calling convention: None
Function fun3 [0x4005e8]
  Syscall: False
  SP difference: 0
  Has return: False
  Returning: Unknown
  Arguments: reg: [], stack: []
  Blocks: [0x4005e8, 0x4005f6]
  Calling convention: None
Function fun4 [0x4005f9]
  Syscall: False
  SP difference: 0
  Has return: False
  Returning: Unknown
  Arguments: reg: [], stack: []
  Blocks: [0x4005f9, 0x400607]
  Calling convention: None

```
I suspect CFGAccurate covers less code than CFGFast, just like the experiments shown in Angr's paper. But CFGFast cannot construct a CFG as accurate as CFGAccurate.

**Comment by rhelmot** [comment]
Hey there - the only person who can get you an authoritative answer on this is @ltfish, who is the author of the CFG code. I can answer a few things though:

- enable_symbolic_back_traversal along with keep_state SHOULD have been enough to do that recovery correctly. This might be a bug. 
- CFG is a synonym for CFGAccurate
- CFGFast works by searching for known blocks of bytes which resemble function prologues, so it makes sense that it'd be able to find your functions but not any edges to them.

**Comment by ltfish** [comment]
- Currently `CFGAccurate` does not have full support for resolving jump tables. You should be able to see call edges from `callsites()` to four functions after we finish the jumptable resolving support for `CFGAccurate`.

- As @rhelmot said, `CFGFast` works by looking for known function epilogues as well as using symbols from the binary, and that's why `CFGFast` sees all functions. However, `CFGFast` does not seem to be able to resolve the jump table either, and as a result, you don't see call edges from `callsites()` to any of those four functions in `CFGFast`.

- With `symbolic_back_traversal=True` or `advanced_back_slicing=True`, `CFGAccurate` should still be able to find those call edges from `callsites()` to those four functions. However, as you can see from your code, `i` can be any value from `MIN_INT` to `MAX_INT`, which could be the root cause of the warning:
> Exit state has over 257 possible solutions. Likely unconstrained; skipping. <BV64 reg_18_47_64>
I believe `CFGAccurate` is ignoring all resolved results for an indirect jump if there are more than 257 possible solutions, which is exactly the case in your example. You can try to limit the range of `i` (e.g. add a check in your code snippet to make sure `i` is less than 100 and greater than or equal to 0) and rebuild the CFG on the new program.

**Comment by brokendragon** [comment]
@ltfish 
Thanks for your help!
According to your suggestion, I add a check `if(x > 0 && x < 4)`  before `(*fun[x])();`, and now I get correct result. But the function table just has four function pointers. I hope Angr can construct CFG correctly without the explicit check code. In many cases, we cannot change the source of the tested program, so we cannot add the explict check manually.

**Comment by rhelmot** [comment]
That check will always be present, since otherwise it's a bug in the program and you might be able to jump to a user-controller pointer.

**Comment by brokendragon** [comment]
@rhelmot 
I agree that without check, the code is buggy. If the tested program is not written by me, and I get a warning like `WARNING | 2016-05-09 13:44:43,902 | simuvex.s_run | Exit state has over 257 possible solutions. Likely unconstrained; skipping. <BV64 reg_18_47_64>`. How can I locate and diagnose the bug?

**Comment by rhelmot** [comment]
The control flow recovery is not meant to be a vulnerability analysis. You want to write your own static/symbolic analysis that searches for dereferences on user input.

I'm sorry about the vague answer, but if there were an easy answer to "how can I use angr to find bugs in programs" then there would be a lot less research going on right now :)

**Comment by brokendragon** [comment]
I see. I tried to add the check code before calling the function callsites, like 
```
void callsites(int x)
{
    (*fun[x])();
  //fun1();
}

void main(int argc, char** argv)
{
  int i = atoi(argv[1]);
  printf("%d\n", i);
  if(i > 0 && i < 4)
    callsites(i);
}
```
This time, Angr reports the exit state has 257 possible solutions againt. But I have already constrained the index i.

**Comment by rhelmot** [comment]
If I recall correctly, there is a CFG option to make this work. Increasing either context_sensitivity_level or call_depth should help, also you can re-enable keep_state and enable_symbolic_back_traversal and that might also catch it.

**Comment by brokendragon** [comment]
It does work no matter adding context_sensitivity_level or call_depth. The command is 
`cfg = b.analyses.CFG(keep_state=True, enable_symbolic_back_traversal = True, context_sensitivity_level = 3, call_depth = 5)`
Angr reports two similar warnings about exit state has 257 possible solutions like this
```
WARNING | 2016-05-09 14:02:27,101 | simuvex.s_run | Exit state has over 257 possible solutions. Likely unconstrained; skipping. <BV64 Reverse(symbolic_read_symbolic_read_reg_38_40_64_42_32_43_64)>
WARNING | 2016-05-09 14:02:28,764 | simuvex.s_run | Exit state has over 257 possible solutions. Likely unconstrained; skipping. <BV64 Reverse(symbolic_read_symbolic_read_reg_38_44_64_47_32_48_64)>
```

**Comment by ltfish** [comment]
> I hope Angr can construct CFG correctly without the explicit check code. In many cases, we cannot change the source of the tested program, so we cannot add the explict check manually.

Recovering the CFG from machine code is not as easy as it seems to be. In your example (the buggy one), `(*fun[0])()`, `(*fun[-1])()`, and `(*fun[13337])()` are all equivalent to the CPU, and apparently, they are all possible targets for that call.

angr will be able to resolve the jump table in `callsites()` *with heuristics* once the jump table resolution is fully implemented in `CFGAccurate`. Heuristics are essential here in order to identify the base address of the function pointer array, which might work for a lot of real-world cases, but is impossible to work for all such cases.

For this specific example, I believe the best way is to rely on the jump table resolution of `CFGAccurate`. I'll work on it later this week.

> If the tested program is not written by me, and I get a warning like  `WARNING | 2016-05-09 13:44:43,902 | simuvex.s_run | Exit state has over 257 possible solutions. Likely unconstrained; skipping. <BV64 reg_18_47_64> .` How can I locate and diagnose the bug?

`CFGAccurate` is not designed to be a vulnerability finder. You can modify angr's code (start from `CFGAccurate._get_simrun()` in `cfg_accurate.py`) in order to catch this specific case.

However, having too many possible solutions does not necessarily mean the existence of a bug. It could also mean some indirect jump is not easily recoverable. You'll have to make some policies in order to use `CFGAccurate` to detect bugs/vulnerabilities.

> It does work no matter adding context_sensitivity_level or call_depth.

I assume you mean "it does not work even when context_sensitivity_level or call_depth is used". (If I remember correctly), as an optimization (for speed), symbolic back traversal does not go back beyond function boundaries. It also has a limit of how many basic blocks angr should traverse back. In your case, I think it's likely that angr does not traverse back enough number of basic blocks to see your constraint on `i`. You can adjust some parameters inside `CFGAccurate._symbolically_back_traverse()` to make it work in this case.
