### ISSUE TITLE
Resolve jump table

### ISSUE THREAD

**Issue by valour01** [angr/angr#1052]
I know that resolving a jump  table has been discussed many times before. I recently use a binary to test the ability of angr on resolving the jump table. I found that inside one binary, angr_fast may be able to resolve some of the jump tables but find others unresolvable. Is this a right behavior? Is cfg_fast able to resolve all the jump tables?

Also, I know that cfg accurate doesn't have a very good support on jump table. May I know the fundamental reason. Why don't you add the support to cfg accurate?  Besides, I ever noticed that you guys say cfg accurate is not path sensitive. What is the difference from context sensitive.

Regards
Muhui

**Comment by ltfish** [comment]
> Is cfg_fast able to resolve all the jump tables?

Currently it's not able to resolve all of them. But resolving all jump tables is the goal. It's mostly an implementation problem (i.e., I haven't got enough time to track down why it fails on the ones that couldn't be successfully resolved).

> Why don't you add the support to cfg accurate?

Because I don't have time right now. It's still on my TODO list.

> Besides, I ever noticed that you guys say cfg accurate is not path sensitive. What is the difference from context sensitive.

[Wikipedia](https://en.wikipedia.org/wiki/Data-flow_analysis#Sensitivities) has some good explanations.
