### ISSUE TITLE
No _iropt_level when loading in a pickled CFGAccurate. 

### ISSUE THREAD

**Issue by bdrodes** [angr/angr#1058]
After pickling and loading a CFGAccurate, I got the following trace attempting to look at a CFGNode's block:

```
/Users/benjaminrodes/angr_libs/angr/angr/analyses/cfg/cfg_node.pyc in block(self)
    211             return None
    212         project = self._cfg.project  # everything in angr is connected with everything...
--> 213         b = project.factory.block(self.addr, size=self.size, opt_level=self._cfg._iropt_level)
    214         return b
    215 

AttributeError: 'CFGAccurate' object has no attribute '_iropt_level'
```

By setting the attribute manually to None on the loaded pickle, I am able to analyze blocks. Since analysis can continue if the attribute is added manually, was `_iropt_level` accidentally excluded from pickling?

**Comment by rhelmot** [comment]
Unfortunately we have to do pickling of analyses manually due to the hackish way that analyses are grafted onto projects, last I checked? Maybe this has changed. I added iropt_level to the pickle list.

@ltfish you may want to open an issue for yourself to make the cfgs do a super-call into a CFGBase.__getstate__ etc. Would prevent issues like this in the future.
