### ISSUE TITLE
Switch Statement Analysis

### ISSUE THREAD

**Issue by ViktorMKa** [angr/angr#106]
Hi angr-team!

I have another issue that popped up while testing c-code with switch statements:

I can't get any valuable information from the angr-CFG beyond the default jump. Is this an issue with my specific sample or way of using angr? Or is this just the way angr handles switch statements?

Appended are the c-code and a CFG created with angrutils. I have done both optimized and non-optimized compilations, but I'm not seeing any difference.

Best Regards,
Viktor

FYI: The 3 nodes of the main function are located at the bottom left of the CFG, the rest is includes/system stuff.
![jumptable out_cfg_full](https://cloud.githubusercontent.com/assets/11650337/15106014/a67ebb60-15c6-11e6-8ad7-2f37be7ccc73.png)

[jumptable.txt](https://github.com/angr/angr/files/254456/jumptable.txt)

**Comment by rhelmot** [comment]
Switch statements that are compiled into jumptables are a very hard case to perform control flow analysis on, since you end up dereferencing a partially symbolic pointer to get there. Soon, there will be some heuristics to try to nail down cases like these, but for now, you should try enabling the CFG options `enable_backward_symbolic_traversal` and `keep_state`.

**Comment by ViktorMKa** [comment]
Thanks for the swift response. I had enabled `keep_state` before and just tried `enable_symbolic_back_traversal=True` (assuming this is what you meant). The result is regrettably the same.

Still thank you - I want to make sure that I'm not messing up using the proper angr usage.

**Comment by ltfish** [comment]
In future releases, `CFGAccurate` will be able to identify all targets from a jump table as well as the specific target that CFG takes under the current (calling) context.
