### ISSUE TITLE
Identifier unreferenced variable

### ISSUE THREAD

**Issue by tiffanyb** [angr/angr#1079]
Test file `test.py`:
```python
from patcherex.patch_master import PatchMaster
pm = PatchMaster(sys.argv[1])
patched_bin, ids_rule = pm.create_one_patch('medium_reassembler_optimized')
```
Run:
`python test.py ../patcherex/test_binaries/CADET_00003`

In `angr/angr/analyses/identifier/identify.py`, line 591:
```python
                        if stmt.offset == self.project.arch.sp_offset:
                            found_end = True
                            ends.add(a.ins_addr)
                            all_end_addrs.add(cur_addr)
```
Variable `a` is not referenced.

**Comment by rhelmot** [comment]
I introduced this bug last year. By examining the commit linked in the above commit message, which replaced that block of code's dynamic analysis with a static analysis, I determined what the appropriate fix is. It survived this long because `a` _could_ have been defined by the above loop, but even if it didn't crash it was producing bad results.

**Comment by tiffanyb** [comment]
Thanks for fixing it quickly! @rhelmot
