### ISSUE TITLE
SimEngineError when using empy blocks

### ISSUE THREAD

**Issue by Alexeyan** [angr/angr#1085]
Hi.
When a BasicBlock b has no code (Like for `<Function __cxa_atexit (0x1000000)>` ), the calls to 
`b.vex`, `b.instructions` and `b.instrucion_addrs` all result in a 
`SimEngineError: No bytes in memory for block starting at 0x1000000`

Trace:

```
---------------------------------------------------------------------------
SimEngineError                            Traceback (most recent call last)
----> 1 b.instructions

/home/X/.virtualenvs/pypy-angr/site-packages/angr-7.8.2.21-py2.7.egg/angr/block.pyc in instructions(self)
    188         if not self._instructions and self._vex is None:
    189             # initialize from VEX
--> 190             _ = self.vex
    191
    192         return self._instructions

/home/X/.virtualenvs/pypy-angr/site-packages/angr-7.8.2.21-py2.7.egg/angr/block.pyc in vex(self)
    143                     num_inst=self._instructions,
    144                     opt_level=self._opt_level,
--> 145                     arch=self.arch,
    146             )
    147             self._parse_vex_info()

/home/X/.virtualenvs/pypy-angr/site-packages/angr-7.8.2.21-py2.7.egg/angr/engines/vex/engine.pyc in lift(self, state, clemory, insn_bytes, arch, addr, size, num_inst, traceflags, thumb, opt_level)
    499
    500         if not buff or size == 0:
--> 501             raise SimEngineError("No bytes in memory for block starting at %#x." % addr)
    502
    503         # phase 5: call into pyvex

SimEngineError: No bytes in memory for block starting at 0x1000000.
```

**Comment by rhelmot** [comment]
Well... you’re not supposed to ask for a basic block for addresses that
don’t have code at them. That error message is accurate.

**Comment by Alexeyan** [comment]
Shoudn't that just return nothing and not die loudly? 

I want to iterate over all BBs and get all addresses of all instructions and it feels inelegant to check manually if the blocks are empty (Or the function is a simproc).
```
cfg = p.analyses.CFGFast()
for fun in cfg.kb.functions:
    for bb in fun.blocks:
        for addr in bb.instructions_addrs:
            print addr
```
should just work imo. 

The errorhandling here shoudn't have to happen on the user-side, shoudn't it?
I can make a PR for this if you like.

If you think the error should be raised there, may i ask why?

**Comment by ltfish** [comment]
> Shoudn't that just return nothing and not die loudly?

No it should not. You should either check if the block is located at a hooked addr (via `project.is_hooked()`) or manually catch the exception. The error-handling should happen on the user side.

> If you think the error should be raised there, may i ask why?

It's an error... why do you think silently eating the error is a good thing?

**Comment by Alexeyan** [comment]
Why shoudn't `block.instructions` just return `None` if there are no instructions?

The error is raised while trying to lift a block, which is not really what i intended to do with block.instruction_addrs. 

> It's an error... why do you think silently eating the error is a good thing?
I can see that the lifting-code should raise that error, but block.instrucion{s|_addrs} or block.vex should be safe properties for a stable api. 
Especially since they are properties and i didn't manually hook those symbols. (Binary is also not loadad with the "auto_load_libs=False" flag)
Otherwise i have to reimplement the same error handling everytime i iterate over blocks and access those attributes.

Just my 2 cents as a dev using angr daily.

Just my 2 cents as a dev using angr daily.

**Comment by danse-macabre** [comment]
I would agree with @Alexeyan.

> The error is raised while trying to lift a block, which is not really what is intended to do with block.instruction_addrs.

It is neither what one might expect while trying to get a list of instructions if we a talking about the blocks that are stored in the `Function.blocks`. As far as I understand, the `Function.blocks` is meant to represent a set of the "basic blocks" that are part of the function. Those "blocks" are not necessarily the IRSBs; they could be hooked nodes as well. So, it would be somewhat unexpected for them to throw any errors that are related to the lifting process.

I think the proper solution is to return an empty set if the actual block doesn't contain any instructions.

**Comment by ltfish** [comment]
In this case, "the actual block" simply does not exist in memory - in some sense, it is a "virtual block". Semantics wise, `block.instructions` is equivalent to asking "what are the instructions that this virtual block contains?" And the answer is, "no, the virtual block _cannot_ contain any instruction since it's a virtual block, and here is an error for you so that you don't expect a virtual block to contain any instruction in the future."

> I think the proper solution is to return an empty set if the actual block doesn't contain any instructions.

If we want to make this change, I'm fine either way (returning `None` or an empty list). But I'm still not convinced that this is a good change. Maybe @rhelmot can think or speak more about it?

> I can see that the lifting-code should raise that error, but block.instrucion{s|_addrs} or block.vex should be safe properties for a stable api

What should `block.vex` return for a virtual block? `None`? As stated in some object-oriented programming books (maybe for C++), we should always raise exceptions instead of returning an error code. What do you think of this?

**Comment by rhelmot** [comment]
I strongly prefer errors in the case of Block. We have the Snippet/CodeNode stuff for representing arbitrary control flow nodes in the knowledge base, though it is not very well documented or accessible... I don't know how to resolve this problem because I don't know what kind of problem you're trying to solve.

Like... for real. It's a Block. A basic block of code. If you ask for a basic block of code at an address where it is an error to ask for a block, you will receive an error. Exceptions are cheap in python, so we will use them.
