### ISSUE TITLE
Stuck in Infinite loop on pthread_once sim procedure 

### ISSUE THREAD

**Issue by mor619dx** [angr/angr#1087]
Hello,

I've encounter a case where running a simple exploration on a function calling "[pthread_once](https://github.com/angr/angr/blob/master/angr/procedures/posix/pthread.py#L82)" where the func argument (the function pthread_once call) points to a function containing the following assembly:
```
BX LR
```
(Branch Link Register)
Causes infinite loop to happen (LoopSeer does not stop it since it is not an actual assembly loop)

I've made a simple binary to replicate it, the C code:
```
#include <stdio.h> 
#include <errno.h>
#include <pthread.h>

int             once_counter=0;
pthread_once_t  once_control = PTHREAD_ONCE_INIT;

__attribute__((naked)) void immediate_return()
{
 asm("bx lr");
}

void pthread_once_bx_lr()
{
 pthread_once(&once_control, immediate_return);
}

void call_immediate()
{
 immediate_return();
}

int main(){}
```

Now If I run this simple exploration:
```
import angr
p = angr.Project(r"pthread_once", load_options={"auto_load_libs": False})
call_imediate = p.factory.call_state(addr=0x10534) # call_imediate
pthread_once_bx_lr = p.factory.call_state(addr=0x10510) # pthread_once_bx_lr

simgr_call_imediate = p.factory.simulation_manager(call_imediate)
simgr_pthread_once_bx_lr = p.factory.simulation_manager(pthread_once_bx_lr)

simgr_call_imediate.run()
simgr_pthread_once_bx_lr.run() # We get in infinite loop
```
The `immediate_return` function should have no problem running (since its only purpose is returning).
After some testing it seems the loop is getting stuck calling the [retsite](https://github.com/angr/angr/blob/master/angr/procedures/posix/pthread.py#L94) function in pthread_once class - it keeps calling that function without calling the "run" function again.

Which is setup in [line 92](https://github.com/angr/angr/blob/master/angr/procedures/posix/pthread.py#L92) where we call it after calling the actual function (immediate_return)

I've attached the binary (ARM 32Bit) so you can test the problem youself: [Link to download](https://ufile.io/rwuir)

**Comment by rhelmot** [comment]
Fantastic... this could have been triggered by literally any function using the simprocedure continuations on ARM, given that the function actually returned. The problem is that we're not correctly saving the lr register, so when we return, we pull the address to return to from lr, but it's been overwritten by the calling function. So basically we need to save the appropriate caller-save registers before making a call out. I think this should only be the link registers, since simprocedures should never actually touch any general purpose registers, so I'm going to forgo implementing this in the calling convention as a "correct" caller-save implementation.
