### ISSUE TITLE
How to install a low version angr?

### ISSUE THREAD

**Issue by DreamingD** [angr/angr#1106]
I want to use a low version angr,how to install it?

**Comment by ltfish** [comment]
Should be helpful for you: https://stackoverflow.com/questions/5226311/installing-specific-package-versions-with-pip

**Comment by DreamingD** [comment]
Thank you very much

**Comment by rhelmot** [comment]
I don't think it's going to be as easy as `pip install angr==old_version`, since we mark all our self-dependencies as `package>=current_version`. I just tried `pip install angr==7.7.9.8` and it tried pulling in `pyvex==7.8.7.1`, which it obviously can't build against.

You'll need to install all the dependency packages in the angr suite pinned to the version you want, otherwise pip will grab incompatible versions.

@ltfish I think this is something we should fix.

**Comment by ltfish** [comment]
@rhelmot I guess he could manually do the following:

```
pip uninstall angr cle archinfo pyvex  # Uninstall the current version of angr and its modules (libraries)
pip install archinfo==old_version_number
pip install pyvex==old_version_number
pip install cle==old_version_number
pip install claripy=old_version_number
pip install angr=old_version_number
```

**Comment by zardus** [comment]
Going through my backlog and finally got to this...

I'd look at the checkout_at script (https://github.com/angr/angr-dev/blob/master/admin/checkout_at.py). Given the commit hash of a release version bump, it'll rewind all the git repos to a commit right before that one, having the desired effect.
