### ISSUE TITLE
Thumb tail call issue in CFGFast 

### ISSUE THREAD

**Issue by pcgrosen** [angr/angr#1123]
In Thumb binaries, functions that contain a tail call will sometimes be marked by CFGFast as not returning. For example, the following code results in the `add_5` function being marked as not returning (`returning == False`):

```
        .section .text
        .code 16
        .global add
add:
        ADD r0, r0, r1
        MOV pc, lr

        .global add_5
add_5:
        MOVS r1, #5
        B add

        .global main
main:
        PUSH {lr}
        MOVS r0, #2
        MOVS r1, #3
        BL add
        BL add_5
        POP {PC}
```
An assembled version of the above is attached along with a script exhibiting the behavior.

[thumb-tailcall.zip](https://github.com/angr/angr/files/2199855/thumb-tailcall.zip)

**Comment by subwire** [comment]
This issue is resolved (via `detect_tail_calls=True` in CFGFast)
However, I can't get anything to work because... this doesn't produce a valid binary :D
angr fails pretty immediately as it tries to decode main() as ARM, i think this is one of those ARM/Thumb interworking issues, and may be helped by decoding the $t flags.
I am closing this and opening a fresh issue
