### ISSUE TITLE
AttributeError: 'SimFileDescriptorDuplex' object has no attribute '_pos'

### ISSUE THREAD

**Issue by cq674350529** [angr/angr#1167]
This error is due to  using an old attribute `_pos` in `ungetc` SimProcedure.
https://github.com/angr/angr/blob/81507e128e90b7363f81244c462c5786c486bdd5/angr/procedures/libc/ungetc.py#L9-L19

In `SimFileDescriptorDuplex`, there are only two attributes: `self._read_pos` and `self._write_pos`. Maybe use `_write_pos` in `ungetc` SimProcedure instead?
https://github.com/angr/angr/blob/81507e128e90b7363f81244c462c5786c486bdd5/angr/storage/file.py#L859-L873

**Comment by rhelmot** [comment]
`_pos` is not an old attribute, it just what is used on the non-duplex SimFileDescriptor. This is what the very loud TODO is about. I'll fix this today.

**Comment by rhelmot** [comment]
Ugh. So. I tried to do a refactor to make ungetc work correctly all the time but that would have required storing the ungotten character outside the file and I didn't want to add the field to SimFileDescriptor, so I wanted to store it in the FILE struct we're simulating on disk, but then I ran into this massive problem which has been plaguing angr absolutely for ever, which is that if you say `auto_load_libs=False` then you will get externs generated for objects like stdout that absolutely do not have the correct size because _there is no way to get the right size for it_, and everything will fall apart.

FURTHERMORE, this ran into the OTHER issue that has been plaguing angr forever, which is that it's impossible to distinguish the `stdout` import symbol from an export symbol (???), and CLE will resolve its GOT slot as a reference to itself if you're using auto_load_libs=False, so realistically everything has already gone to shit and the fact that this isn't broken beyond belief is sort of a fluke.

You can see my attempted refactor on the re/ungetc branch.

**Comment by cq674350529** [comment]
Thanks for your reply and your efforts to make it work. I'll have a look your refactor.
