### ISSUE TITLE
`VariableRecovery` only works for stack pointer offsets

### ISSUE THREAD

**Issue by jabocken** [angr/angr#1173]
While the `VariableRecovery` analysis docstring claims it works for register/stack/heap/global variables, it appears to only be practical for stack variables in its current form. All memory offsets are calculated with respect to `rbp` and the `bp` register is thus hardcoded as the base, and even for cases where offsets are explicitly done in the binary/assembly with other registers as the base (such as with function arguments in the x86-64 System V ABI), the analysis does not handle them properly. Is there any work in progress on improving the effectiveness of that analysis or would I be better off just trying to fix it up myself?

**Comment by ltfish** [comment]
It should be tracking global variables as well. I never pushed the heap variable tracking support because my implementation was too buggy...

> Is there any work in progress on improving the effectiveness of that analysis or would I be better off just trying to fix it up myself?

You are welcome to do it by yourself, but I do plan to fix my code for identifying heap variables in the near future (i.e., within the next month or so). So you may also just wait for my updates.

**Comment by jabocken** [comment]
I'll wait on your updates for now, then, I'm currently only using the analysis to generate data that will ultimately be examined manually by humans so it's fine right now if not everything is captured.
