### ISSUE TITLE
Identifier needs further updating for filesystem refactor

### ISSUE THREAD

**Issue by Kyle-Kyle** [angr/angr#1190]
in angr/angr/state_plugins, line 476
~~~
stdin = state.posix.stdin.load(0, pos)
~~~
in angr/angr/analyses/identifier/runner.py, line 300
~~~
stdout = result_state.posix.stdout.load(0, result_state.posix.stdout.size)
~~~
stdin and stdout have been transformed to be `SimPacketsStream`, which makes above lines invalid. They don't have a `load` function like memory.

But I don't know fix how to fix it elegantly.

BTW, I wonder how to add constraints directly on stdin. I used to write something like `state.se.add(state.posix.files[0] == someting)`. But `state.posix.files[0]` does not work any more.

**Comment by rhelmot** [comment]
god I've explained this so many times

the point of the files refactor was so that if you want to access or constrain the file data, you now do so by creating a SimFile or SimPackets with some symbols that you created instead of relying on angr to create the symbols for you and then resetting the stream. Look at the filesystem page in the docs.

I guess we missed this spot during the refactor.

**Comment by rhelmot** [comment]
Could you please provide a testcase to reproduce this issue? From what I can tell, this should be impossible because Identifier and Rex (the only user of ChalRespInfo) always create their states with stdin and stdout as SimFiles, not SimPacketsStream.

**Comment by Kyle-Kyle** [comment]
I double checked it. I was my misunderstanding.
Sorry.
