### ISSUE TITLE
SimFile does not correctly concretize until after manual write

### ISSUE THREAD

**Issue by ConnorNelson** [angr/angr#1194]
```python
import angr

p = angr.Project('adobe_wichita')
simgr = p.factory.simgr()

def is_successful(state):
    return 'Correct!' in state.posix.dumps(1)

simgr.explore(find=is_successful)

found = simgr.found[0]
print('Incorrectly Empty: %s' % repr(found.posix.dumps(3)))
found.posix.fd[3].write_data('') # Solves issue
print('Correct: %s' % repr(found.posix.dumps(3)))

```

Result:
> WARNING | 2018-09-10 03:14:41,302 | cle.loader | The main binary is a position-independent executable. It is being loaded with a base address of 0x400000.
> WARNING | 2018-09-10 03:14:43,659 | angr.state_plugins.posix | Trying to open unknown file gjiwt - created a symbolic file since ALL_FILES_EXIST is set
> Incorrectly Empty: ''
> WARNING | 2018-09-10 03:14:44,087 | angr.storage.paged_memory | Nothing left of the memory object to store in SimPage.
> Correct: 'cul'

Binary:
[adobe_wichita.zip](https://github.com/angr/angr/files/2365035/adobe_wichita.zip)

**Comment by rhelmot** [comment]
lol, okay so

this is a weird as hell edge case. when angr gives you the empty result, that is a correct to a possibility out in the realm of whatever! This particular possibility is: the file was empty, and the read yielded zero bytes, but the data that was _already present in memory before the read_ just happened to be the correct answer. This is available to emulate because angr treats all uninitialized memory as totally symbolic, and the binary does not zero its malloc'd region before using it.

Doing the blank write contorts the expression for the "current file position" such that z3 just happens to concretize it differently, I think.

adding `angr.options.ZERO_FILL_UNCONSTRAINED_MEMORY` to the state makes the example work correctly.
