### ISSUE TITLE
How to make a http request?

### ISSUE THREAD

**Issue by shivakasu** [angr/angr#1205]
How can  I make a http request as input when analysing a binary file? I can't find any tutorial.

**Comment by schieb** [comment]
You need to implement a [SimProcedure](https://docs.angr.io/docs/simprocedures.html) for whatever library functions handle the http request. Most (all?) of the time, the library expects the programmer to make a sequence of calls, which may mean that you will need to implement more than one. The implementation can vary greatly from one library to another. A "bleeding-edge" implementation might use the new [filesystem features](https://github.com/angr/angr-doc/blob/master/docs/file_system.md). For a one-off, you can probably get away with returning a plain, fixed length symbolic buffer instead.

**Comment by rhelmot** [comment]
To elaborate on the bleeding edge stuff, since I'm pretty sure it's got a bus factor of 1 and I'd like to change that:

There's limited support in angr for providing data through sockets. There was at one point code written in a very old version of angr (2014?) to do this, but it badly bitrotted. In the filesystem refactor I tried to add back in a system to work with sockets nicely. It is currently 100% untested, so be careful.

The relevant code here is in the [socket(2)](https://github.com/angr/angr/blob/master/angr/procedures/posix/socket.py) and [accept(2)](https://github.com/angr/angr/blob/master/angr/procedures/posix/accept.py) simprocedures, along with [state.posix.open_socket](https://github.com/angr/angr/blob/master/angr/state_plugins/posix.py#L261).

There are two ways to provide data to back up a socket opened by the guest program: `socket_queue` and `sockets` parameters to `SimSystemPosix`.

`socket_queue` is extremely simple: every time a new socket is created, either through socket(2) or accept(2), an element is popped from this queue. If it's None, fall back to normal mechanisms, but if it's not, it must be a tuple of two SimFileBase subclasses, which are used as the receiving and sending storage backer mechanisms for the socket, respectively. So, if your program does the standard socket -> bind -> listen -> accept -> fork control flow, and you want to specify input for the client, you can do `state.register_plugin('posix', SimSystemPosix(socket_queue=[None, (input_file, output_file)]))`. Note that you probably want to specify a few more parameters to the SimSystemPosix, since this will blow away whatever was inserted into it by the state constructors (stuff like the stdin/stdout settings, argc, pointers to argv/envp/auxv, program break, a few other things... the posix plugin is a mess. you probably want to copy them from the original).

`sockets` is a bit more complicated. Anyone in angr who wants to open a socket must create an "identifier" for the socket, sort of like the "key" used to register variables with the solver's variable tracking mechanism: a tuple of identifiers in some sort of ad-hoc scheme. For sockets opened with socket(2), the identifer is `('socket', domain, type, protocol, nonce)`, where domain, type, and protocol are the arguments to socket(2), and nonce is just a sequence identifer: the first socket opened will be 1, the second will be 2, etc. (upon writing this I'm now realizing that the domain/type/protocol should not be in the identifier if there's this nonce. hm) For accept(2), the identifier is `('accept', parent_ident, nonce)` where parent_ident is the identifer of the socket that accept is called on (or `'unknown'` if the fd isn't a socket with an identifer) and nonce is an incrementing counter like the previous one, but with a sequence local to the parent!

For example, if you open two TCP listener sockets, their identifiers will be `('socket', 6, 2, 0, 1)` and `('socket', 6, 2, 0, 2)` (assuming I remember my socket.h values correctly). If a socket is accepted from the first, its identifier will be `('accept', ('socket', 6, 2, 0, 1), 1)`. Then, if a socket is accepted from the second, its identifier will be `('accept', ('socket', 6, 2, 0, 2), 1)`. THEN, if a socket is accepted from the first again, its identifier will be `('accept', ('socket', 6, 2, 0, 1), 2)`!

The long and the short of this is that `state.posix.sockets` is a dict mapping from socket identifier to tuple of the input and output SimFiles. So, you can use this to get data out of a socket even if its file descriptor has been closed! Additionally, this dict is consulted _before the socket queue_ while opening the socket, so you can use this as an alternate mechanism for specifying what data should be used to back a socket.

As a postscript: I don't know why there isn't a connect(2) simprocedure. Probably because we only ever want to analyze server programs with angr...
