### ISSUE TITLE
Function Identifier

### ISSUE THREAD

**Issue by lidgik** [angr/angr#1256]
I want to use angr identify function in compiled C program. Does identifier support it?

**Comment by lidgik** [comment]
I've tried the binary include atoi compiled by gcc 5.4 on ubuntu x64, but it cannot work.

**Comment by rhelmot** [comment]
Then it does not work.

**Comment by lidgik** [comment]
OK.

**Comment by Kyle-Kyle** [comment]
As far as I have tried on ELF, it can recover *some* functions reliably(the result was reliable in my test cases, not 100% sure it is reliable.). Because it uses test cases to verify identified functions.

If you give it a bunch of libc functions, it may recover some of them. And hopefully there are few false positives. But if you want it to recover some certain functions(atoi), it may not able to do so.

**Comment by salls** [comment]
keep in mind that since it was written for CGC lots of things may be hard coded for 32 bit x86

**Comment by ltfish** [comment]
Your best bet would be FLIRT. Identifier was implemented for CGC and was mostly tested for CGC binaries only.
