### ISSUE TITLE
Path Group not creating 2 active paths at branch after step

### ISSUE THREAD

**Issue by juk80x** [angr/angr#131]
I have a branching instruction that does not generate two paths after the path group steps.

```assembly
call sub_403060
mov rax, cs:qword_6C0F80
test rax, rax
jz loc_402C91
```

I created a SimIRSB of the basic block at the address after the call and looked to see how many successors it contained.

```python
sirsb = project.factory.sim_block(path_group.active[0].state)
print sirsb.all_successors
```

There were 2, but when I step the path_group there is only one active path at the first successor address. The value of `rax` is a `<BV64 0x0>`, which would appear to mean that angr had decided to not treat this value as symbolic. 

A concrete trace of this same binary results in `rax` being non-zero. 

I must be missing an option that will ensure that both paths are generated.

**Comment by rhelmot** [comment]
The address you're loading rax from looks like it's in the data section, so
it's probably zero by default, and gets initialized somewhere in the code
you skipped by starting a block right at that load. angr is doing the right
thing here - in the state that you told it to tick forward, it was
impossible for that branch to not be taken.

If you'd like it to be symbolic, you can manually store a symbolic value
there, or you can run the program from the beginning; presumably somewhere
along the line that variable gets modified.

**Comment by juk80x** [comment]
Why do you assume I skipped code? 

I created the path group with 

```python
state = project.factory.entry_state()
path_group = project.factory.path_group(state)
```

And then I started stepping.

**Comment by rhelmot** [comment]
Alright, assuming that you correctly stepped the path group up until the address of the load, here are the things off the top of my head that could explain the discrepancy between what you observed in the trace - 

- There are multiple paths in path_group.active, some of which have the variable set to 1 and the others have the variable set to 0. this would mean that the state had already split earlier in execution so there's no need to split it again
- This value is dependent on argc or argv. By initializing the entry_state that way, the program is being run with a null argv and zero argc. `entry_state(args=['./mybinary'])` is a good place to start
- This value is dependent on values that are initialized in the shared library initializers. Those take a bit of time to step through, but if you want the emulated state to match a real state as closely as possible, you should use full_init_state instead of entry_state.
- There's a bug somewhere in angr causing this.

If I were debugging this in person, I would open that binary in IDA and try to figure out the semantic meaning of that variable and the meaning of the decision that it is zero at that point in execution, and then try to figure out why angr failed to do the thing that the program expects at the high level.

**Comment by zardus** [comment]
So I just stumbled onto this looking into another issue. It looks like `project.factory.path_group` uses `project.factory.path` to create a path when one is not provided. In turn, this uses `project.factory.entry_state`. Shouldn't we be using `full_init_state` by default? What do you think, @rhelmot?

**Comment by rhelmot** [comment]
Well there's no guarantee that this is actually the problem that juk80x is running into.

But I did just check and it takes less than half a second to step through the initializers for /bin/true on amd64, so it looks like this is feasible. I think it would be fine to have the default state that gets created by path and path_group be a full init state.

This still wouldn't solve juk80x's problem here since they manually specified entry_state. Do we care about the entry state designation at all, then, if it's so cheap to run the initializers? Should entry state just be an alias to full_init_state?

And while we're talking about saner defaults to fix common problems - if it turns out that juk80x's problem is the null argv, do we want to have the default args be just the basename of the program? I proposed that default when I was designing this version of that interface, and recall being told that it was a bad idea, but maybe times have changed.

**Comment by zardus** [comment]
I think that `full_init_state` definitely makes sense as the default. I'd keep `entry_state` as-is for now. Alternatively, we can make `entry_state` an alias to `full_init_state`, but make the whole thing take a `run_initializers=True` kwarg?

Regarding argv, the two things that make sense to me are either just the basename or a symbolic argv up to some amount. I'm a tad wary of having symbolic data injected into the program from the get-go, though.

**Comment by juk80x** [comment]
I was originally setting argv properly. Sorry for leaving that out. I tried full_init_state with the same result. 

When I break on the address in gdb and look at the contents of the data segment it is shows the following. 

```assembly
0x6c0f80   <_dl_random>   0xffffe209  0x00007ffff  
```
This address is set during the call to _dl_aux_init()

**Comment by rhelmot** [comment]
Oh jeez. Looks like you're interacting with the loader in a way we don't support yet. angr technically acts as the dynamic loader for programs, but also loads the requested interpreter (the loader) into memory, even though we take great care to catch attempts to execute code in it. So _dl_random is going uninitialized since we pretty much have to emulate features the dynamic loader provides on a case-by-case basis, since it it one hundred percent infeasible to emulate the execution of the dynamic loader itself.

Can you upload the binary you're running and all the shared libraries it depends on, including the dynamic loader? I've never encountered anyone using _dl_random so I'm not sure how to emulate it correctly.

**Comment by juk80x** [comment]
This was against amadhj from the 2016 Defcon Quals. 

https://github.com/legitbs/quals-2016/tree/master/amadhj

**Comment by rhelmot** [comment]
That link is to source, not a binary. Are you using the binary distributed during quals or did you recompile it on your own?

And again, can you send me the shared libraries angr is picking up and loading? They are probably different on my system than on yours, and could affect my ability to reproduce it.

Also, what address in what binary is the branch in question at?

**Comment by Manouchehri** [comment]
Binary is here. https://drive.google.com/open?id=0B2dML63ame9bYW9rTWxaVWZvc00 (sha1sum `8a1da96cf493e434f147cc7d00a1519b2c70309a`)

**Comment by rhelmot** [comment]
Yes, I know, I played in quals too, I have the binary they distributed. Since he linked me to source, it's possible he recompiled it himself. Also, I need the shared libraries he's using and the address of that branch instruction we're looking at.

**Comment by rhelmot** [comment]
brief apology to the people involved in this thread: I'm sorry I'm being so snippy about this, I'm in the middle of finals and am pretty close to the end of my rope... I just want to be able to debug this problem and be done with it.

**Comment by juk80x** [comment]
Here is the binary. It was built statically. 

[amadhj.zip](https://github.com/angr/angr/files/297810/amadhj.zip)

**Comment by rhelmot** [comment]
So it looks like the specific thing that's happening is that angr isn't providing an AT_RANDOM entry in the auxiliary vector. That's where that pointer is supposed to come from.

Or at least that's what I'm about 90% sure is going on from just looking at the binary in IDA - I'm unable to step the binary to that point at all, angr errors out before it gets to that point because it tries to call the unsupported uname syscall. Did you add the bypass unsupported syscalls option? Can you post the full trace of your path (path_group.active[0].trace.hardcopy)?

**Comment by juk80x** [comment]
I did add the bypass unsupported syscalls option. I guess the bigger question I have for circumstances like this is why a symbolic variable isn't returned? That way when the branch happens both paths become possible.

```python
['<SimIRSB 0x400f4e>', '<SimIRSB 0x402a00>', '<SimIRSB 0x402ce9>', '<SimIRSB 0x402a41>', '<SimIRSB 0x402a7b>', '<SimIRSB 0x438fe0>', '<SimIRSB 0x439104>', '<SimIRSB 0x402a80>', '<SimIRSB 0x402c19>', '<SimIRSB 0x402c27>', '<SimIRSB 0x402c60>', '<SimIRSB 0x402a8e>', '<SimIRSB 0x402be3>', '<SimIRSB 0x439ea0>', '<SimIRSB 0x45ffa0>', '<Syscall (Unsupported)>', '<SimIRSB 0x45ffa7>', '<SimIRSB 0x45ffb3>', '<SimIRSB 0x439eb3>', '<SimIRSB 0x439ec3>', '<SimIRSB 0x439ed3>', '<SimIRSB 0x439f07>', '<SimIRSB 0x439f19>', '<SimIRSB 0x439ec8>', '<SimIRSB 0x439ed3>', '<SimIRSB 0x439ee7>', '<SimIRSB 0x439f07>', '<SimIRSB 0x439f19>', '<SimIRSB 0x439ec8>', '<SimIRSB 0x439ed3>', '<SimIRSB 0x439f07>', '<SimIRSB 0x439f29>', '<SimIRSB 0x439f1f>', '<SimIRSB 0x402be8>', '<SimIRSB 0x402bf0>', '<SimIRSB 0x402bfe>', '<SimIRSB 0x402a9c>', '<SimIRSB 0x402aa9>', '<SimIRSB 0x402abd>', '<SimIRSB 0x402ad5>', '<SimIRSB 0x418710>', '<SimIRSB 0x418719>', '<SimIRSB 0x43a060>', '<SimIRSB 0x43a087>', '<SimIRSB 0x43a093>', '<SimIRSB 0x43a0ca>', '<SimIRSB 0x43a0eb>', '<SimIRSB 0x43a0f5>', '<SimIRSB 0x41871e>', '<SimIRSB 0x418738>', '<SimIRSB 0x402ad8>', '<SimIRSB 0x402ac8>', '<SimIRSB 0x402ad5>', '<SimIRSB 0x485800>', '<SimIRSB 0x48580e>', '<SimIRSB 0x48581a>', '<SimIRSB 0x48582d>', '<SimIRSB 0x485840>', '<SimIRSB 0x402ad8>', '<SimIRSB 0x402ac8>', '<SimIRSB 0x402ad5>', '<SimIRSB 0x418960>', '<SimIRSB 0x41896e>', '<SimIRSB 0x418981>', '<SimIRSB 0x418994>', '<SimIRSB 0x402ad8>', '<SimIRSB 0x402ac8>', '<SimIRSB 0x402ad5>', '<SimIRSB 0x41e230>', '<SimIRSB 0x41e23e>', '<SimIRSB 0x41e24a>', '<SimIRSB 0x41e25d>', '<SimIRSB 0x41e270>', '<SimIRSB 0x402ad8>', '<SimIRSB 0x402ac8>', '<SimIRSB 0x402ad5>', '<SimIRSB 0x41d560>', '<SimIRSB 0x41d56e>', '<SimIRSB 0x41d57a>', '<SimIRSB 0x402ad8>', '<SimIRSB 0x402ac8>', '<SimIRSB 0x402ad5>', '<SimIRSB 0x41d1d0>', '<SimIRSB 0x41d1de>', '<SimIRSB 0x402ad8>', '<SimIRSB 0x402ac8>', '<SimIRSB 0x402ad5>', '<SimIRSB 0x41db30>', '<SimIRSB 0x41db3e>', '<SimIRSB 0x41db61>', '<SimIRSB 0x402ad8>', '<SimIRSB 0x402ac8>', '<SimIRSB 0x402ad5>', '<SimIRSB 0x41ab90>', '<SimIRSB 0x41ab9e>', '<SimIRSB 0x41abb1>', '<SimIRSB 0x41abcb>', '<SimIRSB 0x402ad8>', '<SimIRSB 0x402ac8>', '<SimIRSB 0x402ad5>', '<SimIRSB 0x41e110>', '<SimIRSB 0x41e11e>', '<SimIRSB 0x41e131>', '<SimIRSB 0x41e14b>', '<SimIRSB 0x402ad8>', '<SimIRSB 0x402ae9>', '<SimIRSB 0x403060>', '<SimIRSB 0x402de0>', '<SimIRSB 0x402dfa>', '<SimIRSB 0x402e29>', '<SimIRSB 0x402e20>', '<SimIRSB 0x402e29>', '<SimIRSB 0x402e20>', '<SimIRSB 0x402e29>', '<SimIRSB 0x402e20>', '<SimIRSB 0x402e29>', '<SimIRSB 0x402e2e>', '<SimIRSB 0x402e5d>', '<SimIRSB 0x4363d0>', '<SimIRSB 0x436418>', '<SimIRSB 0x460580>', '<Syscall (brk)>', '<SimIRSB 0x46058c>', '<SimIRSB 0x460597>', '<SimIRSB 0x4605a5>', '<SimIRSB 0x43641f>', '<SimIRSB 0x4363ef>', '<SimIRSB 0x4363f5>', '<SimIRSB 0x4363f7>', '<SimIRSB 0x4363ff>', '<SimIRSB 0x460580>', '<Syscall (brk)>', '<SimIRSB 0x46058c>', '<SimIRSB 0x460597>', '<SimIRSB 0x4605a5>', '<SimIRSB 0x436405>', '<SimIRSB 0x436409>', '<SimIRSB 0x402e84>', '<SimIRSB 0x402ea9>', '<SimIRSB 0x423740>', '<SimIRSB 0x4237c0>', '<SimIRSB 0x423800>', '<SimIRSB 0x423809>', '<SimIRSB 0x423810>', '<SimIRSB 0x423870>', '<SimIRSB 0x42387e>', '<SimIRSB 0x402ee9>', '<Syscall (Unsupported)>', '<SimIRSB 0x402f0d>', '<SimIRSB 0x402f30>', '<SimIRSB 0x402f84>', '<SimIRSB 0x402aee>', '<SimIRSB 0x402c91>', '<SimIRSB 0x435939>', '<Syscall (open)>', '<SimIRSB 0x435940>', '<SimIRSB 0x43594c>', '<SimIRSB 0x402ca6>', '<SimIRSB 0x402cac>', '<SimIRSB 0x435999>', '<Syscall (read)>', '<SimIRSB 0x4359a0>', '<SimIRSB 0x4359ac>', '<SimIRSB 0x402cbd>', '<Syscall (close)>', '<SimIRSB 0x402cc9>', '<SimIRSB 0x402cd8>', '<SimIRSB 0x402b0d>', '<SimIRSB 0x402c4a>', '<SimIRSB 0x402b23>', '<SimIRSB 0x402b3d>', '<SimIRSB 0x439fb0>', '<SimIRSB 0x43a010>', '<SimIRSB 0x439fda>', '<SimIRSB 0x439e50>', '<SimIRSB 0x439e60>', '<SimIRSB 0x4602b0>', '<Syscall (Unsupported)>', '<SimIRSB 0x4602b7>', '<SimIRSB 0x439e66>', '<SimIRSB 0x4602a0>', '<Syscall (Unsupported)>', '<SimIRSB 0x4602a7>', '<SimIRSB 0x439e6d>']
```

**Comment by rhelmot** [comment]
In the general case this is impossible to fix - there's no "symbolic variable that isn't returned" - the value you're branching on is null by default because it lives in the .bss section, and there's no way to know that this particular value should not be null under some circumstances. If you really want to step this branch forward, there should be somewhere you can grab the unsatisfiable successors and manually remove the unsatisfiable path predicates from the constraints list - there's a technique called under-constrained symbolic execution that does something like this, but then you're moving into the realm of static analysis.

On the other hand, I don't really think that this branch in particular should really affect angr's overall ability to analyze this binary? this is just an initialization quirk in the middle of __libc_start_main, which is pretty good at handling lots of different degenerate initialization cases. If you just let it keep running it should totally get to main and execute correctly. (as an aside, I talked to the shellphish member who solved this challenge during quals, they used angr, but not by executing from the entry point forward, they manually pointed angr at the munge function.)

I've pushed something to github that adds the AT_RANDOM auxiliary vector entry. It should make your branch go the right way.

**Comment by juk80x** [comment]
This fixed the issue. Thanks!
