### ISSUE TITLE
angr failed to resolve errno in simos.py.

### ISSUE THREAD

**Issue by aencode** [angr/angr#1324]
```
>>> proj=angr.Project('/bin/true')
WARNING | 2018-12-10 05:49:14,309 | cle.loader | The main binary is a position-independent executable. It is being loaded with a base address of 0x400000.
ERROR   | 2018-12-10 05:49:14,363 | angr.simos.simos | Resolver at 0x107fa90 failed to resolve!
ERROR   | 2018-12-10 05:49:14,377 | angr.simos.simos | Resolver at 0x1086030 failed to resolve!
ERROR   | 2018-12-10 05:49:14,390 | angr.simos.simos | Resolver at 0x1099bd0 failed to resolve!
```

simos.py

```
except AngrCallableError:
                _l.error("Resolver at %#x failed to resolve!", resolver_addr)
                return None
```

Can anyone please help me to understand this problem ?
I have installed angr using pip3 on debian machine.

**Comment by rhelmot** [comment]
This is a problem about "irelative relocations". these are relocations for which the program specifies a function (a "resolver") which should be called to find the address that should be written into memory. angr will attempt to run them ("resolve" them) in order to find the value that should be written into memory when the project is loaded.

If you want to interrogate this, you want to set a breakpoint in `callable.py` for the line which is raising the exception - I suspect this is line 76, "No paths returned from function". You then want to examine the `caller` simulation manager - it probably has an errored state, so you want to look at the error, and then track that down.

**Comment by rhelmot** [comment]
So - this means that angr is unable to process the code which is in memory at address 0x207fa90. There are two potential solutions to this - 1) angr _should_ be able to handle the code at this address, and to make it work, or 2) angr _should not_ be executing code at this address. We should figure out which one this is. My bet is on the latter.

The first step is to take that address, 0x207fa90, and plug it into `project.factory.describe_addr()`. it will tell you what's at that address, in the form of the binary it's part of and the nearest function symbol. My bet is that it will be in `ld-linux.so`, the linux dynamic linker. Executing code from this object in angr is generally bad.

The next step is to actually figure out what the code at that address is. angr can do this, but since we're debugging angr you should use another disassembler, like IDA or objdump. Take the un-rebased address and the binary object name from describe_addr and use it to find the code in a disassembler. If it actually looks like real code instead of data being interpreted as code, we're in case 1), but if it looks like garbage, we're in case 2).

The third step is to figure out _how_ the state got here. angr conveniently tracks the history of every state automatically, through the state.history plugin. (you can get at the actual state you want to work with via `caller.errored[0].state`. The things you want are probably `state.history.descriptions.hardcopy`, which will tell you the kind of code angr executed (basic blocks, simprocedures, syscalls) at each step along the way, and `state.history.bbl_addrs.hardcopy`, which will give you each address executed - you probably want `[project.loader.describe_addr(addr) for addr in state.history.bbl_addrs.hardcopy]` in order to see the full view of what is being executed in terms of binaries and functions.

If you do these three things and post the results, I can help you with what to do next.
