### ISSUE TITLE
Concrete exection & Symbion

### ISSUE THREAD

**Issue by ChrisMcMStone** [angr/angr#1475]
I'm trying to understand what exactly the Symbion extension enables you do to which wasn't already possible. I understand that it allows you to concretely execution up until a point, say A -> B and then only invoke symbolic execution tracking for a later point, say B -> C. This would enable you to avoid any complex code in A -> B that might cause state explosion and which we don't have SimProcedures to model/summarise all functions.

Now, given that, my question is: without using Symbion, is it not already possible to begin symbolic exection from a given state in the program, maybe by specifying it with the state preset .call_state() i.e.
'B' and symbolically execute up until 'C'? Or would Angr always attempt to execute from the entry point of the program?

To give you some context, my goal is to concretely execute from a point B, to a point C, tracking constraints along that execution path, then backtrack by negating some of those constraints to explore different paths.

I hope this make some sense somewhat and really appreciate any help/advice!

**Comment by degrigis** [comment]
Hey @ChrisMcMStone, sorry for the late answer!

It is absolutely possible to start the execution at whatever point of the program using the call_state interface, but in some cases, you care about the state that will bring the program to that point and you can't ignore everything and simply start the execution there. It's also true that sometimes due to SimProcedures behaviors approximation or the lack of support for specific calls or for other reasons, you can't or don't want to start the execution from the entry point. 

Symbion tries to solve this problem by letting you "import" the concrete state of a program inside angr.

Example:
Imagine that you have a packed malware that implements a complex runtime unpacking routine, you can't simply start to symbolically execute from a specific point because you don't have the real code yet, nor you can start from the beginning because angr hangs. What you can do is bring the executable in a state in which you have the unpacked code in memory ( using a debugger or whatever analysis environment for which a ConcreteTarget exists ), synchronize the concrete state into angr and starts to symbolically execute the unpacked code with a correct memory state. 

This is just an example of how you can use Symbion to skip parts of the program that are too complex to track or simply that you don't care of, other use cases can be the analysis of very complex software like a browser, an hypervisor etc...

Check out our example at http://angr.io/blog/angr_symbion :-)

Let me know if this makes sense for you or if you have any other questions!
