### ISSUE TITLE
Return edges missing in CFGFast

### ISSUE THREAD

**Issue by axt** [angr/angr#148]
I've used this toy example to generate both type of `CFG`-s:
```
int f() {
        printf("x");
}

int main() {
        f();
}
```

It seems that when running `CFGFast` the return edges are missing.

CFGAccurate    |    CFGFast
-------------------------- | ----------------------------------------------------------
![cfgacc](https://cloud.githubusercontent.com/assets/759365/16235246/78ba62e4-37d4-11e6-8f4f-5a9e660273a6.png)  |  ![cfgfst](https://cloud.githubusercontent.com/assets/759365/16235255/7fbde0f2-37d4-11e6-88bb-6d676b21ba26.png)

**Comment by axt** [comment]
Added the binary and the code to create the cfg-s, to make it easier to test:
[test.zip](https://github.com/angr/angr/files/325949/test.zip)

**Comment by ltfish** [comment]
Thanks for reporting. This is a known issue and will be fixed.

**Comment by F4lc0nCt** [comment]
I know you all have a lot of work with the preparation of the challenge, but do you know when this issue will be fixed? I am currently working with angr in order to extract paths to a targeted node. I have used the CFGFast analysis and I have tried to link the endpoints of the callee functions to their respective caller node (or the fake return node if there is one). However, I think there is a better way to do.
I am thinking to use the CFGAccurate analysis to do this analysis as the author of this thesis (that I found on your web-page because the author used angr) underlines [Combining Static Analysis and Targeted Symbolic Execution for Scalable Bug-Finding in Application Binaries](https://uwspace.uwaterloo.ca/bitstream/handle/10012/10500/Parvez_MuhammadRiyad.pdf?sequence=1&isAllowed=y). However, on the angr freenode chat, one person told me that CFGFast is often sufficient to do a path analysis. Therefore, I am a bit lost. Could you give me some advice? Thank you.

**Comment by ltfish** [comment]
> but do you know when this issue will be fixed?

During the week of August 4th, 2016.

> However, on the angr freenode chat, one person told me that CFGFast is often sufficient to do a path analysis.

I would say so. CFGAccurate and CFGFast have different design goals. CFGFast resolves indirect jumps by heuristics and some lightweight data-flow tracking, while CFGAccurate simulates the execution of basic blocks on a program state in a best-effort manner. Thus, apparently, CFGAccurate is way slower. If everything you want to do is to extract paths to a specific node on a binary without too many indirect jumps, you can just use CFGFast to generate a full-program CFG, and then try to find one or more paths from the entry point to your target, in a function-by-function way (i.e. find a series of function calls from the beginning to the target function, and then expand that call trace into a full basic-block level path).

As it is right now, CFGAccurate is not _that_ more accurate than CFGFast on binaries that don't have too many indirect jumps. It needs more care and love to make it more accurate, and, faster. Instead of waiting for our fixes (which won't be released before August), I believe CFGFast should be a good start for you.

Also, CFGFast and CFGAccurate share quite a few APIs. It's not hard to switch from one to the other in the future, if you want!

**Comment by F4lc0nCt** [comment]
Thank you for your answer.

> you can just use CFGFast to generate a full-program CFG, and then try to find one or more paths from the entry point to your target, in a function-by-function way (i.e. find a series of function calls from the beginning to the target function, and then expand that call trace into a full basic-block level path).

I think I will try to work on the paths with the function-by-function approach. In fact, my current goal is to try to leverage static analysis to target a specific node (this is why I am interested in finding paths).

> Also, CFGFast and CFGAccurate share quite a few APIs. It's not hard to switch from one to the other in the future, if you want!

I have run some analyses with both CFGs and I have seen that one analysis could erase some pieces of information gathered by the other analysis (like the list of functions). Is it better to work on two separates projects to build the two graphs or do you think it is not so serious to build both graphs in the same project?

**Comment by ltfish** [comment]
> I have run some analyses with both CFGs and I have seen that one analysis could erase some pieces of information gathered by the other analysis (like the list of functions). Is it better to work on two separates projects to build the two graphs or do you think it is not so serious to build both graphs in the same project?

There is a notion that is not very well documented in angr: `KnowledgeBase`. The list of functions are stored in the knowledge base you pass in to `project.analyses.CFG(kb=xxx)` or `project.analyses.CFGAccurate(kb=xxx)`. If you don't specify the `kb` parameter, it will use the default knowledgebase associated with the project itself. Every time you create a CFG, the function list in its associated knowledgebase will be erased and recreated. Therefore you don't have to create two separate projects, just create two separate knowledge bases and pass them to different analyses, respectively.

**Comment by axt** [comment]
I've rerunned the test with the new angr release:

CFGAccurate    |    CFGFast
-------------------------- | ----------------------------------------------------------
![cfgacc](https://cloud.githubusercontent.com/assets/759365/17601464/953184d2-6008-11e6-9890-f300291af09b.png) | ![cfgfst](https://cloud.githubusercontent.com/assets/759365/17601470/9d606c5e-6008-11e6-88ea-277344ceeb98.png)

The return edges still missing in CFGFast plus there is a new UnresolvableTarget node.

**Comment by ltfish** [comment]
@axt Correct! I didn't merge my changes in before CGC since it may potentially break other parts of our CRS (and I don't want to be the one to blame). Changes will be merged in when I have some time to rebase :-)

**Comment by ltfish** [comment]
Eventually! Commit 53df609 should have fixed this problem. Please let me know if it does not work as expected.

**Comment by axt** [comment]
Works like a charm! Thanks!
