### ISSUE TITLE
stack-buffer-overflow detection

### ISSUE THREAD

**Issue by macromachine** [angr/angr#1536]
Hi, I have read you paper "(State of) The Art of War: Offensive Techniques in Binary Analysis".
You described that it could use VSA for memroy corrution detection in three phases.
But I did not find the corresponding codes. How do I use Angr to locate stack-buffer-overflow?
Thanks.

**Comment by ltfish** [comment]
We did not include the code for static stack buffer overflow detection in angr. You'll have to implement the analysis on top of the functionality that angr provides by yourself.

**Comment by macromachine** [comment]
> We did not include the code for static stack buffer overflow detection in angr. You'll have to implement the analysis on top of the functionality that angr provides by yourself.

How about global-buffer-overflow and heap-buffer-overflow? Do I also inlement by my myslef?

**Comment by ltfish** [comment]
angr does not detect buffer overflows using static analysis in any way. Due to the inaccuracy of such analyses, including them in angr will only cause confusion for people who are not experts in program analysis and put more burden on us of providing support. So no, currently there is no static analysis code that will detect buffer overflows in angr. You will have to implement the analysis by yourself.

That said, implementing the analysis can be as simple as going over the alocs generated by running `VFG`. Of course, it's your own business to deal with false positives and false negatives.

**Comment by macromachine** [comment]
> angr does not detect buffer overflows using static analysis in any way. Due to the inaccuracy of such analyses, including them in angr will only cause confusion for people who are not experts in program analysis and put more burden on us to provide support. So no, currently there is no static analysis code that will detect buffer overflows in angr. You will have to implement the analysis by yourself.
> 
> That said, implementing the analysis can be as simple as going over the alocs generated by running `VFG`. Of course, it's your own business to deal with false positives and false negatives.

I see, thanks very much.

**Comment by ltfish** [comment]
You are welcome.
