### ISSUE TITLE
Analyzing isolated code fragments

### ISSUE THREAD

**Issue by mephi42** [angr/angr#1571]
I have a large binary, in which I would like to analyze not even a single function, but rather a code fragment inside one of the functions. `CFGFast` has `regions` parameter for that, but what about `CFGEmulated`, `VFG` and others? Can I somehow ask `Project`/`Loader` to limit what they expose to analyzers?

**Comment by rhelmot** [comment]
Generally, the design paradigm in angr is that options like that need to be exposed on a per-analysis basis. Scoping, as it turns out, is hard.

In an idealized future where we're actively using the knowledge base for lots of things, you could curate your starting knowledge base so it contained exactly the data you want to be in scope. For now the best you can do is carving the code you care about into a blob and loading that.

**Comment by mephi42** [comment]
Ok, I see.

In the meantime, I realized that `VFG` has `avoid_runs`, which suits my use case pretty well.
