### ISSUE TITLE
Question: taint tracking

### ISSUE THREAD

**Issue by axt** [angr/angr#159]
I would need some kind of taint tracking for my analysis process. 

Are there any future plans to add taint tracking to `angr`?

Can you share some thoughts, how it should be implemented? (simuvex plugin maybe?)

I know this question is very general in this form, but i thought, its a good conversation starter.

(I know CGC final is coming, so feel free to answer it after.)

**Comment by ltfish** [comment]
Currently with too much stuff on my plate, I'm not in a sane state to talk about new features in angr. Here are my two cents, hopefully they make sense.

I'm not sure if you are referring to taint-tracking in dynamic concrete execution, or taint-tracking in symbolic execution. For the former, although angr can perform dynamic concrete execution (with pure-Python simulation right now, and with Unicorn in the upcoming August), I'm not sure if taint tracking on it is what you need. The execution overhead of angr will kill any performance gain from implementing a taint tracking technique instead of a dependency tracking technique. It'll be great if you can elaborate on why you need taint tracking, other than a general dependency tracking technique.

We definitely don't have a working taint tracking implementation in angr right now, but I have some experimental code for dependency tracking in symbolic execution before. I'll definitely polish the code and add it to angr in August.

**Comment by axt** [comment]
@ltfish : I have lots of  stuff to handle right now too. I would propose to get back to this conversation mid/late August, if you are open to that. Thanks.

**Comment by ltfish** [comment]
>  I would propose to get back to this conversation mid/late August, if you are open to that.

Absolutely! I'll keep this issue open, and ping you in a month :-)

**Comment by Manouchehri** [comment]
@axt Have you looked into [Triton](http://triton.quarkslab.com/) for taint tracking?

**Comment by axt** [comment]
@Manouchehri: thanks, its on my todo list!

@ltfish: lol, don't worry, i will notify you about it :-). 
Btw: congrats for the #cgc, can't wait the new angr release!

**Comment by rhelmot** [comment]
It's possible the solution you're looking for is [https://github.com/angr/claripy/blob/master/claripy/annotation.py](annotations!) Annotations are, effectively, a customizable tainting interface that let you add whatever extra data you want to any value in angr. There's also a (more complicated) interface that lets you query ASTs for any properties you like, including any custom logic you could desire for mixing annotations - (https://github.com/angr/claripy/blob/master/claripy/backends/__init__.py)[claripy backends]. Look at (this simple type analysis backend)[https://github.com/angr/simuvex/blob/master/simuvex/s_type_backend.py] for a good example for how to use backends and annotations to intelligently propagate taints with semantic information.

**Comment by rhelmot** [comment]
Sorry, I messed that markdown up pretty badly the first shot. Should be edited and fixed now.

**Comment by axt** [comment]
@rhelmot Thanks for the hint. I saw it in fidget's code and already started to experiment with it. I think its something I was looking for, and that answers @ltfish 's question, that I mostly need taint tracking in symbolic execution. Unfortunatelly I'm also quite busy at the moment, but still looking for to discuss this topic more deeply a bit later. 

Have some remarks about OffsetAnalysis in fidget, but I didn't wanted to open an issue to them, because I think its "in development". Maybe you know about these, but if not, I hope they will be helpful:
- you use normalized cfg in the analysis, but the initial marking of accesses rely on simple lifting, which can cause some inconsistencies with access locations, that get into another basic block after normalization 
- BlanketExecution quits enumerating paths after the first call found during the path, because when following the FakeRet edge to continue the path after the call, _exit_target returns the FakeRet edge as a simple Ret edge, and then the path  gets into the 'finished' stash

**Comment by rhelmot** [comment]
- I do not rely on simple lifting!

```python
block = self.project.factory.block(node.addr, max_size=node.size)
```

`node` is a node from a normalized CFG, so it has the correct size. As far as I've seen, there have been no issues with access locations moving around under me.

- I'm not sure exactly what you're talking about, but I think the issue you're pointing out is resolved by my instrumentation of block exits, the `_exit_taken` function. I explicitly add the fakeret jump in there when I want to continue execution. In general, I don't think glaring problems like the ones you're talking about exist, since my testing on the in-progress code involves making sure I have block coverage.

**Comment by axt** [comment]
Sorry for the noise! 

I just realized, that the probems I see maybe arise from my patches:
Since node was undefined in line 554 in new_analysis.py, i've applied this change:
```diff
-        path.step(num_inst=len(node.instruction_addrs) if node is not None else None)
+        path.step()
```
Plus changed the code to get the CFG from the caller.

**Comment by rhelmot** [comment]
hahahahaha I looked at the fidget history and the last commit to new_analysis.py was https://github.com/angr/fidget/commit/d25584a18c361484d44d49a36160c915441d9e56 which is pretty clearly just me dumping my in-progress changes into a commit as it became obvious that it wasn't gonna get finished in time for cgc. It introduces that bug, yeah. I haven't run the file since then! I pushed a fix.

I'm going to close this for now, you can either open an issue on fidget, open an issue in claripy to discuss annotations, or use the mailing list to continue this conversation :)
