### ISSUE TITLE
Segfault in CFGFast

### ISSUE THREAD

**Issue by gannimo** [angr/angr#1607]
When analyzing an ARMEL ELF library, the analysis dies with a segfault:

```
ERROR   | 2019-06-12 15:44:51,920 | angr.analyses.cfg.cfg_fast | Decoding error occurred at address 0x4129ca of function 0x4129ca.
WARNING | 2019-06-12 15:44:51,929 | angr.analyses.cfg.cfg_base | Unexpected edge with ins_addr being None: <CFGNode 0x406127[20]> -> <CFGNode 0x407139[4]>, data = {'ins_addr': None, 'jumpkind': 'Ijk_Call', 'stmt_idx': None}.
WARNING | 2019-06-12 15:44:51,985 | angr.engines.vex.engine | The .next property of IRSB 0x402794 has an unexpected value None. has_default_exit will be set to False.
WARNING | 2019-06-12 15:44:52,007 | angr.engines.vex.engine | The .next property of IRSB 0x4029cc has an unexpected value None. has_default_exit will be set to False.
WARNING | 2019-06-12 15:44:52,081 | angr.engines.vex.engine | The .next property of IRSB 0x403760 has an unexpected value None. has_default_exit will be set to False.
ERROR   | 2019-06-12 15:44:52,182 | angr.engines.vex.irop | Unsupported operation: Iop_GetElem32x2
[1]    26234 segmentation fault  python3
```

Steps to reproduce:
```
$ python3
>>> import angr
>>> proj = angr.Project('libgifimage_0ABB272C052C097FF4B3FE447F68F9CC81569BEAB3925DE8432D6125947FCFB6.so')
WARNING | 2019-06-12 15:49:14,560 | cle.loader | The main binary is a position-independent executable. It is being loaded with a base address of 0x400000.
WARNING | 2019-06-12 15:49:14,562 | cle.backends.externs | Symbol was allocated without a known size; emulation will fail if it is used non-opaquely: __stack_chk_guard
WARNING | 2019-06-12 15:49:14,562 | cle.backends.externs | Symbol was allocated without a known size; emulation will fail if it is used non-opaquely: __sF
WARNING | 2019-06-12 15:49:14,563 | cle.loader | For more information about "Symbol was allocated without a known size", see https://docs.angr.io/extending-angr/environment#simdata
>>> proj.analyses.CFGFast()
```

I installed angr based on `pip3 install angr`

**Comment by ltfish** [comment]
Obviously I can transfer issues between GitHub repos now! YAY!

@gannimo Just sent you an email.

**Comment by subwire** [comment]
@ltfish yes, but if the issue is missing data references causing code/data confusion, then the only ways to solve it are to either get it completely right, or tolerate when it fails. Since we can't guarantee getting it right enough to get rid of all such cases, we do need to add some robustness and error-handling there as well at some point.

I have tons and tons of examples of why this is a problem, virtually every binary from #ARMCFGParty had a similar issue, so I just turned `force_complete_scan` off in all my code.

**Comment by ltfish** [comment]
> Since we can't guarantee getting it right enough to get rid of all such cases, we do need to add some robustness and error-handling there as well at some point.

That is the deep root cause. I understand that we can never fully differentiate code from data. I'm just talking about the shallower root cause that is deeper than the band-aid that PR #1180 introduces.

Again, with or without the band-aid, it should not crash. So I'll wait for the binary to arrive before speculating what might be happening.

**Comment by gannimo** [comment]
Thanks for moving the issue; I had too many tabs open at the time (blame it on confused faculty brain as well). I've resent the file to your gmail, hoping it gets through this time. Let me know if you have not received the faulting SO.
