### ISSUE TITLE
Couldn't handle R_386_PC32?

### ISSUE THREAD

**Issue by fastbins** [angr/angr#163]
```
cat > test.c << EOF
#include <stdio.h>
int main()
{
    puts("TESTESTEST\n");
    return 0;
}
EOF

gcc -Wall -c -o test.o test.c  -m32
gcc -o test test.o -m32 -fPIE -pie 

readelf -a test | grep R_386_PC32
```
Output:
`xxxxxxxx  xxxxxxxx R_386_PC32        00000000   puts`

```
cat > angrbug.py << EOF
import angr
p = angr.Project('./test', load_options={"auto_load_libs": True})
es = p.factory.entry_state(args=["./test"])
pg = p.factory.path_group(es, immutable=False)
pg.explore()
print(pg.errored)
EOF

python angrbug.py
```
Result in the following AngrMemoryError:
```
[<Errored Path with 26 runs (at 0x4c651b4, AngrMemoryError)>]
```

This happens only when the library function is link(and relocated) with R_386_PC32 and {"auto_load_libs": True}.

**Comment by zardus** [comment]
Hello, we're in full CGC mode at the moment. We'll definitely get to this issue after DEFCON!

**Comment by rhelmot** [comment]
This is fixed here! https://github.com/angr/cle/commit/6fee360b928a4f9b344c9f6d4bafae0ec1b8e712

The problem was that the relocation was performed twice, once to relocate the puts call to libc, and again to relocate it to the puts simprocedure. Since this relocation uses an addend, it depends on the original value in memory to calculate its final value. This gets changed during the first relocation, so the second relocation is wrong! The fix is to force the relocation calculations to read from the original binary data, not any modifications to it by CLE.
