### ISSUE TITLE
crash in cfg_base._analyze_function_features

### ISSUE THREAD

**Issue by quoscient** [angr/angr#167]
The line https://github.com/angr/angr/blob/c60388cddc93ec2c11a28bd0ff95b4cd5ba979f2/angr/analyses/cfg_base.py#L607 crashes angr if `target_func` is None. This happens if the `target_addr` argument of `self.kb.functions.function(addr=target_addr)` is not found. 
The root cause seems to be that `target_addr = edges[0][1].addr` not necessarily returns the first address of a function.
I can fix this issue by searching for the member of edges which is of class angr.knowledge.function.Function. The question remains is whether there are other assumptions violated, e.g. is the iteration in:

```python
edges = [ edge for edge in func.transition_graph.edges(
            nbunch=[src], data=True
            ) if edge[2]['type'] != 'fake_return'
]
```

supposed to return the entrypoint of the function in the first element?

**Comment by zardus** [comment]
Fish is the cfg master, but my guess is that this is already fixed
internally, and will be pushed in a week or so. Let's check it again then!

**Comment by ltfish** [comment]
I'm not in a state sane enough to answer this question right now. I'll come around later.

**Comment by ltfish** [comment]
First I have to admit that the code I wrote was pretty bad. `edges` is a list of 3-tuples: `(source node, destination node, a dict of all labels associated with the edge)`. A `fake_ret` edge is an edge between call site and (the supposedly) return target. If there is a 'fake_ret` edge associated to the source basic block node, *and* the calling target is successfully resolved when doing CFG recovery, there should be at least one `call` edge associated with the source basic block node and each calling target (or multiple `call` edges if there are more than one calling target are resolved, which I don't think `CFGFast` is doing by default).

My guess is that the target address is not the beginning of a function. It's either because `CFGFast` failed to resolve the target before, or the resolution was right, but the target address simply does not exist. I don't know if my guess holds unless you find the root cause, or post a minimal test case that reproduces this issue.

> I can fix this issue by searching for the member of edges which is of class angr.knowledge.function.Function.

I believe every single node in `Function.transition_graph` and `Function.graph` must be a `CodeNode` (either a `BlockNode` or a `HookNode`, which are both subclasses of `CodeNode`). You won't be able to find `Function` instances in `transition_graph` or `graph`.

**Comment by quoscient** [comment]
This doesn't seem to be an issue anymore :)
