### ISSUE TITLE
Angr fail to find a path to a block

### ISSUE THREAD

**Issue by DongShuaike** [angr/angr#1695]
---

Hi, I'm working on a `MIPS` program which has a function called `ExecuteOneAccept`.
The following image shows the part of that function I'm trying to symbolic execute.
![executeoneaccept](https://user-images.githubusercontent.com/8875073/63071940-17051a80-bed6-11e9-8cad-0c9b2ebbaa05.jpg)

There are some variables defined in the function so I first initialized all symbolic variables I need in the execution as follow:
![functionheader](https://user-images.githubusercontent.com/8875073/63072690-fccd3b80-bed9-11e9-8e1d-f62c86820f9d.jpg)

```
start_state = proj.factory.blank_state(addr=0x403da8, remove_options={angr.sim_options.LAZY_SOLVES})

httpinfolen_addr = start_state.regs.fp+0xc40-0xc24

httpinfo_addr = start_state.regs.fp+0xc40-0xc18
for i in range(0x600):
    start_state.mem[httpinfo_addr+i].byte = start_state.solver.BVS('httpinfo', 8)

content_addr = start_state.regs.fp+0xc40-0x414

for i in range(0x600):
    start_state.mem[content_addr+i].byte = start_state.solver.BVS('content', 8)
```
I then create a simulation manager for `start_state`
```
sm = proj.factory.simulation_manager(start_state, save_unconstrained=True)
```
I then use `sm.step()` and `sm.active` to check its states
As the screenshot shows, at the last `sm.step()`, the engine has reached one of interesting address `0x403e10`, which can lead to two different branches.

Among them, if `"Content-Type"` string appears in the variable `Httpinfo`, then the program should go to `0x403e1c`, otherwise, go to `0x403ea0`
![simstate](https://user-images.githubusercontent.com/8875073/63072316-02c21d00-bed8-11e9-8e3b-9a739742a2f9.jpg)
![0x403e10 (1)](https://user-images.githubusercontent.com/8875073/63072409-8845cd00-bed8-11e9-9437-12c154ace670.jpg)

**Because I have defined `Httpinfo` as a symbolic variable, the engine should have calculated that constraint for me if I want to go to 0x403e1c(the bottom left block).**

However, when I `sm.step()` again, only the bottom right block can be reached.
![stepagain](https://user-images.githubusercontent.com/8875073/63072522-191ca880-bed9-11e9-9808-7080d6e98cca.jpg)

Note: To make sure the symbolic variables are correctly defined by me, I `eval` Httpinfo at the the second block's head (`0x403ddc`) when a constraint `"POST" should be in Httpinfo` is satisfied.
The result is shown as
![httpinfo_val](https://user-images.githubusercontent.com/8875073/63072593-7284d780-bed9-11e9-85db-9e128520f0ca.jpg)
(`act3` is created by `act3 = sm.active[1]`)

Thanks for your patience if you have gone through there, my question is:
1. why a block is directly "ignored" by the engine? It is not "unconstrained" because I set "save_unconstrained"
2. How can I reach that ignored block?

**Comment by rhelmot** [comment]
so! many things:

1) I really really appreciate how much work you put into formatting this issue, but the reason that this has taken so long to get back to you on is because this is in fact a _very_ bad format for describing issues. The easiest way to do this would be to upload the binary and your script and explain why you think it should work but isn't working.
2) Your initialization code isn't actually doing anything. Everything is based on `state.regs.fp`, but in a blank state that's uninitialized. (That shouldn't actually affect whether the script works though, since you're not adding constraints or saving references to the symbols you're storing, so angr can just work with the default unconstrained values generated by memory)
3) LAZY_SOLVES has been off by default for a very, very long time. Whatever tutorial or folk wisdom told you to turn it off is severely outdated.
4) The crux of whether or not you're going to be able to reach that block is whether or not strstr gives you the answer you're expecting. strstr is notoriously difficult to do correctly symbolically. Our implementation has several safety caps on it (some implicit in our implementations of strlen and strcmp) which prevent it from causing a symbolic complexity blowup. You may need to raise some of those caps.

In order to proceed, you should add debug breakpoints to `strstr.py` and step through to make sure that a) the inputs are what you're expecting and can take on the values you're expecting (e.g. checking `state.satisfiable(extra_constraints=(some_symbol==some_value_i_expect,))`) and that b) execution proceeds the way you're expecting. If it's coming up with "nope there's no way we can find this needle in this haystack :(" you will need to raise the safety limits. These are:

- `state.libc.max_symbolic_strstr`
- `state.libc.buf_symbolic_bytes`
- `state.libc.max_str_len`

**Comment by DongShuaike** [comment]
Thank you @rhelmot  for your helpful response, but I have something unclear about your answer.
1. Upon my opinion, although the value of `fp` is uninitialized, `fp` should be consistent (be the same) during one symbolic execution (regardless what value the engine assigns it, it should be unchanged during this execution), so that it won't influence the location of stack variables. Is this right? If not, which `factory.xxx_state` should I use to symbolic execute a function?
2. What do you mean by `safety caps`, can I just regard it as some thresholds to prevent the possible endless execution or path explosion? Can I solve the issue by `hook` the `strstr` invocations with angr's `SIM_PROCEDURES['libc']['strstr']`?
3. I admire your suggestions in the last paragraph but I have no experience in debugging `strstr.py`. (My dumb question) Is there any official tutorial on angr debugging?
I really appreciate your patience in helping me and I will soon upload the binary and script for your reference.

**Comment by rhelmot** [comment]
1. The first thing the state you're executing does is overwrite the frame pointer. I have no advice on how to do this correctly. There is `call_state` but it won't set up stack frames for you.
2. They are numerical limits on how much complexity is generated by simprocedures. The problem they prevent is not path explosion but on the size and complexity of ASTs, kind of like if you merged some exploded paths. You cannot resolve this problem by hooking with a simprocedure because it is already hooked by a simprocedure.
3. There is no official tutorial on angr debugging. it's just ordinary python debugging.

please upload the binary

**Comment by DongShuaike** [comment]
Hi @rhelmot , this is the binary I used. I have shared it on my google drive.
https://drive.google.com/file/d/1bznHcvEtUgnxmVJCu_UTTswFtTqZ6LZo/view?usp=sharing
Thank you very much for the help.

**Comment by rhelmot** [comment]
You may solve your issue by setting `start_state.libc.max_symboilc_strstr = 16`. It is very small by default, preventing strstr from finding any solutions where the needle is found too far from the start of the haystack - and it must, in order to be compatible with the previous strstr checking for the presence of "POST".
