### ISSUE TITLE
Solution not found

### ISSUE THREAD

**Issue by justanotheranonymoususer** [angr/angr#1726]
I participated in a CTF, and I had a case where angr would be very useful. But I'm using it for the first time, so I'm not sure I did it correctly. On the other hand, the script is very simple.

I based my code on this sample:
https://gist.github.com/inaz2/c812671841f97804c24ba6650b1b2500

I didn't find any solutions. Then I changed the constants so that I know the solution. Still, solution not found.

Code and binary are attached. I'm using Ubuntu. I expected the sting "12345678qwertyui" to be found - if you run "./a.out 12345678qwertyui", you get to the "find" instruction that I defined.

Please help me understand why it doesn't work. Thanks.

[test_simple.zip](https://github.com/angr/angr/files/3615102/test_simple.zip)

**Comment by rhelmot** [comment]
The problem is that your constraints are too difficult for z3! When I run it, angr stalls for exactly 5 minutes on the last step, then finishes saying the winning branch is unsatisfiable. This is running into the built in solver timeout of five minutes. You can increase this, but generally z3 is bad at breaking hash functions like this.

**Comment by justanotheranonymoususer** [comment]
Thank you for the reply. First of all, I think that a proper error should be displayed in this case, otherwise it's confusing, especially for a first time user like me.

Also, can you tell me how to increase the timeout? I didn't find an angr option for it.

And do you think there are better tools for this task?

Thanks.

**Comment by rhelmot** [comment]
This has been a long standing issue: https://github.com/angr/claripy/issues/41

The timeout can be increased with `state.solver._solver.timeout = time_in_milliseconds`. It's not very well documented because the five minute timeout is so long that if you run it over it's most likely that z3 will only be able to find the solution through brute force search.

I do not believe that your sample is well-suited for automated solving. At least, I don't know of any tools which could solve this automatically.

**Comment by justanotheranonymoususer** [comment]
Thanks
