### ISSUE TITLE
Generating chains of ROP gadgets from a CFGFast

### ISSUE THREAD

**Issue by ntauth** [angr/angr#1745]
I've started fiddling with angr just recently so I've yet to understand fully how it works. For a project, I'm trying to generate the static CFG of a binary and generate a list of ROP gadget chains, which are basically going to be chains of CFGNode's of length at most 3 and no less than 2.

One of the first problems is handling indirect branches, which I believe is partly fixed by indirect branch resolution. The main issue though is SimProcedures: while trying to create the chains, I'll need to record the starting address of each gadget, but having a SimProcedure in between makes it hard to track down the actual hooked function address as well as get the associated capstone block with the disassembled instructions of the node.

This is an explanatory image of the issue: [Plotted CFG](https://imgur.com/a/47yGZfg)
As you can see **__libc_start_main** and **puts** are marked as **SIMP**, so the *addr* attribute of the node doesn't yield the actual address.

What I would like to do with a CFG is:

1. Traverse the entire graph using a Breadth-first Search, which I'm already doing
2. For each node *g1*:

- If it's a direct branch (only one successor node *g2*), chain *g1* and *g2* in a list [*g1*, *g2*]
- Otherwise proceed with traversal

At the end of this, I'll have produced a list of gadget chains that contains:

1. Chains of length 3 (3 chained gadgets/nodes) (only if there's a direct branch between each)
2. Chains of length 2 (2 chained gadgets/nodes)

Ultimately, for each chain, I'll record the address of each branch instruction and store their disassemblies elsewhere. But this is impossible to do when there's a SimProcedure in between.

Is there any way to disable them? I've tried with *use_sim_procedures = False* when loading the project, but it still shows the **puts** SIMP when generating the CFGFast.

**Comment by rhelmot** [comment]
What do you mean by "actual address"? There is no actual address. You've loaded the project with auto_load_libs=False, so in order to satisfy the dynamic linking dependencies of the binary, angr creates a fake region to house all the imports, as the control flow needs to point _somewhere_. There's no other way to give a correct answer. If you did auto_load_libs=True and use_sim_procedures=False, then you would analyze the control flow of the real function in libc, but that's certainly not what you want.

What kind of graph are you expecting?
