### ISSUE TITLE
Behavioural difference between project.factory.block() and cfg.kb.functions[...].blocks

### ISSUE THREAD

**Issue by senyuuri** [angr/angr#1749]
---

**Describe the bug.**

Given a function's entry block at address 0x1234, running `project.factory.block(0x1234)` and `next(cfg.kb.functions[0x1234].blocks)` can generate two blocks of different sizes. So far this behaviour has only been observed when the entry block contains a `call` instruction.

For example, assume there is a function at `0x652133` and we are interested in the first block at the entry address. Comparing the above-mentioned two methods:

1. Method 1: get the block through `cfg.kb`. Notice there is a `call` instruction at `0x65213e`
```
>>> cfg = project.analyses.CFGFast(normalize=True, collect_data_references=False, force_complete_scan=False)
>>> entry_func = cfg.kb.functions[0x652133]
>>> next(entry_func.blocks).pp()
0x652133:	push	ebp
0x652134:	mov	ebp, esp
0x652136:	push	ebx
0x652137:	push	esi
0x652138:	and	esp, 0xfffffff0
0x65213b:	sub	esp, 0x10
0x65213e:	call	0x652143
0x652143:	pop	ebx
0x652144:	add	ebx, 0x1f09ad
0x65214a:	mov	esi, dword ptr [ebp + 8]
0x65214d:	mov	eax, 0x16285994
0x652152:	jmp	0x652161
```

2. Method 2: directly get from project.factory.block(). Notice that instructions after `0x65213e` are trimmed. 
```
>>> blk = project.factory.block(0x652133)
>>> blk.pp()
0x652133:	push	ebp
0x652134:	mov	ebp, esp
0x652136:	push	ebx
0x652137:	push	esi
0x652138:	and	esp, 0xfffffff0
0x65213b:	sub	esp, 0x10
```

I am not sure what is the root cause of this strange behaviour. However, given the pervasive usage of `project.factory.block()` by the community I think people may need to be warned that they may only get a partial view of a block outside a function's CFG context.

**Comment by rhelmot** [comment]
So I don't understand why this is happening in the way shown in your example but this is expected behavior and is well documented. There are myriad reasons why the units of block used in the CFG are different than the most basic attempt at lifting a block. The most obvious example is that you've passed `normalize=True` to the CFG, which explicitly gives it permission to chop up blocks in ways different from how `project.factory.block()` does it.

The two things that don't make sense are:

1) I don't know why a block is including a call statement. This means that it's not a real basic block, which must always break at every control flow instruction, but rather a block from the function supergraph. Maybe fish just happened to implement supergraph parsing in cfg proper when I blinked.
2) I don't know why project.factory.block(...) gave you something that ended with a non-control-flow instruction. Did you miss the last line, the call instruction, when you copied the output?

There is a FAQ entry about different block sizes when working with CFGs, which is not exactly what you asked but very close to it: https://docs.angr.io/introductory-errata/faq#why-is-angrs-cfg-different-from-idas

**Comment by senyuuri** [comment]
Thanks for the quick reply. Yes, the FAQ do make sense and that should solve my doubt. 

For your second question, the output is copied as it is. `project.factory.block(...)` did not include the next immediate `call` instruction.  

The original function is attached below. FYI, the binary was obfuscated in an ollvm-like way through control flow flattening. Not sure if that will affect the lifting process.
```
>>> list(entry_func.blocks)
[<Block for 0x652133, 33 bytes>,
 <Block for 0x652161, 12 bytes>,
 <Block for 0x652154, 8 bytes>,
 <Block for 0x65216d, 7 bytes>,
 <Block for 0x65215c, 5 bytes>,
 <Block for 0x652174, 7 bytes>,
 <Block for 0x65217b, 2 bytes>]
>>>
>>> for b in entry_func.blocks:
...     b.pp()
...     print('\n')
...
0x652133:	push	ebp
0x652134:	mov	ebp, esp
0x652136:	push	ebx
0x652137:	push	esi
0x652138:	and	esp, 0xfffffff0
0x65213b:	sub	esp, 0x10
0x65213e:	call	0x652143
0x652143:	pop	ebx
0x652144:	add	ebx, 0x1f09ad
0x65214a:	mov	esi, dword ptr [ebp + 8]
0x65214d:	mov	eax, 0x16285994
0x652152:	jmp	0x652161

0x652161:	and	eax, 0x7fffffff
0x652166:	cmp	eax, 0x16285994
0x65216b:	je	0x652154

0x652154:	mov	dword ptr [esp], esi
0x652157:	call	0x40dfa0

0x65216d:	cmp	eax, 0x4de9da69
0x652172:	jne	0x65217b

0x65215c:	mov	eax, 0x4de9da69

0x652174:	lea	esp, [ebp - 8]
0x652177:	pop	esi
0x652178:	pop	ebx
0x652179:	pop	ebp
0x65217a:	ret

0x65217b:	jmp	0x65217b
```

**Comment by ltfish** [comment]
> For your second question, the output was copied as it is. project.factory.block(...) did not include the next immediate call instruction.

It seems weird to me. Can you please post your binary so I can debug and see what's going on?

**Comment by senyuuri** [comment]
Thank you Fish. However I have tried again and was not able to reproduce the same result. My best guess is that my previous code messed up some angr's internal objects and caused the issue (I ran `start_interactive_shell()` at the end of the code to inspect the result).

I will open a new issue if I managed to see this again.
