### ISSUE TITLE
How to get constraints from CFGEmulated object

### ISSUE THREAD

**Issue by ShadowLL** [angr/angr#1770]
I want to get constraints from CFGEmulated, but I don't know how to get them.

**Comment by behnamben** [comment]
i think you have to enable some of the state options that are related to track the constraints in your initial states and after that you just get your interested constraints like : node.input_state.solver.constraints.
take a look at the state options in api-doc.

**Comment by ShadowLL** [comment]
Your suggestion is useful, thank you very much

**Comment by ltfish** [comment]
You can start from `state.solver.constraints`. However, please note that due to how state merging works (or the lack of state merging) in `CFGEmulated`, you will lose constraints when multiple paths converge. You will need to manually handle such cases before we implement better path/state merging in `CFGEmulated`.

**Comment by ShadowLL** [comment]
These problems do exist. State.solver.constraints is often a list of <Bool True> or <Bool False >.
