### ISSUE TITLE
Issue with SimUnicorn

### ISSUE THREAD

**Issue by abarbaro** [angr/angr#181]
Hi all,
I have update angr and now when I try to solve an example exercise I have the following error:

examples/strcpy_find$ python solve.py 
Traceback (most recent call last):
  File "solve.py", line 11, in <module>
    import angr
  File "/usr/local/lib/python2.7/dist-packages/angr/__init__.py", line 7, in <module>
    from .project import *
  File "/usr/local/lib/python2.7/dist-packages/angr/project.py", line 442, in <module>
    from .factory import AngrObjectFactory
  File "/usr/local/lib/python2.7/dist-packages/angr/factory.py", line 1, in <module>
    from simuvex import SimIRSB, SimProcedures, SimUnicorn, SimState, BP_BEFORE, BP_AFTER, SimUnicornError
ImportError: cannot import name SimUnicorn

I have installed angr following this page: http://docs.angr.io/INSTALL.html

Am I missing something?

Thanks

**Comment by rhelmot** [comment]
Looks like you have a really nasty version desync issue between angr and simuvex.

- Did you install from pip or from github?
- Can you post the output of `python -c "print __import__('simuvex')"

**Comment by rhelmot** [comment]
Additionally:
- what operating system are you using?

**Comment by abarbaro** [comment]
Hi,
I'm using Linux and I have installed angr using github. The output of the command is:

<module 'simuvex' from '/usr/local/lib/python2.7/dist-packages/simuvex-4.6.6.28-py2.7.egg/simuvex/__init__.pyc'>

Thanks

**Comment by abarbaro** [comment]
I have installed again simuvex and claripy and now I have the following error:

.....
 File "/usr/local/lib/python2.7/dist-packages/claripy/backends/backend_z3.py", line 333, in _abstract_internal
    raise ClaripyError("unknown decl kind %d" % decl_num)
claripy.errors.ClaripyError: unknown decl kind 2352
Segmentation fault (core dumped)

Thanks

**Comment by rhelmot** [comment]
Looks like a really nasty z3 version mismatch.

Try `sudo pip install -I angr-only-z3-custom`

**Comment by abarbaro** [comment]
Hi,
I have uninstalled all and reinstalled all from github. I tried also your last command but nothing.

I still have the same issue.

Thanks

**Comment by rhelmot** [comment]
Which issue are you facing, the most recent one you posted with the segmentation fault?

**Comment by abarbaro** [comment]
Yes, sorry I was unclear.

**Comment by rhelmot** [comment]
Can you post the output of the following: `python -c 'import claripy; import z3; print z3.z3core.lib()'`

**Comment by abarbaro** [comment]
Hi,
this is the output: <CDLL '/usr/lib/libz3.so', handle 2a466a0 at 7ff12a8b9490>

Thanks

**Comment by rhelmot** [comment]
So basically I have absolutely no idea what's going on, and I don't have any way to remotely debug your problem for you. This is because you've installed angr globally, as root. This is not the way we recommend people to install angr (the recommended alternative is in a virtualenv).

So, here are my suggestions:

- If you have any version of z3 installed from your OS's package manager or any source besides angr-only-z3-custom, uninstall it and make sure its files are purged from your filesystem
- If that doesn't work, reinstall angr in a virtualenv.

And some tips for interacting with open source projects in general:

- When someone asks what operating system you're using, they generally want an answer more detailed than "linux", for example, "ubuntu 14.04"
- When you post output from a terminal on github, surround it by \`single backticks\` (`single backticks`) for inline snippits or:

\`\`\`
triple backticks for longer passages
\`\`\`

```
triple backticks for longer passages
```

Let me know if you need any more help!

**Comment by abarbaro** [comment]
Hi,
thanks for all your suggestions. I'll use the virtualenv on the VM as you suggested.

Thanks

**Comment by abarbaro** [comment]
All solved using virtualenv.

Thanks
