### ISSUE TITLE
CFGFast: infinite loop

### ISSUE THREAD

**Issue by quoscient** [angr/angr#184]
I figured that, at least for PE files, CFGFast might get stuck in an infinite loop.
The code causing the trouble starts here:
https://github.com/angr/angr/blob/2f718925e2f6e3cd109075f4d798ca5130092681/angr/analyses/cfg_fast.py#L613

Since the `get_max_addr()` of the PE module already takes relocation into account, `self._end` is far beyond the mapped memory.

Later in the analyses process `_next_code_address` calls `_next_unscanned_addr`, which in turn returns `self._end`, which is behind any mapped memory.
The infinite loop starts at: 
https://github.com/angr/angr/blob/2f718925e2f6e3cd109075f4d798ca5130092681/angr/analyses/cfg_fast.py#L786
because 
```python
 while next_addr in self._initial_state.memory:
```
will never be true, the conditional check
```python
if len(sz) > 0 and is_sz:
```
is always false (since sz is still empty), and https://github.com/angr/angr/blob/2f718925e2f6e3cd109075f4d798ca5130092681/angr/analyses/cfg_fast.py#L819 causes the loop to repeat with an address even further out of the mapped image.

Is this a problem of the PE module or is the initial calculation of `self._end` wrong?

**Comment by ltfish** [comment]
> Since the  get_max_addr()  of the PE module already takes relocation into account,  self._end  is far beyond the mapped memory.

`get_max_addr()` should not account for relocation. @rhelmot

**Comment by rhelmot** [comment]
`get_max_addr()` *should* account for relocation. The decision was made at some point that all backend functions should work with rebased addresses, since this is a far more common use-case.

The one place I can think of off the top of my head that provides un-rebased addresses is symbols and relocations, which provide a `addr` and a `rebased_addr`. I'm not wedded to this scheme though, we could absolutely refactor that into `addr` and `unrebased_addr` or something.

**Comment by ltfish** [comment]
Ah so it's a defect in CFGFast code. I think it is not updated when we made that decision that `get_max_addr()` should account for relocation.

**Comment by ltfish** [comment]
Commit 040cd86 should fix this issue. Thanks.

**Comment by quoscient** [comment]
Cool, thanks
