### ISSUE TITLE
Finding syscall numbers without running a program

### ISSUE THREAD

**Issue by rxe101** [angr/angr#1852]
---

Hi, thanks to angr team for sharing this wonderful project with community.

What I am trying to do is to find all system calls from the main program and related libraries along with the system call number (which is one of parameters). 
Given I'm a novice to the angr tool, any detailed guideline to achieve this goal would be appreciated. Note I intend to run this code on various sizes of elf binaries with the static only way without running them.

I noticed that "Extending the Environment Model"/SimProcedure section mentions syscall issues, but wonder whether this really applies to my problem (if I cannot run programs).

If it is already responded answer due to my limited knowledge on the posts, please just let me know the referred page.

Thanks in advance.

p.s., this is a question. I wish I have labeled this as a question.

**Comment by rhelmot** [comment]
- build a control flow graph with the CFG analysis
- some of the nodes of the graph will be syscalls. each one will have an attribute indicating whether it is a syscall and if so what number it is

**Comment by rxe101** [comment]
So far I tried CFGFast (with all libraries loaded). In my test program written in C code, there are a couple of lines calling system calls like following.

`rc = chmod("./passwd", 0444);  // which is a libc call just for a reference.`

` rc = syscall(SYS_chmod, "./passwd", 0444); // syscall that I'm interested in`

The nodes of this code shows function calls to "chmod" and "syscall" functions respectively. They both have is_plt=True, is_syscall=False.

The second case is what I'm interested. Prior to the call I see there are instructions for parameters. But I don't see any info on the syscall number (SYS_chmod) either in the function node or a symbol node.

I wonder what could be the next steps. Thanks.

**Comment by ltfish** [comment]
The problem here is much harder. This is because the `syscall()` you are dealing with is in fact a libc function. It is not strictly a `syscall` (as in, a `syscall` instruction). angr's CFGFast does limited localized data-flow analysis to determine the syscall number when facing a `syscall` instruction. It does not do so for syscall wrappers.

There can be multiple solutions:

- Use `CFGEmulated` to emulate all functions that are calling the libc function `syscall` with `call_depth=1` and examine the first argument of each call to extract syscall numbers.
- Implement a simple data-flow analysis to get the first argument of each call to `syscall` and extract syscall numbers. `ReachingDefinitionAnalysis` should get you those arguments directly.
- (Not recommended) Symbolically explore each function that calls the libc function `syscall` and extract the first argument when the function is called. I do not recommend this route since it is probably a giant overkill to your problem. But if your program involves dynamically constructing syscall numbers on different paths, this might be your best bet.

**Comment by rxe101** [comment]
Thank you for wonderful comments. 
Let me get familiar with angr, try what you suggested, and then come back.

**Comment by mauricesvp** [comment]
@ltfish So what if I wanted to identify all `syscall` instructions? Wouldnt I have to do some sort of backtracking in order to determine where the rax register might have been set (which could happen from multiple places)?

**Comment by ltfish** [comment]
> So what if I wanted to identify all syscall instructions?

Build a CFG, find all CFGNodes (or blocks) with `Ijk_Syscall` or `Ijk_Sys??` jumpkinds. Those blocks end with a syscall instruction (or the equivalence).

> Wouldnt I have to do some sort of backtracking in order to determine where the rax register might have been set (which could happen from multiple places)?

CFG will try to determine the syscall number if `rax` is assigned with a concrete value within the same basic block of the `syscall` instruction. Otherwise yes, you'll have to do some data flow analysis to find all definitions of `rax` at the point when `syscall` is executed.

**Comment by IyotakeTatanka** [comment]
I am trying to find the system calls from this binary. As you can see, the system call command is made directly and not via the libc.
```
int main(void) {
    register int    syscall_no  asm("rax") = 1;
    register int    arg1        asm("rdi") = 1;
    register char*  arg2        asm("rsi") = "hello, world!\n";
    register int    arg3        asm("rdx") = 14;
    asm("syscall");

    if(1){
        register int    syscall_no  asm("rax") = 1;
        register int    arg1        asm("rdi") = 1;
        register char*  arg2        asm("rsi") = "hello\n";
        register int    arg3        asm("rdx") = 6;
        asm("syscall");
    }
  return 0;
}
```
As suggested, I create a CFG and check the nodes for their is_syscall property.
```
import angr

p = angr.Project('helloWorldAssembly', auto_load_libs=False)

CFG = p.analyses.CFGFast()

for node in CFG.nodes():
    if(node.is_syscall == True):
        print(node.name, " with syscall: ", node.is_syscall)
```
However there is only one write system call. In addition, angr only finds the system calls with the CFGFast - no system calls are found with the CFGEmulated.
To my question: how do I find the two write system calls?

Thanks in advance.

**Comment by rhelmot** [comment]
You have to do some data flow analysis, as fish described in the previous post. angr does not have a good mechanism to solve this problem outright for you.

To be honest, this is enough of a contrived and removed-from-reality problem that we get asked so often that I genuinely wonder whether "find all syscalls used by this binary" is an assignment in some course somewhere.
