### ISSUE TITLE
Why project.hook has side-effect on project.factory.block

### ISSUE THREAD

**Issue by 4B5F5F4B** [angr/angr#1872]
---
Hello all,

Consider the fllowing thumb instructions:

```
.text:00000710 20 46             MOV             R0, R4  ; size
.text:00000712 FF F7 08 EF       BLX             malloc
```

I create a block object by calling project.factory.block like this no exception will occurr.

```
block = project.factory.block(0x400711, 6)
assert(block.vex.jumpkind == "Ijk_Call")         //no exception occurrs
```

But if I call project.hook first like this, AssertionError will be arised.

```
def dummmy():
      return

project.hook(0x400713, se_call_ins, 4)
block = project.factory.block(0x400711, 6)
assert(block.vex.jumpkind == "Ijk_Call")         //AssertionError occurrs
``` 

I don't understand why block.vex.jumpkind is Ijk_Boring instead of Ijk_Call if I hook the blx instruction?

**Comment by rhelmot** [comment]
Hi! This is a feature, not a bug. When you hook part of the program, you are changing its behavior, effectively adding a new step to the process of executing it at the given point. To this end, basic blocks will be stopped early if they would otherwise skip over a hook, since hooks and basic blocks have to be processed in [discrete steps](https://docs.angr.io/core-concepts/simulation).

In your case, since you don't want to affect the control flow of the program, you should hook directly at the address of malloc instead of inside its PLT stub. You can do this with `project.loader.hook_symbol(name, procedure)`.
