### ISSUE TITLE
question: CFG with function pointers

### ISSUE THREAD

**Issue by rxe101** [angr/angr#1907]
Hello,

I have a sample code of a function pointer here. 
May I ask how to get main->func1, main->func2 function calls in CFG? 
I read some older article about CFGAccurate which I believe is obsolete now. 
If there is already a past discussion or related code example, please just let me know.
Thank you in advance.

```
void fun1(int a)
{
        printf("Value of a is %d\n", a);
}

void fun2(int a)
{
        printf("Value of a is %d\n", a);
}

int main()
{
        void (*fun_ptr)(int) = &fun1;
        (*fun_ptr)(10);

        fun_ptr = &fun2;
        (*fun_ptr)(20);
        return 0;
}
```

**Comment by ltfish** [comment]
Three approaches with various caveats:

- `CFGEmulated` (which was renamed from `CFGAccurate`) should be able to find those two targets just fine. It works well on small- to medium-sized targets, but ultimately it does not scale.

- `CFGFast` (the default CFG flavor) with a custom indirect jump resolver. You need to write an indirect jump resolver that is able to track _local_ data flows and figure out what the callees are. It should be easy to support simple cases like this one (pointer assignments are within the same function, no crazy loops, etc.) and should scale well (since it's mostly a local analysis), but it will have problem supporting complex examples (e.g., virtual function tables).

- `CFGFast` with a data flow analysis built atop. You'll need to develop your own data flow analysis to track pointers and calling targets. angr provides some building blocks for writing your own data flow analysis, and there are some readily available data flow analyses in angr that you can reference as well. However, depending on how much expertise you have, it may not be easy to implement.

All in all, this is still pretty much an open problem in the field. While there have been some cool solutions recently (e.g., [1]), it still far away from getting solved. You should pick the solution based on what your targets are, instead of developing an approach that works for all, unless you are conducting research on this specific problem.

[1] Where Does It Go?: Refining Indirect-Call Targets with Multi-Layer Type Analysis, https://dl.acm.org/doi/10.1145/3319535.3354244

**Comment by rxe101** [comment]
Thanks for your prompt response!
Let me close this and may come back with more specific questions :-)
