### ISSUE TITLE
Angr and vulnerability discovery

### ISSUE THREAD

**Issue by ljun85** [angr/angr#191]
I learned angr for some days. I read the paper **Offensive Techniques in Binary Analysis**,  installed the angr on my compute, and now , i finished the  [Angr Documentation ](http://docs.angr.io/docs/analyses/cfg_accurate.html). Then, althought i know the struct of angr, and i know the nature of angr is dynamic symoblic excution, but i don't know how to discover vulnerability through angr which is cool as said in  the paper **Offensive Techniques in Binary Analysis**. Is there anything somebody could help me? I think i need some easy case to learn how to use angr to discover vulnerability . Thanks very much.

**Comment by ltfish** [comment]
> the nature of angr is dynamic symbolic execution

ouch... It hurts so much for people working on static analysis support in angr...

Learning angr doesn't naturally tell you _how_ to find vulnerabilities. angr is a tool that assists you to analyze and understand programs, not a guide in vulnerability discovery, or a guarantee or an insurance that says "vulnerabilities must be found if you use angr". It is still up to you to learn _what_ you should do in order to find bugs in real software. And, you'll soon find out, that finding software vulnerabilities is a hard job (for the majority of people). I doubt there is any bug hunting 101 that holds your hand and show you how angr can be used in bug hunting - it's a cool idea, and we might consider that in the far future, but no one has done that up to now.

Personally I have no idea how bug hunting works. I would recommend a book, _The Bug Hunter's Diary_, as a beginner's guide to bug hunting. It's a nice book to read, and it shows many details in how a human finds bugs in real software, and what tools are useful at what time. angr is not mentioned, but you can use some approaches from the book on angr as well.

In the end, please properly case your title. All uppercase looks pretty offensive, as offensive as angr ;)

**Comment by ljun85** [comment]
First, thanks for you comments very much. I apologize for the case of my title, and i have no intention of offending. In fact, i just carelessly copy the title from the paper. I'm sorry .

**Comment by ltfish** [comment]
> I'm sorry.

It's OK. I didn't know that you just copied the paper title :-)

**Comment by ljun85** [comment]
Thanks at all.

在 2016-08-22 11:31:21，Fish <notifications@github.com> 写道：


I'm sorry.

It's OK. I didn't know that you just copied the paper title :-)
