### ISSUE TITLE
CFGAccurate's use_sim_procedures causes early termination

### ISSUE THREAD

**Issue by marcusp46** [angr/angr#203]
Greetings,

Can someone offer an explanation why CFGAccurate fails to run with use_sim_procedures=False?  If I flip it to True, it runs normally.  Please see the following code snippets.  Thanks.

works:
angr.Project("/usr/sbin/apache2",load_options={'auto_load_libs':False},use_sim_procedures=True)
doesn't work:
angr.Project("/usr/sbin/apache2",load_options={'auto_load_libs':False},use_sim_procedures=False)

**Comment by rhelmot** [comment]
When you say auto_load_libs=False and use_sim_procedures=False, you've
removed every mechanism angr has available for resolving library
functions-- in this configuration, every time your program calls a library
function, angr will see it as a jump to address 0. Since most programs have
an entry point that calls libc_start_main, which calls main, angr will only
ever see a program that sets up some function arguments and jumps to null.

**Comment by marcusp46** [comment]
Thank you for the timely response.  My goal is to produce a CFG with placeholders at library callsites.  Perhaps the best way is to set use_sim_procedures=True, but delete all SimProcedures in the respective directory?  In other words, I want a "pruned" CFG.

**Comment by ltfish** [comment]
`CFGFast` should do what you want.

**Comment by marcusp46** [comment]
Do you think the indirect branch resolving will be useless without the loaded libraries or sim procedures?  I'm hoping for the best CFG considering my constraints.

**Comment by marcusp46** [comment]
...and subsequently, I am going to linked the callsites of individually analyzed symbols for a whole-program CFG

**Comment by ltfish** [comment]
> Do you think the indirect branch resolving will be useless without the loaded libraries or sim procedures? I'm hoping for the best CFG considering my constraints.

I think they are still useful, at least for jump table resolution.

> ...and subsequently, I am going to link the callsites of individually analyzed symbols for a whole-program CFG

You can do that.
