### ISSUE TITLE
Number of arguments is always 0

### ISSUE THREAD

**Issue by jiahao42** [angr/angr#2032]
---

Hi all, 

I am using version 8.20.1.7, and I find the `num_arguments` property of functions are always 0. If I understand correctly, this property is to show the number of arguments of a function, isn't it?

Below is my code to test:

```Python
p = angr.Project(binary)
cfg = p.analyses.CFG()
for addr, func in cfg.kb.functions().items():
    if func.num_arguments != 0:
        print(func.name, 'Not zero!', func.num_arguments)   # This line never executed
```

Any help is appreciated, thanks!

**Comment by ltfish** [comment]
Sorry. `Function.num_arguments`, together with `Function._argument_registers` and `Function._add_argument_register()`, should have been deprecated ever since we have `CallingConventionAnalysis`. They were implemented back in 2016 where angr did not have the notion of calling conventions (`SimCC` and `CallingConventionAnalysis`). As of now, `Function.num_arguments` are only set after `CFGEmulated` is executed on that function.

I will get rid of `num_arguments`, `_argument_registers`, and `_add_argument_register()` soon.

You may access `Function.calling_convention` to get the calling convention of a function, the number of its arguments, and which registers are used to pass arguments. Please use `CompleteCallingConvention` to run a full calling convention analysis on your target binary, or use `CallingConventionAnalysis` to run a controlled calling convention analysis on a single function, before accessing `Function.calling_convention`. The following code snippet will probably work:

```python
p = angr.Project(binary, auto_load_libs=False)  # setting auto_load_libs to False so we don't recover CFG for libraries
cfg = p.analyses.CFG()
proj.analyses.CompleteCallingConventions(recover_variables=True)  # allow the recovery of variables
for angr, func in cfg.kb.functions.items():
    print(repr(func), func.calling_convention.cc, func.calling_convention.args)
```

**Comment by ltfish** [comment]
Oh also, calling convention analysis (and variable recovery) is in active development in angr. You definitely want to switch to a development install of angr and use the latest master branch.

**Comment by jiahao42** [comment]
That is very helpful, Thank you so much!

**Comment by muazek** [comment]
hey, did this work? i keep getting an error 'SimCCSystemVAMD64' object has no attribute 'cc' that is traced back to func.calling_convention.cc

**Comment by rhelmot** [comment]
This advice is a little outdated - we did a refactor to clean some of this stuff up (see https://docs.angr.io/appendix/migration (if this link breaks in the future it's the 9.1 migration guide)) so now you want `func.calling_convention` and `func.prototype`.
