### ISSUE TITLE
About Global Data

### ISSUE THREAD

**Issue by brokendragon** [angr/angr#209]
hi,
 I try to find a path from a funtion to another function and I set  UCSE(simuvex.o.UNDER_CONSTRAINED_SYMEXEC). The conditions of this path including global variable and I only get a deadended path and no constraints. Is there any parameter I can use to let the global variable be symbolic ? Or is there something wrong with my python file?
below is the testes program:

```
int y;
void fun1(int d)
{   printf("fun1\n");}

void test()
{
    if(y>100)
    {       
        if(y<1000)
        {
            fun1(y);
        }   
    }   
}
```

here is the python file,`0x40054e`is the address of funtion `test`, `0x400536` is the address of funtion `fun1`

```
    entr_state=proj.factory.blank_state(addr=0x40054e)
    entr_state.options.add(simuvex.o.UNDER_CONSTRAINED_SYMEXEC)
    p=proj.factory.path(state=entr_state)
    pg=proj.factory.path_group(p)
    pg=pg.explore(find=0x400536,num_find=20)
```

below is the result:

```
<PathGroup with 1 deadended>
constraints : []
```

Thanks a lot!

**Comment by rhelmot** [comment]
Your variable `y` is stored in the `.bss` section of the program, which is initialized to all zeros (concrete) by default. We should really set the bss to symbolic data for the blank_state state, or at least have an option for it...

**Comment by ltfish** [comment]
The real problem here is, that `UNDER_CONSTRAINED_SYMEXEC` does not necessarily make `y` symbolic. You are supposed to detect what variables are accessed on yourself, overwrite them with unconstrained symbolic values, and then perform symbolic execution.

Also, although I implemented the support for under-constrained symbolic execution in angr, please note that it is not officially supported, may not work as what the paper described, and you should not use it as a reference implementation to the original approach mentioned in the paper. Just in case you are working on a serious research project, you should either ask original authors of that paper for their code, or make sure the implementation in angr matches your expectation.
