### ISSUE TITLE
angr RISC-V support?

### ISSUE THREAD

**Issue by aron245** [angr/angr#2194]
I am new to angr and was wondering if angr supports RISC-V. I didn't find anything mentioned in the documentation, so I assumed it was not supported. Is there any work being done to support RISC-V?

**Comment by ltfish** [comment]
angr does not support RISC-V. We also do not plan to implement a RISC-V lifter. However, we will be able to leverage RISC-V support in VEX or Ghidra PCODE if they are adding support to RISC-V in the near future.

**Comment by rhelmot** [comment]
Caveat! We have a contributed RISC-V lifter in the [angr-platforms](https://github.com/angr/angr-platforms/tree/master/angr_platforms/risc_v) repository. I don't know how well its architecture support is but you should be able to import angr_platforms.risc_v and risc_v elf files should load and disassemble.

**Comment by ltfish** [comment]
Amazing. @rhelmot is right. The lifter looks pretty simple!

**Comment by Ptomerty** [comment]
Hi, bump as I'm part of a group looking to conduct a research project on this. I did some poking around and it looks like RISC-V 32-bit support is fully implemented in angr-platforms. Going off of [this link,](https://docs.angr.io/introductory-errata/helpwanted#additional-architectures)

1. Why is RISC-V 32-bit not listed in archinfo?
2. Has any progress been done on RISC-V 64-bit? Would this go in angr-platforms instead?

Thanks!

**Comment by ltfish** [comment]
> Why is RISC-V 32-bit not listed in archinfo?

Because RISC-V is only provided inside `angr-platforms`, which mainly consists of community-contributed lifters and arches support. While angr's interfaces are fairly stable, currently we do not have the manpower to maintain most community-contributed content.

> Has any progress been done on RISC-V 64-bit? Would this go in angr-platforms instead?

Not that I am aware of. It should go in angr-platforms if anyone contributes RISC-V 64-bit support.

I wonder if Ghidra P-Code has RISC-V (32-bit and 64-bit) support. If so, it might be easier to use angr's P-Code backend for RISC-V support.

I hate to say this, but without active research projects that are related to RISC-V going on in our team, we do not anticipate official support for RISC-V any time soon.

**Comment by sollyucko** [comment]
Ghidra added support for RISC-V in version 9.2: https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Configurations/Public_Release/src/global/docs/ChangeHistory.html#L117-L128

**Comment by twizmwazin** [comment]
angr platforms has some support, and you may have luck with using the support pypcode has with the pcode engine. If you find shortcomings in either of those options, please file issues so they can improve.
