### ISSUE TITLE
Backward Slicing

### ISSUE THREAD

**Issue by emrahsariboz** [angr/angr#2209]
---

Hi! 
I have been trying to use a backward slicing feature of angr; however, I have a couple of questions to understand how it works. 

I checked out the example in the following [link](https://docs.angr.io/built-in-analyses/backward_slice). My very first question is, how do I apply backward slicing of the program. Let's say I have .py file where I want to build a backward slice for it. 

What is the first step I need to do? I realized that probably I will need to load the project which I tried; however, no luck. What is the proper way to load the .py file (not necessarily need to be .py if angr supports any other programming language)? Do I need to create binary version of the script or executable file of it before load? 

Thanks a lot in advance!

**Comment by rhelmot** [comment]
angr is a binary analysis framework, it only analyzes binary files. You will not have much luck using angr to analyze python code if you compile it to a binary. Perhaps sometime in the future we will support analyzing python bytecode the way we support analyzing java bytecode, but it is not currently on our roadmap.

**Comment by ltfish** [comment]
> Do I need to create binary version of the script or executable file of it before load

Due to the limitations of current binary analysis techniques, you are better off using angr to analyze "pure binary programs," i.e., compiler-generated binary executables that comprises machine code. Compiling Python code or any other interpreted languages to bytecode forms do not generate binary programs that angr could load or analyze.
