### ISSUE TITLE
Possible bug: AttributeError: 'TLSObj' object has no attribute 'user_thread_pointer'

### ISSUE THREAD

**Issue by frala19871987** [angr/angr#222]
Hi,
using the following code
```
import angr

p = angr.Project("./nginx") #nginx 32 bits
p.analyses.CFGFast(show_progressbar=True)
```

I have the following syntax error:

```
File "/usr/local/lib/python2.7/dist-packages/angr/project.py", line 166, in __init__
    self._simos.configure_project()
  File "/usr/local/lib/python2.7/dist-packages/angr/simos.py", line 548, in configure_project
    super(SimLinux, self).configure_project()
  File "/usr/local/lib/python2.7/dist-packages/angr/simos.py", line 327, in configure_project
    self.proj.loader.perform_irelative_relocs(irelative_resolver)
  File "/usr/local/lib/python2.7/dist-packages/cle/loader.py", line 799, in perform_irelative_relocs
    val = resolver_func(resolver)
  File "/usr/local/lib/python2.7/dist-packages/angr/simos.py", line 316, in irelative_resolver
    val = resolver()
  File "/usr/local/lib/python2.7/dist-packages/angr/surveyors/caller.py", line 50, in __call__
    self.perform_call(*args)
  File "/usr/local/lib/python2.7/dist-packages/angr/surveyors/caller.py", line 61, in perform_call
    toc=self._toc)
  File "/usr/local/lib/python2.7/dist-packages/angr/factory.py", line 285, in call_state
    return self._project._simos.state_call(addr, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/angr/simos.py", line 432, in state_call
    state = self.state_blank(addr=addr, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/angr/simos.py", line 627, in state_blank
    state.regs.gs = self.proj.loader.tls_object.user_thread_pointer >> 16
AttributeError: 'TLSObj' object has no attribute 'user_thread_pointer'
```

I would also mention that nginx was compiled on a 32 bit arch and i'm using a 64 bit bit arch for the analysis.

Thanks

**Comment by rhelmot** [comment]
This is a version desync error. Please make sure your CLE is up to date.

**Comment by ltfish** [comment]
Seems to be a problem in the loader itself. @rhelmot knows enough to deal with it.

**Comment by frala19871987** [comment]
Hi,
thanks for the quick response. I have updated CLE and the problem was solved. However I had this second error:
```
File "/usr/local/lib/python2.7/dist-packages/claripy/backends/backend_z3.py", line 333, in _abstract_internal
    raise ClaripyError("unknown decl kind %d" % decl_num)
claripy.errors.ClaripyError: unknown decl kind 2352
Segmentation fault (core dumped)
```

I think it is because you have just updated z3, so I'm updating it.

I was wondering, isn't possible to add a kind of check before the Angr project is created and verify that everything is sync?

Thanks

**Comment by ltfish** [comment]
> isn't possible to add a kind of check before the Angr project is created and verify that everything is sync?

I totally agree with it.

**Comment by ltfish** [comment]
> I think it is because you have just updated z3, so I'm updating it.

One thing that I just realized is, that we didn't properly constrain version number requirements in `setup.py` of each individual components. I suppose this is what is happening:

- You installed an old version of angr, along with old versions of all underlying libraries.
- You did a `pip install --update angr`. angr is updated to the latest version, but not other libraries, since we do not constrain version numbers in the `setup.py` of angr's.
- There comes a version-mismatch error.

@zardus is this the case?

**Comment by frala19871987** [comment]
I have updated what necessary and now all works.

Thanks

**Comment by zardus** [comment]
Constraining the version numbers sounds like a huge pain in the butt... It'd be the Right Thing to do, and would require extending releaser.sh to update the required version numbers at every release. There's no way I can think of to do this at runtime automatically, otherwise. I opened up https://github.com/angr/angr-dev/issues/4 to track that.

**Comment by hypersimple** [comment]
@frala19871987  How could you solve it? Update Claripy?

**Comment by zardus** [comment]
Yeah, everything needs to be kept up-to-date. However, we properly track version dependencies now, so this sort of stuff should not come up...
