### ISSUE TITLE
How to get return value of a function

### ISSUE THREAD

**Issue by CvvT** [angr/angr#2263]
---

Hi,

I'm new to angr. Thanks for providing such an amazing tool. I was trying to use angr to hook certain functions to get their arguments, as well as return values. My initial failed solution is the following:

```
class Hooker(angr.SimProcedure):
    def run(self, arg0, orig_func=None):
        self.call(orig_func, (arg0), "getReturn")
        
    def getReturn(self, arg0, orig_func=None):
        ret = self.state.regs.rax
        print(arg0, ret)
        return ret
        
proj.hook(func_A, Hooker(orig_func=func_A]))
```
However, unlike user hook, it would cause infinite recursion. One solution I can think of is to use user hook for every return instruction inside that function.

Any suggestions on how to achieve it?

Thanks!

**Comment by ltfish** [comment]
You will need to pass `Ijk_NoHook` to `self.successors.add_successor()` (see [here](https://github.com/angr/angr/blob/master/angr/sim_procedure.py#L442)) instead of `Ijk_Call`. You must modify the source code of `SimProcedure.call()` to make this work. Should be straightforward.

Alternatively, you can add a hook at at the beginning of the function, and add another hook at all the return sites of this function to dump return values. This might be the more robust way to do what you want.

**Comment by CvvT** [comment]
Thanks! I prefer the latter non-intrusive solution.

**Comment by ltfish** [comment]
Just want to point out that angr is open sourced, and one of the biggest motivation is to allow easy changes to the source code! Modifying angr's code is definitely not considered _intrusive_. The use case here looks pretty valid to me; we just did not think that anyone would use the hooks in this way.

**Comment by CvvT** [comment]
Got it. I was just a little concerned about the compatibility issue since angr is still under active development. The first solution sounds trivial. Maybe I could send a PR if I could make it work without any side effects.

**Comment by ltfish** [comment]
PRs are always welcome!
