### ISSUE TITLE
CFGAccurate Doesn't Find Function With Symbol

### ISSUE THREAD

**Issue by bannsec** [angr/angr#232]
CFGAccurate was unable to find a function in an application that had a symbol entry pointing to it. The normal CFGFast was able to find it. Looking through the code, it appears CFGAccurate isn't scanning for loaded symbols. Is that intentional? I'd think symbols should be in the CFGBase class or something.

**Comment by ltfish** [comment]
That is intentional. `CFGAccurate` does not scan symbols. You can, however, get all functions/symbols from `CFGFast`, and then ask `CFGAccurate` to start CFG recovery from those symbols.

It's worth noting that `CFGAccurate` is not more complete (and is usually less complete) than `CFGFast` (which is the default CFG recovery mechanism).
