### ISSUE TITLE
How angr can output the Symbolic Expression?

### ISSUE THREAD

**Issue by pfsun** [angr/angr#238]
Hey,

I wonder whether angr can ouput the symbolic expression of register or memory location in any point when application executing?

Thanks,
Sun

**Comment by rhelmot** [comment]
angr can absolutely do this - at any point in the execution, given a SimState, you can access memory or registers or files and any value you pull out (via state.memory.load() or state.regs.\*) will be a symbolic expression, if symbolic data influenced this value in the current execution.

**Comment by hypersimple** [comment]
Can it print which memory location it writes to (symbolic), together with the instruction address?

**Comment by ltfish** [comment]
This will require some sort of tracking. You can do that by creating a custom `simuvex.Breakpoint` via `SimInspector` with breakpoint type being `reg_write` and `mem_write`, register it onto your state, and track the instruction address in the callback function of your breakpoints.

**Comment by hypersimple** [comment]
So it means, for _ALL_ the states, I should register

state.inspect.b('mem_write', when=simuvex.BP_AFTER, action=debug_func)

right?

**Comment by zardus** [comment]
You'd add the inspect hook to the initial state (when you initially create the path group, it would be `path_group.one_active.state`), and it gets automatically propagated onwards.

However, I think the easiest way to do this, rather than making an inspect hook, is to analyze the actions logged by the path. You can access this, for any path, through `path.actions`. Of these, the actions with a `type` member of `mem` and `action` member of `write` represent memory writes, and you can get at the values by accessing the `data` member.

**Comment by hypersimple** [comment]
When I access `path.actions` or `sirsb.statements.actions` , how to find the corresponding instruction address or the PC value? 

When I use `sirsb.statements.actions`, only the statement index can be printed.

**Comment by zardus** [comment]
You should be able to access `action.ins_addr` to get the address of the instruction.

**Comment by P4nda0s** [comment]
Hey you can try ‘dbg_repr’
```python
    cond = state.regs.eax == 0x1A67B4A4
    state.add_constraints(cond) 
    print(cond.dbg_repr())
```
