### ISSUE TITLE
A wrong in exploration_techniques.tracer.py 

### ISSUE THREAD

**Issue by treebacker** [angr/angr#2390]
---

**Describe the bug.**

In tracer.py line 188
![image](https://user-images.githubusercontent.com/44844446/99493125-a6d32780-29a9-11eb-9369-0f5e0f8b55c7.png)

which results the "raise" always be executed
![image](https://user-images.githubusercontent.com/44844446/99492973-65db1300-29a9-11eb-8552-cec59bac2537.png)

the right  maybe?

![image](https://user-images.githubusercontent.com/44844446/99493169-b7839d80-29a9-11eb-892a-c9b694d09120.png)

**Environment Information.**

**To Reproduce.**

**Additional context.**

**Comment by rhelmot** [comment]
No, the code is correct. An else clause on a for loop runs when the loop exits without breaking. Your proposed change would make the error raise too quickly.

This error indicates that something is wrong with your trace - what it is intended to do is find via heuristics the index of the entry point in the provided trace. Does the address of the entry point exist in the trace you have provided to the tracer? If so, does it match the heuristics? (that it must be the same as the linked entry point if the binary is non-PIC, and that the page offset must be the same and that the previous instruction must be a jump from at least 0x10000 bytes (from another shared object) away? If the entry point is present but it does not match these heuristics, then we need better heuristics. Otherwise, you need to make sure the entry point is in your trace

**Comment by treebacker** [comment]
ok, i think i know!
Thanks for your response!



---Original---
