### ISSUE TITLE
Mark PC as a symbolic value; judge if an instruction is a "call" instruction

### ISSUE THREAD

**Issue by hypersimple** [angr/angr#241]
How to mark PC as a symbolic value?

For example, on ARM, if I do

```
state.regs.r15 = claripy.BVS("pc", 32)
```

It does not work.

Also, how to judge if an instruction is a "call" instruction in Angr ?

I use something like 

```
pg.active[i].state.inspect.b('call', when=simuvex.BP_AFTER, action=debug_func)

def debug_func(state):
    print 'Call name:', state.inspect.function_name
```

But it prints a lot of stuff there. Also, state.inspect.instruction often causes error when pg.step(num_inst=1).

**Comment by rhelmot** [comment]
Having a symbolic value for PC is a very strange case - a lot of the things you might expect to happen by having a symbolic PC don't actually work because VEX requires a concrete address to do its lifting, and uses that address instead of a read from the PC register in most places...

To track calls, after each step check if the jumpkind is `Ijk_Call`. If so, there has just been a call executed.
