### ISSUE TITLE
You are attempt to use unicorn engine support even though it or the simuvex compatibility la isn't installed

### ISSUE THREAD

**Issue by qkta** [angr/angr#243]
Im trying to run an example at `angr-doc/examples/tumctf2016_zwiebel`, but the bellow error occurred:

> ERROR   | 2016-10-12 16:40:47,159 | simuvex.plugins.unicorn | You are attempt to use unicorn engine support even though it or the simuvex compatibility la isn't installed

Installed module:

```
$ pip list
ana (0.2)
angr (5.6.10.7)
angr-only-z3-custom (4.4.1.post4)
archinfo (5.6.10.5)
bintrees (2.0.4)
cachetools (2.0.0)
capstone (3.0.4)
cffi (1.8.3)
claripy (5.6.10.5)
cle (5.6.10.5)
cooldict (1.2)
decorator (4.0.10)
dpkt-fix (1.7)
future (0.15.2)
futures (3.0.5)
idalink (0.11)
mulpyplexer (0.7)
networkx (1.11)
nose (1.3.7)
pefile (2016.3.28)
pip (8.1.2)
plumbum (1.6.2)
progressbar (2.3)
pycparser (2.14)
pyelftools (0.24)
pyvex (5.6.10.5)
rpyc (3.3.0)
setuptools (28.3.0)
simuvex (5.6.10.7)
unicorn (0.9)
wheel (0.30.0a0)](url)
```

**Comment by ltfish** [comment]
We are still trying to get Unicorn onto PyPI, see [this issue](https://github.com/angr/simuvex/issues/39). If you want to install Unicorn support now, you'll have to manually do it by downloading our Unicorn fork from [here](https://github.com/angr/unicorn), installing it as a Python package, and then either compile `simuvex_c` under `SimuVEX` or reinstall `SimuVEX` from PyPI.

**Comment by rhelmot** [comment]
Hi! Fish's information is a little outdated, because a lot of things have happened in the last 24 hours :) In order for unicorn support to be compiled into angr correctly, the following things need to happen:

- You need to have the absolute latest version of unicorn installed; the final fixes got merged to upstream last night. Either our fork or the upstream repo will work fine.
- You need to have the absolute latest version of simuvex installed; the correct API compatibility adjustments got pushed to pypi literally seconds ago
- You need to have installed simuvex *after* unicorn was installed. simuvex decides at install time whether it can build unicorn support.

Finally, as scary as that error is, things will still run correctly, just more slowly, without unicorn support. I just pushed a new version of simuvex that makes the error a lot less obnoxious.

**Comment by leithon** [comment]
Hi Andrew,
Following your step, I downloaded the latest version of unicorn and simuvex, and successfully installed unicore. However, it seems angr cannot work well if simuvex.option.unicorn is enabled. For the example of zwiebel, the solver enables the option (add_options=simuvex.o.unicorn), but it cannot work. I debugged the solver.py,    after pg.run(n=20), there is no active path, and only one errored path.

Without the simuvex.o.unicorn option, it works well. I think it is the impact of unicorn.

**Comment by rhelmot** [comment]
Can you please post the error in the errored path? You may access the error directly with `path.error` or retry it and have the error printed to the screen with `path.retry()`. You can also get a debug shell in the error with `path.debug()`.
