### ISSUE TITLE
Solver that finds values satisfying expression equivalence or not

### ISSUE THREAD

**Issue by hypersimple** [angr/angr#246]
Is there any way in Angr or Claripy to do the following:

Given two symbolic expressions, for example:

```
<BV32 r0_0_32 + r1_0_32 + 0x4>
<BV32 r0_1_32 + r1_1_32 + 0x4>
```

Find a tuple that satisfies both expressions?
Here it can be:

```
r0 = 0, r1 = 0
```

If it cannot, return False.

It should know that `r0_0_32` and `r0_1_32` are the same thing. (this can be done by rewriting AST, just replace all the value in the middle to 0)

**Comment by zardus** [comment]
I'm not sure what you mean by `satisfies both expressions` in this context... Your ASTs aren't booleans, they're just bitvector expressions.

Do you mean satisfying them being equal? In that case, you can, after rewriting the two ASTs to reference the same variables r0 and r1, simply add the constraint of them being equal (`path.state.add_constraints(ast1 == ast2)` in angr or `solver.add(ast1 == ast2)` if you're dealing with the Claripy solver directly) and check if the result is satisfiable (`path.state.se.satisfiable()` or `solver.satisfiable()`) and, if it is, try to get the values out (`path.state.se.eval` or `solver.eval`).

In general, if you're having to rewrite your ASTs, it might point to something else being suboptimal. For example, instead of having to do all this, you can set the same variable to two states:

```python
r0 = claripy.BVS('r0', 32)
r1 = claripy.BVS('r1', 32)
state1 = project.factory.blank_state()
state2 = project.factory.blank_state()
state1.regs.r0 = state2.regs.r0 = r0
state1.regs.r1 = state2.regs.r1 = r1
```

Then, when it addrs r0 and r1 and 4, the expression will already have the same variables in it. Not sure if this is your situation, but it might simplify things if it is.

**Comment by hypersimple** [comment]
Thanks for the quick reply.

If I set the symbolic value in this way, the register or mem expression will still be something like `r0_28_32` or `mem_3_2_16` after execution.

Are there ways to control this?

**Comment by zardus** [comment]
That's weird... Can you upload your script?

**Comment by hypersimple** [comment]
The script can be simple, just like 
https://lists.cs.ucsb.edu/pipermail/angr/2016-September/000195.html

Simply copy and paste all the content once, and run it.

The symbolic value would be `symbolic_4_32` at the second run.

If not duplicating, for large binaries (e.g., Linux kernel functions), the number in the middle (e.g., `4` of `symbolic_4_32` will also increase, and I do not know the exact reason.

Does it represent just different symbolic values (by increasing order), or mean something else?

**Comment by rhelmot** [comment]
the `4` is just an autoincrementing identifier. It exists only to make sure that names are all unique. If you really, truly need to disable this, you can pass `explicit_names=True` into the BVS constructor, I think? But generally, if you're ever working directly with variable *names*,  you're doing something wrong. Claripy ASTs are supposed to have what's called "object identity", which means that once you create an object, it's immutable, and that object should be the only way to refer to the entity you just created. So if you wanted to represent the above example, you wouldn't want to have two separate `r0 = state.se.BVS('r0') lines, you would have only one of those, and then you would reuse that one `r0` value for your whole program.

**Comment by hypersimple** [comment]
Is there any way in Angr to find if two symbolic expressions are equivalent (including if... else... conditions), rather than just find one solution?

For example,

    If a == 3, result is 4; else, result is 5.

Not equivalent to

  result is 4.

Z3 has an API called `prove`, how to use it in Angr (expression)?

**Comment by zardus** [comment]
We don't currently expose `prove` from Z3 (purely due to lack of a need so far, but we're not opposed to it). You can emulate `prove` with:

```
solver.add(expr1 != expr2)
print solver.satisfiable()
```

Where `solver` is `state.se` if you're on the simuvex level.
