### ISSUE TITLE
Failing with unsat result despite an existing solution

### ISSUE THREAD

**Issue by liona24** [angr/angr#2461]
---

recently I have been trying to solve the *nobranch7e4* challenge from the [HXP CTF 2020](https://2020.ctf.link/internal/challenge/5e577a0e-057f-406f-965b-5f8d559183f0/) using angr.

My success has been mixed: Even though there is no apparent state explosion I still cannot solve for the flag because for some reason I get an error: `Got an unsat result`

This is the script I am using (the binary is available at the link mentioned above):
```python
import angr
import claripy
import logging

logging.getLogger("angr.sim_manager").setLevel("DEBUG")
p = angr.Project("nobranch7e4", auto_load_libs=False)

flag_size = 64
flag_addr = p.loader.find_symbol("flag").rebased_addr

s = p.factory.entry_state(add_options=angr.options.unicorn)

flag = [ claripy.BVS("flag_%d" % i, 8) for i in range(flag_size) ]
for c in flag:
    s.solver.add(c < 0x7f)
    s.solver.add(c > 0x20)

flag = claripy.Concat(*flag)
s.memory.store(flag_addr, flag)

sm = p.factory.simulation_manager(s)
sm.run()

final_state = sm.deadended[0]
final_state.solver.add(final_state.regs.dil == 0)
result = final_state.solver.eval(flag, cast_to=bytes)
print("The flag is", result)
```

(The goal is to make the program exit with code 0 by patching the memory at `flag`)

I observed that I am able to solve if I give at least the first 53 characters as known input.
For some reasons the same procedure does not work if I assume the last `n` characters are known (it seems I cannot even solve for only the first character unknown).

I also tried hinting the flag format `hxp{...}` but that does not work either.

Adding/Removing the constraints (`0x20 < c < 0x7f`) does not seem to have an effect, too.

Any ideas?

**Comment by ltfish** [comment]
I solved this challenge during the CTF with angr :) the short answer is that angr (or SMT) is not able to give you an answer to the problem you are trying to solve within a reasonable amount of time. This is because this small binary implements multiplication on `GF(2^8)`.

Here is my solution (really dirty Python scripts - what do you expect me to do during a CTF lol) for your reference.

The angr script that I used to derive the coefficients for polynomials: 
[simplify.zip](https://github.com/angr/angr/files/5775415/simplify.zip)

The script that I used to solve the matrix multiplication on `GF(2 ^ 8)`: 
[solve.zip](https://github.com/angr/angr/files/5775420/solve.zip)

In order to run solve.py, you need to put it under the root directory of [this project](https://github.com/Glank/Galois). I think it's Python 2 only, so you also need Python 2 or PyPy 2.7.

Finally, there seems to be a bug in Matlab 2018 and 2019 that it could not properly do multiplication on `GF(2 ^ 8)` for whatever reason... I wasted hours on it during the CTF. I still don't know why Matlab did not give me the correct results though.

Flag: `hxp{un_r0ll1ng_r0ll1ng_r0ll1ng_g03s_th3_g4l015_f13ld_ar1thm3t1c}`

**Comment by ltfish** [comment]
Apparently the other public [solution](https://gist.github.com/5unKn0wn/39abff28f21f3d75ead33476e7e517e2) online also uses angr. Just FYI.

**Comment by liona24** [comment]
Thanks. So just that I do not get this wrong, you are telling that it is generally not possible to solve for problems on `GF(n)` using SMT solvers?

**Comment by ltfish** [comment]
> you are telling that it is generally not possible to solve for problems on GF(n) using SMT solvers?

That is correct. SMT solvers usually do not include any optimization rules for GF(n), so for any non-trivial equations over GF(n) SMT solvers will quickly resort to bitblasting.

**Comment by ltfish** [comment]
Oh, one last thing.

> For some reasons the same procedure does not work if I assume the last n characters are known (it seems I cannot even solve for only the first character unknown).

Strictly speaking, angr will still give you a result after spending a lot of time in solving. However, the default timeout setting in claripy is 300 seconds. You might be experiencing a solver timeout, which (inconveniently) manifests itself as an unsat result, too.

**Comment by liona24** [comment]
Very helpful, I did not know that, thank you. 
Also noting the timeout thing is surely something to remember in the future :+1: 

Guess we can close this now.
