### ISSUE TITLE
Hook is not executed when hooking two library functions

### ISSUE THREAD

**Issue by dtouch3d** [angr/angr#247]
In a simple binary, like

``` c
#include <stdlib.h>

int main(void)
{
    int* ptr = malloc(1024);
    free(ptr);
}
```

I hook the two library functions

``` python
#!/usr/bin/env python

import sys
import angr

p = angr.Project(sys.argv[1], load_options={'auto_load_libs': False})
s = p.factory.entry_state()

def malloc_print(state):
    print("Called malloc!")

def free_print(state):
    print("Called Free!")

p.hook_symbol('free', free_print)
p.hook_symbol('malloc', malloc_print)

pg = p.factory.path_group(s)
pg.explore()
```

But only "Called malloc" is printed. When I use my own SimProcedures both functions are called correctly. When I hook only 'free' for example, the free_print function is called as expected.

**Comment by rhelmot** [comment]
I am intensely busy and can't debug your code right now but my best guess right now is that your path is deadending immediately after malloc gets called because your hook is replacing angr's default malloc hook.

hook_symbol works by actually redoing the project's relocations, so by hooking malloc and free this way, you've pointed the program's GOT slots away from the normal malloc and free simprocedures and toward your stubs. What's more, your stubs don't specify anything to do for control flow, so execution will try to continue at the hook address, which is gonna be in a nonsense externs section.

If you want to hook library functions, I would either manually insert code into their simprocedures (`simuvex/procedures/libc__so__6/*`), or hook at the PLT stubs for those functions. The PLT stubs can be looked up with `p.loader.main_binary.plt`.
