### ISSUE TITLE
Unicorn version is out of date

### ISSUE THREAD

**Issue by twizmwazin** [angr/angr#2541]
**Describe the bug.**
angr currently uses an out of date release candidate of unicorn, version 1.0.2rc4. This version does not have published wheels for macOS, making the setup process more complicated. Upgrading to 1.0.2 stable should resolve this issue, it has macOS wheels.

**Environment Information.**
N/A

**To Reproduce.**
`pip install angr` or `./setup.sh -e angr` from angr-dev
The installation will either fail if build dependencies aren't met, or take longer than necessary if they are.

**Additional context.**
N/A

**Comment by rhelmot** [comment]
Upgrading to 1.0.2 stable seems to cause some sort of memory corruption bug whenever we use unicorn. My first guess as to what this could be about is that we could be accessing some internal unicorn data structures which have changed since the pinned release, but the only accesses like this I can find in sim_unicorn.cpp are a) read-only and b) unchanged since the pinned release. Not sure what's up.

**Comment by anthraxx** [comment]
@rhelmot I'm currently trying to finish the packaging and release angr as a native distro package. I'm currently hit by this issue as we are providing `unicorn 2.0.0`.
It turned out to be a show stopper now because of this bug here, as with python its not feasible to have another lower version of unicorn (python has no concept of multiple versions of the same module installed in site-packages).

Would it remotely be possible to somehow get a bit of focus on trying to figure out the issue with latest unicorn? That would unlock the last issue and allow us to release angr as a distro package.

Thanks a lot and cheers :cat:

**Comment by rhelmot** [comment]
I have a branch of angr that works with the latest (unreleased) unicorn! We will merge it as soon as unicorn does a 2.0.1 release of some sort!

**Comment by rhelmot** [comment]
ref https://github.com/unicorn-engine/unicorn/pull/1651

**Comment by dnivra** [comment]
Fixed in #3598
