### ISSUE TITLE
Difference between path.step(num_inst=1) and path.step()

### ISSUE THREAD

**Issue by hypersimple** [angr/angr#259]
When trying `path.step(num_inst=1)` and `path.step()` for the same program, I found the results (certain memory operation or register symbolic expressions at a given PC) can be different. Also, `path.step()` can take fewer paths than `path.step(num_inst=1)`.

I think `path.step()` is basic-block-stride, and `path.step(num_inst=1)` is instruction-stride.

Which one is more accurate? And Why this could be different?

**Comment by rhelmot** [comment]
The only thing that option ends up modifying is the lifting settings that get passed to PyVEX. It makes it stop IR translation after a single instruction instead of at basic block boundaries.

This means that when you're using `num_inst=1`, it'll take many steps to accomplish the same thing as a single normal step. The results should be identical if you step the two paths in sync (i.e. several num_inst steps for one normal step until they reach the same PC). However, the num_inst path will take more time to execute, obviously.

The only reason you'd want to use num_inst=1 over the default is if you explicitly wanted to get instruction to stop in the middle of a basic block for some reason.

If you're analyzing MIPS code, num_inst=1 will obviously mess things up, since VEX implements delay slots in a way that's incompatible with lifting one instruction at a time.

**Comment by rhelmot** [comment]
Another thing, you might see actions happening at different instructions with full-block steps, because libVEX performs optimization that can move actions across instruction boundaries. If you want to disable this you can pass `opt_level=0` into `.step()`.
