### ISSUE TITLE
Force the path to take both successors on condition branches

### ISSUE THREAD

**Issue by hypersimple** [angr/angr#260]
At some branches, due to the value in the comparison statement, only one path(successor) will be taken.

Is there any way to force the program to continue executing on both paths, regardless of the condition?

**Comment by zardus** [comment]
The closest out-of-the-box feature is `LAZY_SOLVES`. Unless a condition is concretely false, that option will cause the path to continue to be executed until an actual unsat error is encountered. It's already on by default.

One other way you can do this, currently, is to have an exploration technique in which you check the unsat stash (make sure the path group is created with save_unsat) and reinject them into the active stash. However, since the guard condition is added to the constraint set, it could make your state unsat. With an unsat state, there's no reasonable way to, for example, resolve symbolic writes, since all constraint solves fail. You'd have to remove the last constraint to maintain "satness". That's a bit of a hack, since the states won't be completely consistent afterwards.

An alternate way to do this would be to set up a SimInspect hook in the code that deals with categorizing successor states (in SimRun). That code is currently being refactored, but afterwards, that feature should be fairly easy to add. It'd be fairly equivalent (and have the same drawbacks) as the exploration technique method, though.
