### ISSUE TITLE
running symbolic execution for functions

### ISSUE THREAD

**Issue by bejab2020** [angr/angr#2655]
hi

I have some question about running symbolic execution for functions :

when we use symbolic execution with call_state for a function, what happens for the functions in the target function,are they execute symbolically too?

can I run symbolic execution for a function only (i mean just the target function, not function calls in it(local calls) except simprocedure calls)? can I use call_state for this ? (i add the CALLLESS option to state but the symbolic run was incomplete for the function, is an option for this purpose?)

I have another question: how can I run the main function with call_state(bcz if I run it with entry_state or full_init_state the symbolic execution will run for the whole program), I mean, I want to run it just for the main function? how I must set argc and argv for this purpose ?

thanks alot

**Comment by rhelmot** [comment]
By default, call_state says only to start angr's emulation at the beginning of a function. If the program tries to call another function, the emulator will respect that and jump to the other function. You can change this behavior with the CALLLESS option, as you have found, but if the called function returns values through pointers, there is no way for angr to detect this and the emulation will continue as though those values were never changed. I would need to see your target program in order to determine exactly what's going wrong with your use case.

To call main with argc and argv set, do this: `state = project.factory.call_state(main_addr, len(args), angr.PointerWrapper([angr.PointerWrapper(arg) for arg in args])`, where `args` is a list of strings or bitvectors you would like to use for the program's arguments.
