### ISSUE TITLE
entry_state and args

### ISSUE THREAD

**Issue by schieb** [angr/angr#272]
When setting up an entry state with concrete values
```
>>> p = angr.Project("./filename")
>>> s = p.factory.entry_state(addr=main, args=["./filename", "arg1", "arg2"])
```
I expect the stack layout to look something like:
```
(sp)        7ffeff9c | <BV32 0x3>
            7ffeffa0 | char **argv
            7ffeffa4 | char **envp
            7ffeffa8 | ...
```

Instead is looks like (edited for clarity):
```
>>> print s.state.dbg_print_stack(depth=5)
SP = 0x7ffeff9c, BP = 0x00000000
(sp)        7ffeff9c | <BV32 0x3>
            7ffeffa0 | argv[0]
            7ffeffa4 | argv[1]
            7ffeffa8 | argv[2]
            7ffeffac | ...
```
Is this intended, and if so, why?

**Comment by rhelmot** [comment]
It's hard to tell whether that layout in particular was intentional. A lot of care went into designing the state constructors, but the goal was to replicate the interface provided by the loader, not the actual implementation. 

I can't remember off the top of my head what the stack actually looks like on x86 program entry, but it's not necessarily what you described your expectation to be. The entry point is not a normal function, and it does not take the same parameters as main(). 

You should check in a debugger what the stack actually looks like at a real program start!

**Comment by schieb** [comment]
Ah, I missed the __libc_start_main SimProcedure. Thanks for clarifying!
