### ISSUE TITLE
How to reset the path execution

### ISSUE THREAD

**Issue by frapik99** [angr/angr#278]
Hi,
let's suppose that I have a path that I found use ```pg.explore()``` and now I want to execute it again but from the beginning. Is it possible to do it?

it would be nice to implement a ```reset()``` function for the ```Path``` object.

Thanks

**Comment by rhelmot** [comment]
Paths are immutable, so you should be able to rerun the exact same path group constructor you originally run and you should get back a copy of the path group you started with.

**Comment by frapik99** [comment]
@rhelmot Thanks, but what if I don't want to rerun pg.explore() but just the path from the beginning?

**Comment by rhelmot** [comment]
Pretty much everything besides path groups that you can interact with in angr is meant to be immutable from a user interface perspective. There is no need for a reset method anywhere because if you just hold on to the object you started with (again, except for path groups, the solution for which I just described above), and it'll still work just like it did the first time you used it.

**Comment by frapik99** [comment]
@rhelmot Thanks but the problem is that I don't have the original path before the execution. My code is something like:

```
pg.explore(find=0x400400)
path = pg.found[0]
```

I think at this point path is at the "end"... Using ```path``` I would rerun it again like if it were at its beginning. Can you show me how please.

Thanks

**Comment by rhelmot** [comment]
You just have to save off a copy of the path immediately before running explore.

```
startpath = pg.active[0]
pg.explore(find=0x400400)
path = pg.found[0]

rerun = project.factory.path_group(startpath)
# do whatever
```

**Comment by frapik99** [comment]
Oh yes of course I can use pg.active[0] and pass to pg a state with the address that I need...

Thanks
