### ISSUE TITLE
CFG() vs CFGAccurate()

### ISSUE THREAD

**Issue by frapik99** [angr/angr#283]
Hi,
I was looking at this exercise [https://github.com/angr/acsac-course/blob/master/exercises/slide_104/0.solution.py](url) and I have seen that CFGAccurate() terminates in a reasonable time. The problem if I try it against, even small executables like ls, it takes forever. I'm aware that the combination of ```keep_state``` and ```context_sensitivity_level``` implies a much bigger work but I was wondering if there is a way to have the ```input_state``` at the end of the computation without using ```CFGAccurate()``` or maybe using something at faster than it.

Thanks

**Comment by ltfish** [comment]
> even small executable like `ls`, it takes forever

`ls` is not as small as the example (fauxware) as I was using. `CFGAccurate` is several orders of magnitude slower than `CFGFast` since it simulates the execution of basic blocks. Additionally, raising context sensitivity will lead to an (roughly) exponential increase in the number of basic blocks that you recover.

My suggestion is to limit `CFGAccurate` on a subgraph, like several functions, to make it more tractable.

**Comment by frapik99** [comment]
@ltfish thanks for the answer, do you suggest to pass multiple address to ```starts``` or also something else. It would be nice to have an example on the documentation as well if possible.

Thanks

**Comment by frapik99** [comment]
Hi,
as suggested I'm trying to create the paths just for specific functions. So I have a list like ```[134513781L, 134513781L, 134513763L]``` that contains all the target addresses i want to reach. All this addresses are part of the function ```f```. The fact is that if the project is compiled for a 64 bit machine all works well but if I try on a 32 bit machine the parameter value is something like ```134513742``` but the expected result should be ```220``` or ``216```. Do you have an idea why please?

The C code I used is:

```
#include<stdlib.h>
#include<limits.h>

int sum(int a, int b) {
	return a+b;
}

int sum2(int a, int b) {
	return a+b;
}

int main() {
	int a = 1001;

	a = 99 + 1;
	int b = sum(a,8) * 2;

	if ( b > 5 )
		malloc(b);
		malloc(b+4);
}
```
Thanks

**Comment by frapik99** [comment]
Hi, I think I have understood the problem, I create the ```cc``` using ```cc = simuvex.DefaultCC[p.arch.name](p.arch)``` but the current arch is a ```x86_64``` and the project was compiled for ```x86``` the first parameter is not returned. Infact, ```134513742``` if converted to hex is ```0x804844e```. If you break just before the first ```malloc``` the stack is the following:

```(gdb) x/10x $esp
0xffffd0f0:	0x000000d8	0x0804844e	0x00000064	0x00000008
0xffffd100:	0x00000001	0xffffd1c4	0x000000d8	0x00000064
0xffffd110:	0xf7fb03dc	0xffffd130
(gdb) 
```

My goal is to retrieve ```0xd8``` but instead I had ```0x0804844e```. I retrieved the first parameter doing:

```
first = cc.arg(found.state, 0)
```

Any idea?

Thanks

**Comment by schieb** [comment]
Are you inside the function when you run `first = cc.arg(found.state, 0)`, or are you just before the function call? In other words, what is `found.state.ip`? If the function has not been called yet then `cc.arg()` will be off by one because the return address has not been pushed onto the stack yet.

**Comment by frapik99** [comment]
@schieb Great, I'm just at the beginning before the function call. What do you suggest? Continue the execution until the first instruction after the first ```malloc``` and then extract the first parameter?

**Comment by schieb** [comment]
It depends on your goal. After reading the link you gave in your opening question it looks like your goal is to gain some knowledge about the arguments to certain functions so that you can perform some sort of run-time (or emulation-time) argument checking. If that is the case you can certainly check the arguments at each call instruction like you have just shown. If you choose to do it that way, you must enumerate and hook all instance of `call malloc`. In general that can be a difficult thing to do as it assumes a correct disassembly. Another solution would be to hook the actual malloc function, or rather, the plt entry for malloc. That is already done by angr via the malloc `SimProcedure`. So for that method you could just add code directly to [malloc](https://github.com/angr/simuvex/blob/master/simuvex/procedures/libc___so___6/malloc.py). If you go that route, you will have direct access to function arguments inside the `SimProcedure` so you don't need to instantiate your own `cc`.

**Comment by frapik99** [comment]
Hi @schieb ,
excellent suggestion. I think I'll hook the plt entry without touching the orginal ```malloc``` ```SimProcedure```. I think it would be better in case the team would change the ```malloc``` code. Isn't it?

Thanks again

**Comment by schieb** [comment]
If you want to have a self-contained solution (i.e., something you can easily share) then I would agree with you and avoid editing a `SimProcedure`.

A relevant read in case you run into trouble: angr/issues/247.

**Comment by frapik99** [comment]
Thanks @schieb

**Comment by rhelmot** [comment]
Another solution is that most functions on `SimCC` take a `stack_base` parameter that you can use to specify a pointer to where the return address of the function ought to be. This will make the functions work even in the case that the state is not immediately after the function call.

It looks like we've resolved our problems here!
