### ISSUE TITLE
Question: coverage analysis?

### ISSUE THREAD

**Issue by bntejn** [angr/angr#284]
Hi, is there an existing module to analyze the (object) branch coverage or the instruction coverage for an *exploration*? If not, any suggestion on the easiest way to implement one?

**Comment by schieb** [comment]
Easiest/quickest method I could come up with involves defining a `step_func` to pass to [`pg.explore()`](https://github.com/angr/angr/blob/5cff3b5802deffda1c4f1db34d84477d65a0bff9/angr/path_group.py#L781). It will be called [here](https://github.com/angr/angr/blob/5cff3b5802deffda1c4f1db34d84477d65a0bff9/angr/path_group.py#L522). Now you just need to keep some state as the paths get stepped and your function gets called. For a quick hack you can use globals or use (abuse?) [`path.info`](https://github.com/angr/angr/blob/5cff3b5802deffda1c4f1db34d84477d65a0bff9/angr/path.py#L63).

I am almost certain there is a better way but this was what came to mind first...

**Comment by luosichengx** [comment]
Sorry to bother you, is there any update on this topic ? I'm interested in angr's ability of binary analysis. While the api has changed, how to get the detail information now, or is there other better way to get   the branch coverage or the instruction coverage, thanks a lot.

**Comment by rhelmot** [comment]
In order to obtain branch coverage or instruction coverage for an exploration, you must accumulate a list of all the branches/instructions and then instrument the stepping process (there are many options but consider either SimInspect breakpoints or an exploration technique) to mark which branches/instructions are seen. I can't offer any further advice on how to do either of these.
