### ISSUE TITLE
How to detect or capture the crash?

### ISSUE THREAD

**Issue by leithon** [angr/angr#294]
Could you kindly give me some hint regarding of how to capture the crash when symbolically executing a program within angr?
For example, a statement _raise(SIGSEGV)_ is embed in the program.
When I use angr to symbolically executing the program, however, the execution did not suspend when executing _raise(SIGSEGV)_, and the program can step to the following successors.
I want to capture the crash. How could I do?

Thank you very much.

**Comment by rhelmot** [comment]
If you would like paths to halt when they would perform an action that would cause a segfault, add the option `simuvex.o.STRICT_PAGE_ACCESS` to the state. Any paths that would segfault will throw a SimSegfaultError and end up in the path group's "errored" stash.

The specific case you discuss is hard because angr currently doesn't support the raise library function or the kill syscall. If you wanted, you could write a short SimProcedure for the raise library function that either throws a `simuvex.s_errors.SimSegfaultError(self.state.scratch.bbl_addr, 'raise')` (this will throw the same error that STRICT_PAGE_ACCESS will throw), or mark the path as segfaulted in some other way convenient to your analysis.
