### ISSUE TITLE
solver.satisfiable() is Weird: same value test is differnent

### ISSUE THREAD

**Issue by gjxo12** [angr/angr#3014]
---

Hi, I'm trying check bitvector value in some case..

I got a memory address some 'c0000000'.

this value is 

![image](https://user-images.githubusercontent.com/15341381/145961337-9c9c3918-9359-4a21-af32-deb5b98caa0f.png)

and start to solver.satisciabe using angr and here is result...

'''
p = angr.Project("binary/fauxware")
    print(p.loader.shared_objects)
    # p.hook(0x401040)

    a = p.factory.blank_state()
    b = a.solver.BVV(0xc0000000,32)
    print(b)
    print(a.solver.satisfiable((0 > b,)))
    print(a.solver.satisfiable((0 > -1073741824,)))
    print(a.solver.satisfiable((b == -1073741824,)))
'''

and result is here

![image](https://user-images.githubusercontent.com/15341381/145962522-5a2e26cc-4140-4e7b-a692-15951e24f203.png)

i think the first result is being true... but result is false....

why i have this result... is this a bug?
plz help me, Thank you

**Comment by rhelmot** [comment]
The default < and > operators are unsigned integer comparisons, which we chose because it made the most sense for binary analysis. So you're actually comparing against 3221225472. To use signed comparisons, use state.solver.{SLT, SGT, SLE, SGE}. This explains the first result.

The second result is because you are comparing python integers directly, not bitvectors.

**Comment by gjxo12** [comment]
Thank you for your kindness! I understand this result.
have a nice day and i closed Issue.
