### ISSUE TITLE
How to obtain the input_state from a path?

### ISSUE THREAD

**Issue by rdrunker** [angr/angr#302]
Hi
based on previous issues I think it is not possible to generate the ```CFGAccurate```on big projects such as apache and ssh because it would talk forever because of its complexity. I think it might be possible reseanoble, instead, extract a specific path specifing the proper start and end address. My question is: is it possible to obtain the ```node.input_state``` for every node in a path without generating the ```CFG```? How can I do it? If not, what would be the quickest way to have all the input states for a path in a complex project such as ssh?

Thanks for your great work.

**Comment by ltfish** [comment]
Currently the state getting from `CFGNode.input_state` is generated from simulating one path reaching that node from the entry point. So clearly it's not possible to get such a state without generating `CFGAccurate`, since `CFGAccurate` is basically a numerical simulation for paths combined with forced execution of all branches at branching points.

However, you can definitely limit the state extraction to the scope of a `Path`. That is, if you know exactly which path you want to follow, you can first get such a `Path` instance in angr by providing proper input to a `Path` generated from an initial state, and then manually dump the path after each call to `step()`. This may not be feasible on complex programs like httpd or nginx since there are usually a) events, callbacks, and multi-threading or even multi-processing, and b) unimplemented function summaries (`SimProcedure`s) involved. If that's the case, you can either start your path later in the program (like, starting at the beginning of a handler instead of at the entry point of the program), or implement a minimal set of `SimProcedure`s required to follow that path. It's worth noting that in this way, it's not symbolic execution, but concrete execution (or rather, simulation), since you are supposed to give concrete input to trigger that path. There will be no force execution involved in this solution. If this is not what you want (i.e. you really want to do force execution of the path), please let me know.

**Comment by rdrunker** [comment]
Thank @ltfish, 
Since easier and enough for my initial tests I would follow the first approach. I know exactly at what address I want to reach, suppose the address is ```0x400400``` so I'll do something like: pg.explore(find=0x400400) and use ```pg.found[0]```. I could be wrong, can I just generat a ```Path``` object in angr an after use ```path.step()``` and at each step extract all the actions? My final goal is to perform an analysis similar to the one performed in the actual ```DDG```. So i need to access to ```action.type``` and similar.

Thanks

**Comment by ltfish** [comment]
> so I'll do something like: pg.explore(find=0x400400)

`pg.explore(find=0x400400)` will definitely give you a path explosion on any real-world sized program. You are doing a full symbolic exploration of all feasible paths in that way.

> can I just generat a Path object in angr an after use path.step() and at each step extract all the actions?

Of course. All actions will be recorded, and if the state option `TRACK_ACTION_HISTORY` is not enabled, previous actions will be discarded at each time `step()` is called. You can simply enable `TRACK_ACTION_HISTORY` in the initial state you are using, and then access `path.history.actions` to access all actions along the path.

**Comment by rdrunker** [comment]
Hi @ltfish , thanks for your answer. I'm not sure on how to generate the ```Path``` as an object but I'll try to di it following the documentation.

Thanks again

**Comment by ltfish** [comment]
That is correct!

I'm not aware that our documentation is _that_ bad :-(

**Comment by rdrunker** [comment]
Hi @ltfish no worries the documentation is fine, I was able to find the solution :)

You project is excellent so no worries and please continue to develop angr for the community, we really appreaciate it

**Comment by rdrunker** [comment]
Hi,
I have  couple of more questions:

* How can I programmatically find all the address where a specific function is called? For instance, atoi.. After that I need i to obtain a possible value for the first parameter

* If I need to have the stack pointer's vlue after every instruction should I use pg.step(num_inst=1) and after just get its value?

thanks

**Comment by rhelmot** [comment]
- Your first question is very complicated and can't really be accomplished in the general case. However, if you want it to just work in simple cases, something easy to do would be to lift an IRSB at every address in the binary, and filter out everything but the ones that end with an `Ijk_Call` jumpkind, jumping to the address of the function you're looking for. Then, for each callsite, execute only the single basic block prior to the call instruction, and then use a SimCC to extract the arguments.
- That would work. Another way to do it would be to use a SimInspect breakpoint.
- If you have a path, you can get at its underlying SimState with `path.state`.

Sorry for the delay in answering!

**Comment by rdrunker** [comment]
Thanks @rhelmot , all clear with the second and thjrd question. 

For the first question, my goal is to obtain all the paths from an address to a call to atoi. So i need to know the atoi's address and generate all the paths to it. At the moment it seems to be possible to know the atoi's address only after i have generated the CFG. Once i have the path,my idea, is to use path.step(num_inst=1) so after every instruction i can use path.state and get the sp and at the end of tge path i can also extract the atoi's parameter. Can you suggest a better approach? CFGAccurate() is too expensive

Thanks

**Comment by rhelmot** [comment]
Sorry for letting this drop!

- You can know the address of atoi by looking at the symbols provided by our implementation of the loader. Off the top of my head, it should be something like `project.loader.main_bin.get_symbol('atoi').rebased_addr`.
- There is no need to use num_inst=1. You can just step until you see a path that has reached the atoi address, and at that point you can simply look on the stack or in registers to find the parameter. angr provides an interface called `SimCC` (simuvex.s_cc) to extract data from function call argument passing. It expects a state that has just gone through the call opcode but has not yet set up the stack frame.

**Comment by rdrunker** [comment]
Hi @rhelmot, thanks for your suggestion. I think  got your point but I still few issue. Let's suppose I have a path called ```found``` that goes from the first line of main until the call to ```atoi```. In a loop I do something:

```
for address in found.addr_trace:
    node = cfg.get_any_node(address)
    input_state = node.input_state
    ...
```

Unfortunately in some cases I cannot retrieve node properly because a node at ```address``` is not found. Instead, if I terminat the path at the very first instruction afte ```atoi``` I can have it. What would be the best solution in this case? My goal is just to obtain the value of the first parameter, of course in case the funtion would be ```fread``` instead of ```atoi``` I would like to have the pointer's address.

Thanks a lot

**Comment by rhelmot** [comment]
Is there any particular reason you need the input state from the CFG? why is the state from the path not appropriate?

**Comment by rdrunker** [comment]
Hi
I'd say lack of knowledge. How do you suggest to obtain it? My goal is just to follow what happens in the path..

Thanks

**Comment by schieb** [comment]
> My goal is just to obtain the value of the first parameter

`found.state` has all the information you need. If `found.state.ip` corresponds to the call instruction (contrast to atoi's plt stub or the function itself), then you can access the first parameter via `found.state.se.any_int(found.state.stack_read(offset=0, length=4))`. If you are inside the function already use `offset=4` instead. If 64 bit, use `found.state.se.any_int(found.state.regs.rdi)`

There is more than one way to obtain that information (e.g., stepping into the call and using `SimCC` as @rhelmot suggested, or modifying the atoi `SimProcedure`). If this way isn't sufficient for your use case, feel free to follow up with more information.

**Comment by frapik99** [comment]
Hi all,
thanks for the interesting discussion. Probably I'm missing something but, why he cannot retrieve the input_state if the path terminates exactly at the instruction where the ```atoi``` is called but yes if terminated just after? I think he needs the input_state for perming a kind of analysis on the project so he needs the input_state right until the atoi.

My guess is because angr terminates the blocks at the call he cannot have the input_state for the "current" block if he terminates the path right at the ```atoi``` call. Am i right? What would be the best approach for having the input_state also for the atoi? The problem is that if he terminated the path right after the ```atoi``` the stack probably would be already changed....

Thanks

**Comment by rhelmot** [comment]
There is precisely zero information that is gained or lost in the difference between the state just before the call and the state just after the call. You just need to know which one you're working with. Because angr produces states that live between basic blocks by default, it includes utilities for extracting information from states immediately after the call instruction, in the form of SimCC.

**Comment by frapik99** [comment]
@rhelmot ,
so if finally I understood properly I can extract the address of the first parameter just doing:

```
cc = simuvex.DefaultCC[self.project.arch.name](self.project.arch)
arg = cc.arg(found.state, 0) 
address = found.state.se.any_int(found,state.regs.sp)
```

Assuming ```found``` to be the path found using pg.explorer and the function in scope to be ```fread``` and not ```atoi``` as before because @schieb explained me that already.

Thanks
