### ISSUE TITLE
Wrong simstate during analyze armel elf

### ISSUE THREAD

**Issue by AlexCasual** [angr/angr#3111]
During analyze file simulate exploration unexpected stops its execution on **udiv** instruction on variable, wich angr incorrect initialize to zero.
disasm : 
 ```
HAL_InitTick                                   
        08000804 10 b5           push       { r4, lr }
        08000806 04 46           mov        r4,TickPriority
        08000808 0e 4b           ldr        r3,[->uwTickFreq]                                = 20000000
        0800080a 18 78           ldrb       TickPriority,[r3,#0x0]=>uwTickFreq               = HAL_TICK_FREQ_1KHZ
        0800080c 4f f4 7a 73     mov.w      r3,#0x3e8
        **bug -->** 08000810 b3 fb f0 f3     udiv       r3,r3,TickPriority
```
bug on : _08000818 b0 fb f3 f0     udiv       TickPriority,TickPriority,r3_
angr initialize TickPriority == 0 , but In source code HAL_InitTick() call with TickPriority==15 :
```
HAL_StatusTypeDef HAL_Init(void)

{
  HAL_NVIC_SetPriorityGrouping(3);
  HAL_InitTick(0xf);
  HAL_MspInit();
  return HAL_OK;
}
```
explorer script : 
[explore.log](https://github.com/angr/angr/files/7965751/explore.log)
elf file : 
[STM32F100VETx.zip](https://github.com/angr/angr/files/7965756/STM32F100VETx.zip)

**Comment by fmagin** [comment]
Okay, this is actually fairly confusing, because you are probably using Ghidra and Ghidra renames the registers in the disassembly according to the parameters. But `r0` at this instruction isn't actually the argument `TickPriority` but the global variable `uwTickFreq`. Also your addresses are slightly different than mine?

So the more intuitive disassembly is:
```
        080007fc 10 b5           push                      { r4, lr }
        080007fe 04 46           mov                       r4,r0
        08000800 0e 4b           ldr                       r3,[->uwTickFreq]                                = 20000000
        08000802 18 78           ldrb                      r0,[r3,#0x0]=>uwTickFreq                         = HAL_TICK_FREQ_1KHZ
        08000804 4f f4 7a 73     mov.w                     r3,#0x3e8
        08000808 b3 fb f0 f3     udiv                      r3,r3,r0                          
```

So a more concise script to reproduce this is:
```python
import angr
proj = angr.Project("./STM32F100VETx.elf", load_options={"auto_load_libs": False})
cfg = proj.analyses.CFG()
state = proj.factory.entry_state()
proj.factory.simgr(state).run()
```

the curious thing is that with `state = proj.factory.call_state(proj.kb.functions['main'].addr)` this doesn't seem to happen, so somewhere before `main`, this value is overwritten with `0`?

You could now set a [`mem_write` breakpoint](https://docs.angr.io/core-concepts/simulation) at the address of `uwTickFreq` and find out why this is overwritten.

**Comment by AlexCasual** [comment]
Oh, thnx @fmagin
Reset_Handler()->LoopCopyDataInit() zero filled .bss section and uwTickFreq == 0

`Reset_Handler:

/* Copy the data segment initializers from flash to SRAM */
  ldr r0, =_sdata
  ldr r1, =_edata
  ldr r2, =_sidata
  movs r3, #0
  b LoopCopyDataInit

CopyDataInit:
  ldr r4, [r2, r3]
  str r4, [r0, r3]
  adds r3, r3, #4

LoopCopyDataInit:
  adds r4, r0, r3
  cmp r4, r1
  bcc CopyDataInit
  
/* Zero fill the bss segment. */
  ldr r2, =_sbss
  ldr r4, =_ebss
  movs r3, #0
  b LoopFillZerobss

FillZerobss:
  str  r3, [r2]
  adds r2, r2, #4

LoopFillZerobss:
  cmp r2, r4
  bcc FillZerobss
`
