### ISSUE TITLE
How to get more information about path constraints?

### ISSUE THREAD

**Issue by b4sic4lly** [angr/angr#314]
Hi,  
I am just playing around a bit with the constraints in paths. The path constraints look like this:

`
In [19]:  path.state.se.constraints
Out[19]: 
[<Bool unconstrained_ret_nothing_9_64[31:0] != 0x0>,
<Bool (unconstrained_ret_nothing_20_64[63:63] | (if (unconstrained_ret_nothing_20_64 == 0x0) then 1 else 0)) == 0>,
 <Bool unconstrained_ret_nothing_22_64 == 0x0>,
 <Bool unconstrained_ret_nothing_24_64 != 0x0>]
`

Is it now possible to easily lookup somehow, where in the assembly code the constraint was added, like the address of the branch instruction for example?

regards

**Comment by rhelmot** [comment]
What you're looking for is called "actions". There are a ton of different events that are logged over the course of execution, and these end up being collected and logged in a path's history. One of them is a record of exactly where and how a constraint got added to the state.

Because these options take up a lot of memory (they involve holding on to a reference to each intermediate state, I think?) by default we only hold on to the actions for the most recent block. This behavior can be changed by adding the `o.TRACK_ACTION_HISTORY` option to the SimState, but again, memory consumption. The alternative is consuming the actions after every step.

Let me know if you have any more questions!

**Comment by b4sic4lly** [comment]
Thank you that was very helpful. There also seem to be other related flags like o.TRACK_CONSTRAINTS or o.TRACK_CONSTRAINT_ACTION. Looking into the code it looks like this information gets written into state.log.actions, but when I add these options they do not appear there. Did I misunderstand this feature?

**Comment by rhelmot** [comment]
I'm not sure off the top of my head. The system for how this information gets tossed around is needlessly complicated, having organically grown through about two refactors of the surrounding systems.

My rule of thumb is that the only option that you ever need to use in "normal" usage of the actions subsystem is TRACK_ACTION_HISTORY, but if that's not working, well...

The other thing you can try is path.last_actions, which always contains the most recent run's actions, regardless of TRACK_ACTION_HISTORY. If this is still empty, try running path.step() before looking at path.last_actions.

**Comment by b4sic4lly** [comment]
ok, thank you for your help, this was very helpful!
