### ISSUE TITLE
%k$p format string error in angr/procedures/stubs/format_parser.py 

### ISSUE THREAD

**Issue by 4everdestiny** [angr/angr#3148]
---

**Describe the bug.**

I recently write a program to use format string Vulnerability, but I find printf("%3$p") sentence's result is not like normally.
In angr:  
printf("%3$p")
angr result:
%$p
but result I expected is:
0x7fffffffd90 like

**Additional context.**

so how to solve this problem, I just want to use %k$n and %k$p format

**Comment by rhelmot** [comment]
The problem is I don't know how to implement this. Arbitrarily indexing the nth member of an argument list is extremely nontrivial when you take into account the fact that floating point and struct argument can take up strange numbers of registers or amounts of stack memory. If you can come up with a reference for how libc solves this problem, I'd be happy to implement it.
