### ISSUE TITLE
Clarification of successor types, possible bug

### ISSUE THREAD

**Issue by Lukas-Dresel** [angr/angr#328]
Can someone give me a breakdown of the successor types in `SimSuccessors`?
E.g. the `flat_successors` according to @zardus are for symbolic IPs, however I have found in my code that they have the `successors` as well.

What is the intended behavior here?

**Comment by zardus** [comment]
We should add this to the simuvex docs when we recreate them, but here are the different types of successors on the SimSuccessors object:

| Attribute | Guard Condition | Instruction Pointer | Description |
|-|-|-|-|
| `successors` | True (can be symbolic, but constrained to True) | Can be symbolic (but 256 solutions or less; see `unconstrained_successors`). | A normal, satisfiable successor state to the state processed by the engine. The instruction pointer of this state may be symbolic (i.e., a computed jump based on user input), so the state might actually represent *several* potential continuations of execution going forward. |
| `unsat_successors` | False (can be symbolic, but constrained to False). | Can be symbolic. | Unsatisfiable successors. These are successors whose guard conditions can only be false (i.e., jumps that cannot be taken, or the default branch of jumps that *must* be taken). |
| `all_successors` | Anything | Can be symbolic. | This is `successors + unsat_successors`. |
| `flat_successors` | True (can be symbolic, but constrained to True). | Concrete value. | As noted above, states in the `successors` list can have symbolic instruction pointers. This is rather confusing, as elsewhere in the code (i.e., in `SimEngineVEX.process`, when it's time to step that state forward), we make assumptions that a single program state only represents the execution of a single spot in the code. To alleviate this, when we encounter states in `successors` with symbolic instruction pointers, we compute all possible concrete solutions (up to an arbitrary threshold of 256) for them, and make a copy of the state for each such solution. We call this process "flattening". These `flat_successors` are states, each of which has a different, concrete instruction pointer. For example, if the instruction pointer of a state in `successors` was `X+5`, where `X` had constraints of `X > 0x800000` and `X < 0x800010`, we would flatten it into 16 different `flat_successors` states, one with an instruction pointer of `0x800001`, one with `0x800002`, and so on until `0x80000f`. |
| `unconstrained_successors` | True (can be symbolic, but constrained to True). | Symbolic (with more than 256 solutions). | During the flattening procedure described above, if it turns out that there are more than 256 possible solutions for the instruction pointer, we assume that the instruction pointer has been overwritten with unconstrained data (i.e., a stack overflow with user data). *This assumption is not sound in general*. Such states are placed in `unconstrained_successors` and not in `successors`. |

**Comment by zardus** [comment]
Added to https://github.com/angr/angr-doc/blob/master/docs/simuvex.md#simsuccessors. I'll close this, but reopen it if i wasn't clear somewhere!

BTW, the code that classifies the successors is in `SimSuccessors._categorize_successor`, if you want to take a look.
