### ISSUE TITLE
How to get the machine code (in binary) for each basic block?

### ISSUE THREAD

**Issue by squarekyzhong** [angr/angr#3352]
---

**Comment by squarekyzhong** [comment]
I want to get machine code in binary format per block. Is it possible to get that by angr? Thank you.

**Comment by rhelmot** [comment]
```
[+] In [3]: p.factory.block(p.entry).bytes
Out[3]: b'\xf3\x0f\x1e\xfa1\xedI\x89\xd1^H\x89\xe2H\x83\xe4\xf0PTL\x8d\x05\x16/\x00\x00H\x8d\r\x9f.\x00\x00H\x8d=\x18\xff\xff\xff\xff\x15\xa2y\x00\x00'
```

**Comment by squarekyzhong** [comment]
Thank you so much for your reply.  Here is an another question.  I use the following 2 methods to get the number of functions that the program has, but they have different outputs. The first one has 26 while the second has 18. Can you explain why is the case occuring? Next, I use code in 3 to get their function names, seeing that the number of different functions in the method 1. is 17, while the other is 18.
1. 
proj = angr.Project('/Users/squareky/Downloads/fauxware', load_options={'auto_load_libs': False})
cfg = proj.analyses.CFGEmulated(keep_state=True)
cg = cfg.functions.callgraph
print(len(cg.nodes))

2.
idfer = proj.analyses.Identifier()
print("no. of functions", len(idfer.func_info))

3.
       lfunc_name=[]
       for node_addr in cg.nodes:
           node = cfg.functions.function(node_addr)
           if node and node.name not in lfunc_name:
               lfunc_name.append(node.name)
       print(len(lfunc_name))
       print(lfunc_name)

       for funcInfo in idfer.func_info:
            print(funcInfo.name)

**Comment by rhelmot** [comment]
Please don't use the Identifier. Its stated purpose is to use emulation to identify library functions by checking against expected outputs for a set of hardcoded testcases. Internally, identifier generates a CFGFast in order to figure out where to even begin its analysis, so what you're really comparing here is CFGFast vs CFGEmulated. These are two different cfg construction algorithms and they will usually come up with different results. As you can probably see from the third test, CFGEmulated's more-functions is not necessarily better. We pretty much always recommend people use CFGFast.

**Comment by squarekyzhong** [comment]
Thank you very much for the helpful suggestion. Is there a way to get the list of library functions and user functions separately in a function?

**Comment by rhelmot** [comment]
If your binary is dynamically linked, you can check if the function is part of the import table or the PLT. If the binary is statically linked, you will have to resort to signature based identification of library functions.
