### ISSUE TITLE
Accessing all the strings of a binary in 1 go

### ISSUE THREAD

**Issue by ghost** [angr/angr#34]
From the documentation what I gather is, the best way to find all strings in the binary(and their addresses) is to walk through each function and find the string references.

``` python
cfg = proj.analyses.CFG();
for addr in cfg.function_manager.functions:
    f = cfg.function_manager.functions[addr]
    print f.string_references()
```

Are there better/faster ways to go about doing this?

**Comment by ltfish** [comment]
`strings <your_binary> | less`?

Joking aside, the default CFG module in angr is slow but accurate. In theory, `GirlScout` is the fast CFG, since it does not try to execute blocks and does not resolve any indirect jump. However, its code may have been bit rotted - that's why I didn't document it in angr-doc. It's definitely on my TODO list though.

`GirlScout` does not generate any string reference right now, but that functionality should be simple: you should parse VEX statements and try to see if any address is referencing memory data that looks like a string.

Feel free to try it out, and leave comments or open issues if it does not work!

**Comment by eQu1NoX** [comment]
Thanks!
I just tried using GirlScout and I seem to be running into a bit of a strange problem.

```python
In [8]: gs  = proj.analyses.GirlScout()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-8-2f7b4a49594b> in <module>()
----> 1 gs  = proj.analyses.GirlScout()

/home/ieurqo/angr-master/venv/lib/python2.7/site-packages/angr/analysis.pyc in make_analysis(*args, **kwargs)
     82             oself.project = self.project
     83
---> 84             oself.__init__(*args, **kwargs)
     85             return oself
     86

/home/ieurqo/angr-master/venv/lib/python2.7/site-packages/angr/analyses/girlscout.pyc in __init__(self, binary, start, end, pickle_intermediate_results, perform_full_code_scan)
    199         self.functions = None
    200         # Calls between functions
--> 201         self.call_map = networkx.DiGraph()
    202         # A CFG - this is not what you get from project.analyses.CFG() !
    203         self.cfg = networkx.DiGraph()

AttributeError: can't set attribute
```

**Comment by ltfish** [comment]
Great... this is caused by the recent refactoring I believe. I'll fix that.
