### ISSUE TITLE
C Structure Recovery

### ISSUE THREAD

**Issue by jwtouron** [angr/angr#3440]
Angr team,

I am trying to use Angr to recover C structures from compiled binaries. 

What I have so far is a C test program:
```
#include <stdio.h>
#include <stdlib.h>

typedef struct s {
    int i;
    char *s;
} S;

static void f(S *s)
{
    printf("i: %d, s: %s\n", s->i, s->s);
}

int main()
{
    S s1;
    s1.i = 42;
    s1.s = "42";
    f(&s1);

    S *s2 = malloc(sizeof(S));
    s2->i = 43;
    s2->s = "43";
    f(s2);

    return 0;
}
```

I compiled it with: `gcc -o testprog test.c`. 

A portion of it, when, disassemble via `objdump -d testprog`, looks like:
```
0000000000001189 <f>:
    1189:       f3 0f 1e fa             endbr64
    118d:       55                      push   %rbp
    118e:       48 89 e5                mov    %rsp,%rbp
    1191:       48 83 ec 10             sub    $0x10,%rsp
    1195:       48 89 7d f8             mov    %rdi,-0x8(%rbp)
    1199:       48 8b 45 f8             mov    -0x8(%rbp),%rax
    119d:       48 8b 50 08             mov    0x8(%rax),%rdx
    11a1:       48 8b 45 f8             mov    -0x8(%rbp),%rax
    11a5:       8b 00                   mov    (%rax),%eax
    11a7:       89 c6                   mov    %eax,%esi
    11a9:       48 8d 3d 54 0e 00 00    lea    0xe54(%rip),%rdi        # 2004 <_IO_stdin_used+0x4>
    11b0:       b8 00 00 00 00          mov    $0x0,%eax
    11b5:       e8 c6 fe ff ff          callq  1080 <printf@plt>
    11ba:       90                      nop
    11bb:       c9                      leaveq
    11bc:       c3                      retq

00000000000011bd <main>:
    11bd:       f3 0f 1e fa             endbr64
    11c1:       55                      push   %rbp
    11c2:       48 89 e5                mov    %rsp,%rbp
    11c5:       48 83 ec 30             sub    $0x30,%rsp
    11c9:       64 48 8b 04 25 28 00    mov    %fs:0x28,%rax
    11d0:       00 00
    11d2:       48 89 45 f8             mov    %rax,-0x8(%rbp)
    11d6:       31 c0                   xor    %eax,%eax
    11d8:       c7 45 e0 2a 00 00 00    movl   $0x2a,-0x20(%rbp)
    11df:       48 8d 05 2c 0e 00 00    lea    0xe2c(%rip),%rax        # 2012 <_IO_stdin_used+0x12>
    11e6:       48 89 45 e8             mov    %rax,-0x18(%rbp)
    11ea:       48 8d 45 e0             lea    -0x20(%rbp),%rax
    11ee:       48 89 c7                mov    %rax,%rdi
    11f1:       e8 93 ff ff ff          callq  1189 <f>
    11f6:       bf 10 00 00 00          mov    $0x10,%edi
    11fb:       e8 90 fe ff ff          callq  1090 <malloc@plt>
    1200:       48 89 45 d8             mov    %rax,-0x28(%rbp)
    1204:       48 8b 45 d8             mov    -0x28(%rbp),%rax
    1208:       c7 00 2b 00 00 00       movl   $0x2b,(%rax)
    120e:       48 8b 45 d8             mov    -0x28(%rbp),%rax
    1212:       48 8d 15 fc 0d 00 00    lea    0xdfc(%rip),%rdx        # 2015 <_IO_stdin_used+0x15>
    1219:       48 89 50 08             mov    %rdx,0x8(%rax)
    121d:       48 8b 45 d8             mov    -0x28(%rbp),%rax
    1221:       48 89 c7                mov    %rax,%rdi
    1224:       e8 60 ff ff ff          callq  1189 <f>
    1229:       b8 00 00 00 00          mov    $0x0,%eax
    122e:       48 8b 4d f8             mov    -0x8(%rbp),%rcx
    1232:       64 48 33 0c 25 28 00    xor    %fs:0x28,%rcx
    1239:       00 00
    123b:       74 05                   je     1242 <main+0x85>
    123d:       e8 2e fe ff ff          callq  1070 <__stack_chk_fail@plt>
    1242:       c9                      leaveq
    1243:       c3                      retq
    1244:       66 2e 0f 1f 84 00 00    nopw   %cs:0x0(%rax,%rax,1)
    124b:       00 00 00
    124e:       66 90                   xchg   %ax,%ax
```

I'm running Angr like so:
```
import angr

proj = angr.Project('testprog', auto_load_libs=False)
cfg = proj.analyses.CFGFast(normalize=True)
main = proj.kb.functions['main']
dec = proj.analyses.Decompiler(main, cfg=cfg.model)
print(dec.codegen.text)
```

Which outputs:
```
WARNING | 2022-07-15 08:58:57,546 | cle.loader | The main binary is a position-independent executable. It is being loaded with a base address of 0x40 0000.
typedef struct struct_0 {
    unsigned int field_0;
    char padding_4[4];
    unsigned long long field_8;
} struct_0;

int main()
{
    struct_0 *v0;  // [bp-0x30]
    unsigned int v1;  // [bp-0x28]
    unsigned long v2;  // [bp-0x20]

    v1 = 42;
    v2 = "42";
    f();
    v0 = malloc(0x10);
    v0->field_0 = 43;
    v0->field_8 = "43";
    f();
    return 0;
}
```

The last piece I'm trying to figure out is how to associate `v0 = malloc(0x10);` in the decompiled output above with offset `0x1200` in the binary. In other words, I want to be able to use Angr to determine that `rax` at offset `0x1200` in the binary contains the struct `struct_0` (or will be used as `struct_0`). 

It seems clear to me that the `Decompiler` knows this, as the text produced shows, but I haven't been able to figure out how to get his information from the `Decompiler` instance. I've looked through the source code of the `Decompiler` and `CStructuredCodeGenerator`, as well as Angr's unit tests, but the solution escapes me.

A second, question I have is why does the `Decompiler` not see the address of `struct_0` being passed into the function `f` (and how would I get `f` to also be decompiled).

Please help. Thank you.

**Comment by ltfish** [comment]
> The last piece I'm trying to figure out is how to associate v0 = malloc(0x10); in the decompiled output above with offset 0x1200 in the binary. In other words, I want to be able to use Angr to determine that rax at offset 0x1200 in the binary contains the struct struct_0 (or will be used as struct_0).

What you want are a series of maps that `dec.codegen` provides (sorry for the lack of documentation):

- `map_pos_to_node`: Maps positions (offsets) in a decompilation output string to AIL (ailment) AST nodes.
- `map_pos_to_addr`: Maps positions (offsets) in a decompilation output string to closest instruction addresses.
- `map_addr_to_pos`: Maps instruction addresses to positions (offsets) in a decompilation output string.
- `map_ast_to_pos`: Maps AIL AST nodes to positions (offsets) in a decompilation output string.

So you can use these mappings to convert an offset into an AIL AST node, take the node, and then access its `.ins_addr`, `.stmt_idx`, and `.block_addr` attributes to see where it is coming. In your case, you'll find an AIL AST node whose class is `Register` and whose `ins_addr` is `0x1200`.

This is exactly what angr management does for mapping selections in pseudocode view to disassembly view, and vice versa. You may want to give it a try.

> A second, question I have is why does the Decompiler not see the address of struct_0 being passed into the function f (and how would I get f to also be decompiled).

angr does not know the prototype (or calling convention) of `f`. You have three options:

- Perform a full-binary calling convention analysis (or just analyze the calling convention of `f`), which will allow angr to know the prototype and calling convention of function `f`, before decompiling `main`. You can do this by running `proj.analyses.CompleteCallingConventions(recover_variables=True)`.
- Enable call site analysis, so that angr will use the information at the call sites of `f` to reason about the number of arguments `f` takes. You can enable it by passing `analyze_callsites=True` to `CompleteCallingConventions()`. This is useful for functions whose implementations are not known during the analysis (e.g., an external library function).
- Manually specify the prototype and calling convention for `f`. You'll want to set `f.calling_convention` and `f.prototype`.

**Comment by jwtouron** [comment]
This is great. Based on the information you provided, I've been able to do everything I need to do. Thank you so much. As far as I'm concerned, the issue can be closed.

**Comment by ltfish** [comment]
Awesome!
