### ISSUE TITLE
Ideas behind the construction of DDG/DataDepsGraph/VFG?

### ISSUE THREAD

**Issue by xrkk** [angr/angr#3587]
### Question

It's not too difficult to read the source code of constructing DDG/DataDepsGraph/VFG etc, but it's not that easy to understand backend idea. Any references? Maybe papers?

**Comment by ltfish** [comment]
Unfortunately there are no papers for them, since they are just straightforward and textbook implementations of algorithms...

- DDG generates data dependence graphs based on forced-emulation results derived in CFGEmulated. The idea is similar to [X-Force](https://www.usenix.org/system/files/conference/usenixsecurity14/sec14-paper-peng.pdf) but was based on a different paper.

- VFG is based on value-set analysis (VSA). You can find the original PhD thesis "WYSINWYX: WHAT YOU SEE IS NOT WHAT YOU EXECUTE" by Dr. Gogul Balakrishnan to read. We further implemented signedness-agnostic VSA.

- DataDepsGraph is a dynamic version of the data dependency graph that is generated using symbolic exploration results on _one path_.
