### ISSUE TITLE
state.posix.open takes a long time to open large files

### ISSUE THREAD

**Issue by r00tus3r** [angr/angr#3794]
It takes 40 mins to open a file with size 128 MB.

```
import angr
import logging
from angr.state_plugins.posix import Flags

logger = logging.getLogger(name=__name__)
logger.setLevel(logging.INFO)

args = ["/bin/ls",
        "fs.img"]

p = angr.Project(args[0])
state = p.factory.blank_state(concrete_fs=True, mode="tracing")
state.options.remove(angr.sim_options.COPY_STATES)
logger.info("Opening file")
state.posix.open(args[1], Flags.O_RDWR)
logger.info("Done")
```

```
(pypy) ubuntu@thingy:~/$ python test_open.py 
INFO     | 2024-02-02 00:19:05,925 | __main__       | Opening file
INFO     | 2024-02-02 00:59:56,922 | __main__       | Done
```

**Comment by ltfish** [comment]
@rhelmot Can we use mmap to solve this issue?

**Comment by rhelmot** [comment]
There are a couple of ways we can solve this problem. The way I was hoping would work was that breaking the object into 4k-sized BVVs and storing one per page instead of trying to create one BVV for the entire file would work, but apparently that's too slow. I was going to profile it and see if there was some other bottleneck. Barring that, the next approach would be to use SimMemory's backer feature to use the blob of the file as fallback data without having to have it as BVVs until it was accessed. I would rather not use mmap because we don't have a good way to reclaim that file descriptor other than just letting it be garbage collected.

**Comment by ltfish** [comment]
With the PR, opening the same file now takes about 20 seconds for me.
