### ISSUE TITLE
Pros and cons of enabling or disabling `fail_fast` during analysis

### ISSUE THREAD

**Issue by riyadparvez** [angr/angr#42]
In https://github.com/angr/angr-doc/blob/master/analyses.md#resilience, it is written:

> These errors, depending on how they're caught, are logged to the errors or named_errors attribute of the analysis. However, you might want to run an analysis in "fail fast" mode, so that errors are not handled.

It is not explained what are the pros and cons of disabling or enabling `fail_fast` during analysis.

**Comment by zardus** [comment]
Yeah, that should be documented more and/or removed.

Basically, my initial design for the `Analysis` subclass was that it would provide all of these building blocks for a single analysis. `fast_fail` would control if the whole analysis would be aborted when a single building block failed. Unfortunately, no one really used `Analysis` the way that I expected them to, and `fast_fail`, along with the rest of the `Analysis` logging and error infrastructure wasn't used. For most analyses, I think `fast_fail` literally does nothing.

Probably a case of over-engineering :-)

That being said, there's recently been some talk on refactoring some analyses to actually take advantage of the design and provide a bit more user control (i.e., running an analysis a step at a time in `angr-management`). We'll see what happens!

**Comment by riyadparvez** [comment]
Thanks for the reply.

I am seeing angr can't extract CFG for some binaries e.g. it is missing lots of basic blocks and edges. I am guessing the binaries are not very amenable to static analysis. Is there any good way to know why it is failing?

**Comment by ltfish** [comment]
Hi Riyad,

The short answer is, angr is not good enough :-)

The long answer is, that we never put enough effort to make angr's CFG as complete as possible. We did a bit experiment (on our upcoming angr release), which shows that even after quite some improvement to angr's CFG generation algorithm, our CFG coverage is only equal to or better than IDA Pro's for 60% of all test cases we have. We are looking into it now, and I believe it will be greatly improved with a) more implementation bugs fixed, and b) the upcoming object-sensitivity analysis feature.

If you'd like to debug angr and see why it's slow, you would have to look into `angr/analyses/cfg.py` and manually set some hooks there. Turn on logging output for `CFG` class by using `logging.getLogger('angr.analyses.cfg').setLevel(logging.DEBUG)`, which should give you some idea of what CFG is doing.

The code of CFG class right now is a bit messy (in the sense of not grouping related methods together, and unnecessarily using unnamed tuples instead of proper classes), which will be reorganized in the next two releases. Sorry if you want to read the code before that :P

**Comment by riyadparvez** [comment]
Hi Fish,

My experience with angr in extracting CFG has been pleasant so far.

I've tried with `logging.getLogger('angr.analyses.cfg').setLevel(
logging.DEBUG)`, but seeing no debug output. Right now, it is kind of
important for me to know whether or not angr had any issues when extracting
CFG so that I can detect issues as early as possible.

**Comment by zardus** [comment]
Are you seeing any other output from other components (i.e., did you run
logging.basicConfig or something similar)?

**Comment by riyadparvez** [comment]
OK, I am seeing debug output now. Feeling stupid.

The CFG extracted by angr for some binaries misses many basic blocks. Is
there any way to figure out from debug log when such case occurs? Is there
any obvious pattern in the log file that can indicate major issues when
extracting CFG?

**Comment by ronnychevalier** [comment]
On Wed, Nov 18, 2015 at 7:54 PM, Riyad Parvez <notifications@github.com>
wrote:

> OK, I am seeing debug output now. Feeling stupid.
>
> The CFG extracted by angr for some binaries misses many basic blocks. Is
> there any way to figure out from debug log when such case occurs? Is there
> any obvious pattern in the log file that can indicate major issues when
> extracting CFG?
>
>
If you see something like:
- "No bytes in memory"
- some unsat errors from claripy
- you can have a lot of "Exit state has over 257 possibilities", but using
enable_advanced_backward_slicing can help
- If you use enable_advanced_backward_slicing, you can have some "The
target exit is not included in the slice"
- worst case scenario: SimIRSBError because some instructions are not
handled by vex

I think there is more but these are the ones that I encounter often.

**Comment by riyadparvez** [comment]
Thanks.


On Wed, Nov 18, 2015 at 2:11 PM, Ronny Chevalier <notifications@github.com>
wrote:

> On Wed, Nov 18, 2015 at 7:54 PM, Riyad Parvez <notifications@github.com>
> wrote:
>
> > OK, I am seeing debug output now. Feeling stupid.
> >
> > The CFG extracted by angr for some binaries misses many basic blocks. Is
> > there any way to figure out from debug log when such case occurs? Is
> there
> > any obvious pattern in the log file that can indicate major issues when
> > extracting CFG?
> >
> >
> If you see something like:
> - "No bytes in memory"
>

I've seen this one. What is the reason behind this error. "No bytes in
memory" itself is not very descriptive.

**Comment by ronnychevalier** [comment]
On Wed, Nov 18, 2015 at 8:40 PM, Riyad Parvez <notifications@github.com> wrote:
>
> > If you see something like:
> > - "No bytes in memory"
> >
>
> I've seen this one. What is the reason behind this error. "No bytes in
> memory" itself is not very descriptive.
>

If I'm not wrong, it's because the instruction pointer is going crazy
and you are jumping somewhere you should not, so there is no code at
this location.

**Comment by riyadparvez** [comment]
My guess is right then. The static disassembly of the binary does not match
runtime disassembly, `objdump` also fails to disassemble the binary
properly.

Is there any API to check these errors from client code instead of grepping
log files?

**Comment by ronnychevalier** [comment]
On Wed, Nov 18, 2015 at 9:40 PM, Riyad Parvez <notifications@github.com> wrote:
>
> My guess is right then. The static disassembly of the binary does not match
> runtime disassembly, `objdump` also fails to disassemble the binary
> properly.
>
> Is there any API to check these errors from client code instead of grepping
> log files?
>

Officially there is the `errors` attribute which should be populated
with the resilience thing, but as @zardus it's not really used, so
basically no you can only use the logs.

**Comment by riyadparvez** [comment]
Can it safely be assumed any ERROR level log statement from the analysis is
a major issue?

**Comment by zardus** [comment]
Unfortunately, the CFG logs errors pretty happily right now. We have a huge update for the CFG (and lots of other things in angr) coming out in the next week or so. It doesn't do anything for log levels, but the CFG is a *LOT* faster and much more complete.

**Comment by riyadparvez** [comment]
Thanks.

I think it would be helpful for the client code, to have an API where the
client can have access to errors. I personally want this feature to
understand whether .or not something terribly gone wrong during extracting
CFG.

**Comment by ltfish** [comment]
Eventually I got some time for this thread!

I'm planning to make the following improvements to our CFG recovery.

Performance:
- It will try to resolve indirect-jumps less often. Generally it helps a lot in some sexy architectures like MIPS, where most functions calls are compiled down to indirect jumps.
- Create a `CFGFast` analysis routine, which does some preliminary CFG recovery tasks with the help of function prolog/epilog identification, jump table recovery, etc. It does not rely on `SimState`s, which is why it's fairly fast (and is usually comparable to IDA's CFG). It's less accurate, of course, but it should be enough for a preliminary understanding. The current `CFG` will become `CFGAccurate`.
- I'll see if it's possible to make CFG recovery multi-threaded. Using only one core on a 40-core machine is a crime.

Code:
- I'm refactoring CFG's code. Personally I'm not a code neat freak (unlike someone else in the team), and over time, the `CFG` class has bit-rotten quite a little. And I have to admit that some of my old C-style code is really difficult to understand (even for myself!) My goal is to make CFG code more modular and easy to read. It's difficult, but I'll try my best.
- Logging. It's a big issue right now for users that CFG spits quite some error logs, most of which are false alarms. For those true alarms, very few people really understands how to deal with it. "No bytes in memory" is definitely not helpful to understand what's going on. I'll make those logging more useful to end users with more descriptions and suggestions of solutions.

Visualization:
- Right now, debugging CFG is a pain, especially for big binaries. I spend a lot of time typing `cfg_node.successors[0].successors[0]....predecessors[1]` just to understand what the graph looks like. I'm planning to develop `angr-management`, which will eventually give users a friendly interface to browse and dig into a CFG with a certain level of context-sensitivity.

A few of those improvements will be seen in the recent release, and others are either in development, or on my TODO list. Your ideas and suggestions are more than welcomed!

**Comment by riyadparvez** [comment]
On Fri, Nov 20, 2015 at 10:17 AM, ltfish <notifications@github.com> wrote:

> Eventually I got some time for this thread!
>
> I'm planning to make the following improvements to our CFG recovery.
>
> Performance:
>
>    - It will try to resolve indirect-jumps less often. Generally it helps
>    a lot in some sexy architectures like MIPS, where most functions calls are
>    compiled down to indirect jumps.
>    - Create a CFGFast analysis routine, which does some preliminary CFG
>    recovery tasks with the help of function prolog/epilog identification, jump
>    table recovery, etc. It does not rely on SimStates, which is why it's
>    fairly fast (and is usually comparable to IDA's CFG). It's less accurate,
>    of course, but it should be enough for a preliminary understanding. The
>    current CFG will become CFGAccurate.
>
> Have you done any benchmarking how much accurate is fast CFG recovery with
respect to CFGAccurate?

On a related note, do you know what is the difference between
`cfg.unresolvables` and `cfg.unresolved_indirect_jumps`?
