### ISSUE TITLE
Question about SimActions for SimProcedures

### ISSUE THREAD

**Issue by axt** [angr/angr#421]
@ltfish , @zardus :

When I create a SimProcedure, the generated action list will not contain any kind of TMP actions, as it does for VEX lifted code (if TRACK_TMP_ACTIONS is enabled). 

For example it generates these actions for an empty simprocedure:
```
<SimActionData <simproc>() reg/read>    # read value of esp
<SimActionData <simproc>() reg/write>   # esp += 4
<SimActionData <simproc>() mem/read>    # read ret addr from stack
<SimActionExit <simproc>() conditional> # this should be 'default' i guess, but doesnt matter too much for now
<SimActionData <simproc>() reg/write>   # set eip to the value read from stack
```
My problem is that for example the DDG analysis is depending on the tmp actions, which are missing from this list, so it can't really handle these list of actions. 

I want to create an analyis what is relying on SimActions (like DDG does).
 
What is the original purpose of SimActions?
Is it encouraged to base an analysis on them?
If yes, how can I overcome the situation above?

**Comment by zardus** [comment]
We created actions to allow us to track the provenance of data as it was processed by a program. The idea was that, by analyzing a chain of SimActions, we could reason about data flow. Unfortunately, SimActions are what we call a "first-generation design" -- they get the job done but they're very clunky and hard to work with.

The flow of data from reg or mem actions through tmp actions is an artifact of our VEX settings, not a base property of how angr processes data. With different VEX options (specifically, if we don't use flattened IR), we can have data flowing straight from a reg read to a mem write, for example. Likewise, this is how SimProcedures create actions, without any intermediate temporaries.

If the DDG requires tmps to function, then the problem lies with the DDG, unfortunately :-(

**Comment by axt** [comment]
Thanks @zardus. This answers the question. So I shouldn't use actions in any form to base an analyis on them. It's not about DDG, i know it is under a heavy refactor, but I forgot to tell why I'm asking this: what is the preferred way then to track data flow?

**Comment by axt** [comment]
Nevermind! I found the answer for my problem! :-)
