### ISSUE TITLE
Shall I submit issues for not implemented arguments of existing SimProcedures?

### ISSUE THREAD

**Issue by gitttt** [angr/angr#44]
For examples, the printf SimProcedure seems to not support long integers, that is, exploring the following code leads to an errored path:

long blah;
blah = 1;
printf("%li", blah);

Would you suggest submitting such things as an issue? I mean, it is obvious to everybody that angr's coverage of system functions is not complete yet and submitting such things could pollute the repo.
What do you think?

**Comment by zardus** [comment]
I think reporting is useful. Ideally, we'd get to a point where, performance-wise and path explosion-wise, we can execute the *actual* printf. Right now, for constrained data (like your example), you can probably disable SimProcedures and be ok. For real software, though, printf tends to cause gigantic path explosions...

Anyways, philosophy aside, it's useful to see what sort of specific features people need so that we can implement them. `li`, for example, should be fairly simple.
