### ISSUE TITLE
Is there a way to install a breakpoint on a event a simulation level instead of state level ?

### ISSUE THREAD

**Issue by Voxanimus** [angr/angr#4641]
### Question

Everything is in the title.

**Comment by rhelmot** [comment]
SimInspect breakpoints are solidly isolated to the SimState level, so the answer to your question is no. However, SimulationManagers are eminently instrumentable, so you should be able to do everything you want with either a step loop (instead of .run() or .explore()) or a custom ExplorationTechnique.

**Comment by Voxanimus** [comment]
Yeah I was thinking about this and hopped to not have to rewrite a bunch of code. I guess I won't escape it X). Thanks you
