### ISSUE TITLE
angr.errors.AngrCallableError: No paths returned from function

### ISSUE THREAD

**Issue by carryinfo** [angr/angr#465]
hi,
I write a small 'libfunc.so' which on android platform. when I use callable to run the function in it.
It always raise:  angr.errors.AngrCallableError: No paths returned from function

for the howtouse.dll from the example, there is no any problem

anyone can help me? below is the code. thanks a lot :)

import angr

def main():
    p = angr.Project('libfunc.so', load_options={'main_opts': {'custom_base_addr': 0x10000000}})
    howtouse = p.factory.callable(0xf20)
    # p = angr.Project('howtouse.dll', load_options={'main_opts': {'custom_base_addr': 0x10000000}})
    # howtouse = p.factory.callable(0x10001130)
    return howtouse(10)

if __name__ == '__main__':
    print main()

**Comment by rhelmot** [comment]
You've specified the base address of 0x10000000, but you're calling a
function at 0xf20. You need to rebase that address.

**Comment by carryinfo** [comment]
@rhelmot  but when I change the address to 0x10000f20, raise the same exception .  any other suggestions?  thanks

**Comment by rhelmot** [comment]
Sorry for letting this drop. In order to debug this issue, you should use not a callable but a `call_state` initialized similar, then drop it into a path group and run it. By looking at how the execution happens, you will be able to tell more easily what's going on - is an error occurring, is there a program exit happening, etc.
