### ISSUE TITLE
Will Mayhem be open sourced?

### ISSUE THREAD

**Issue by leotian** [angr/angr#470]
Will mayhem be an open source project where can i find his code and documentation?

**Comment by giovannivigna** [comment]
Hilarious.

**Comment by ltfish** [comment]
Unfortunately Mayhem is not an open source project. We, like anyone else in this field, are also interested in its code and documentation!

Please email us a copy if you find one and would like to share with the rest of the world!

**Comment by rhelmot** [comment]
The previous answers were unclear: mayhem is not a project of the angr team - it is by the researchers at CMU, a separate group from us. It is highly unlikely they will ever open-source their work.

We did implement mayhem as described in their paper *as an extension to angr*, in order to evaluate against it, but this is not open-sourced either, at least partially due to bit-rot.
