### ISSUE TITLE
How to obtain the "real" CFG?

### ISSUE THREAD

**Issue by frapik99** [angr/angr#473]
Hi all,
I have created the ```CFGFast``` graph for my pngpixel and my problem is that, for example, I call in multiple cases the function ```puts```(address is 0x80485f0) and of course it can have multiple successors as shown below:

```
In [15]: n = cfg.get_any_node(0x80485f0)
In [16]: n.successors
Out[16]: 
[<CFGNode main+0xbf 0x804885a[14]>,
 <CFGNode main+0x8f 0x804882a[13]>,
 <CFGNode puts 0xd000110L[0]>,
 <CFGNode UnresolvableTarget 0xd000300[0]>]
```
I would like to have a graph that would connect the node calling the ```puts``` only to one successor based on the case but in my case I have the node connected to all the successors.

is there a way to achieve it? Any other suggestion?

Thanks

**Comment by ltfish** [comment]
`CFGFast` is not context sensitive. Your best bet for now is `CFGAccurate` with a context sensitivity level of at least 1.

**Comment by frapik99** [comment]
Thanks @ltfish , I'll try ASAP. One clarification, I think I have been told that the ```CFGFast``` guarantees full code coverage instead ```CFGAccurate```, so could I take every single node in the ```CFGFast``` symbolically execute and then obtain something similar to the ```CFGAccurate```? I know that would be very expensive but I would try to understand the difference between ```CFGFast``` and ```CFGAccurate``` more in details.

Thanks

**Comment by ltfish** [comment]
You are right. `CFGFast` guarantees a full code coverage, while `CFGAccurate` does not. `CFGAccurate` tries to simulate program execution _to some extent_, which is why you can have states in `CFGAccurate`.

You should be aware that a full context-sensitive CFG does not scale well: the number of nodes in the graph grows exponentially with the level of context-sensitivity level. You can build a `CFGFast` first, and then construct `CFGAccurate` only starting from those functions that you care about.

**Comment by ltfish** [comment]
A comment on your title: all CFGs are real :-)
