### ISSUE TITLE
Deleted Conversation After Bug Fix

### ISSUE THREAD

**Issue by lion10** [angr/angr#4879]
### Question

What is the point of deleting the conversation/bug description after fixing a bug? It seems weird to me

**Comment by twizmwazin** [comment]
Can you be specific about what you mean? When an issue is completed, the issue is closed, but not deleted. It is still viewable and can be reopened if the solution is later found to be invalid. Users can still comment on them and we receive notifications for those comments just the same as an open issue.

**Comment by lion10** [comment]
Thanks for the clarification. I have noticed some issues (e.g., 1381, 2691, 2467, 2487, 3445, 4004, 4365, 4541, etc.) have no descriptions available. It seems like the original details were removed, not sure yet. It makes it harder to track the history of the issues...

**Comment by twizmwazin** [comment]
Of those that I checked, they are PRs made by the core developers of angr. In general we make PRs so that we can run any changes through the CI prior to merging them. They are not necessarily bugs and there often isn't much context to add in the body that isn't in the title, nor do we expect anyone to actually read them.

**Comment by lion10** [comment]
I see, thanks!
