### ISSUE TITLE
How to skip an instruction during symbolic execution?

### ISSUE THREAD

**Issue by sparktend** [angr/angr#495]
I use angr to do symbolic execution. the arch is arm/thumb.
The basck block's assembler code are below:
```
.text:000016CA               MULS          R3, R2
.text:000016CC               SUBS           R4, R4, R3
.text:000016CE               BL               some_func
.text:000016D2               MOV            R3, 3
```
My purpose is skip the instruction in 0x16CE，That is not to execute the instruction like BL/BLX/BX。

The ways I tried are:
1. Use ```inspect.b(0x4102FD, hook_change, length=0)```, then change the PC register in the ```hook_change()```. 0x4102FD is the address of some_func.
2. Change the PC register or ```state.scratch.ins_addr``` directly.

My idea is to modify the PC register or to change the ins address of the current state.
But it did't work.
I'm not very familiar with angr, who can tell me how to do?

**Comment by rhelmot** [comment]
Modifying the PC register with a breakpoint will not work due to the way the execution process works - a block of code is lifted and executed at a time.

The correct approach here is to add a hook (consult the docs for how to do this) that does nothing, on top of the 4 bytes of the BL instruction. The hook will change the way the instruction-lifting process works so it will stop before the BL instruction, then your hook will execute, doing nothing, and then it will resume 4 bytes later on the MOV instruction.

**Comment by rhelmot** [comment]
something like:

```python
def nothing(state):
    pass

project.hook(0x4102fd, nothing, length=4)
```

**Comment by ltfish** [comment]
This should be added to angr-doc.

**Comment by sparktend** [comment]
The code in 0x102fd are below:
```
.text:000102FC  ; void *some_func(size_t size)
.text:000102FC                 BX              PC
.text:000102FC ; ---------------------------------------------------------------------------
.text:000102FE                 ALIGN 4
.text:000102FE ; End of function some_func
.text:000102FE
.text:00010300                 CODE32
.text:00010300
.text:00010300 ; =============== S U B R O U T I N E =======================================
.text:00010300
.text:00010300 ; Attributes: thunk
.text:00010300
.text:00010300 ; void *some_func_stub(size_t size)
.text:00010300 some_func_stub                         ; CODE XREF: some_funcj
.text:00010300                 LDR             R12, =(some_func2 - 0x20E0C)
.text:00010304                 ADD             PC, R12, PC ; some_func2
.text:00020E04 ; End of function some_func_stub
```

I try your code 
```
def nothing(state):
    pass

project.hook(0x4102fd, nothing, length=4)
```
but it will continuely execute the instruction on 0x102fe, then 0x10300. not work.
is this because this function is very special?  or the value of length is wrong?

**Comment by rhelmot** [comment]
The instruction at 0x10300 is no longer in thumb mode! If you want to execute it correctly you should have the instruction pointer point to 0x10300 exactly, so if you hook at 0x102fd, you should hook with `length=3`, since 0x10300 - 0x102fd is 3.

If it's still not working, or if I'm understanding, you should show me the end of the `trace.hardcopy` for your path me and tell me what looks wrong with it.

**Comment by sparktend** [comment]
I tested the different address to hook.
**The first case:**
`project.hook(0x4102fd, nothing, length=3)`

Then the trace is 
```
<IRSB from 0x4016c1: 1 sat>
<SimProcedure UserHook from 0x4102fd: 1 sat>
<IRSB from 0x410300: 1 sat>
<IRSB from 0x4031b8: 1 sat>
<IRSB from 0x4016d3: 1 sat>
```

**The second case:**
`project.hook(0x4016cf, nothing, length=4)`

Then the trace is 
```
<IRSB from 0x4016c1: 1 sat>
<SimProcedure UserHook from 0x4016cf: 1 sat>
<IRSB from 0x4016d3: 1 sat>
```

The two methods can meet my needs.
But I think the second case is more closer to my purpose that don't call the function I specified during symbolic execution.
I will deal with the more general situation, to find each instrument starts with` BL/BLX`. then hook the instrument's address to skip it.
am I right? if the two methods both the right way to do so, which one is better?
Thank you very much for completing my goal.

**Comment by rhelmot** [comment]
It depends on if you're making a transition from THUMB to non-THUMB code. I only suggested 3 bytes because it successfully aligned the instruction pointer so that you would land on the correct instruction alignment to execute non-THUMB code even though it was THUMB going into the hook. You should pick whatever length will cause the instruction pointer to jump to wherever you want it to be.

**Comment by sparktend** [comment]
OK, I know. 
Thank you.
