### ISSUE TITLE
How to generate test cases using symbolic execution

### ISSUE THREAD

**Issue by iceeeeee** [angr/angr#501]
Hi all,

I am trying to use angr's symbolic execution engine to create test cases. I notice that angr could easily generate command line inputs by creating an symbolic value `x = claripy.BVS('x', 32)` and pass this value `x` to the state of symbolic execution `state = b.factory.entry_state(args=[x])`. Then angr would be able to generate the test cases for the argument `x`. I hope this is the correct way to do the test case generation.

However, when the program's input is a file, I have trouble on generating those test cases. I would be appreciate if anyone could give me a hint on how to solve this problem. 

Thanks,
iceeeeee

**Comment by rhelmot** [comment]
At some point the program will open the file, and it will be assigned a file descriptor. You can call state.posix.dumps(x) to return a concretization of the symbolic data for file descriptor x based on the constraints on the state (a test case). You will have to figure out what the right file descriptor is, but if it is the first file opened by the program it will be #3. 

I think there is also a dumps_by_filename function that takes a filename instead of a file descriptor, but I can't remember if that's the right name and I am not in a position to look that up right now.

**Comment by iceeeeee** [comment]
@rhelmot Thanks for your suggestion. I have tried the way you suggested, but get no result by state.posix.dumps(3) at any time after the file should be opened. 1 is the only file descriptor contains data, which I think is stdout. I believe there must be some thing wrong during my usage, but I cannot figure out the right way to do it.

The following is the logic of my test binary:
Usage: ./test ./inputfile (there is a number in the inputfile)
    `fp = fopen(argv[1], "r");
fscanf(fp, "&d", &i);
if (i <5){ ... }`

The script logic is:
`x=claripy.BVS('x', 32)
state = b.factory.entry_state(args=['./test', x])
pg = b.factory.path_group(state)
pg.explore()
print(pg.deadended[0].state.posix.dumps(3))`

I would be appreciate if anyone could help me. Thanks.
iceeeeee

**Comment by rhelmot** [comment]
angr does not have a simprocedure for fscanf implemented, but DOES have a simprocedure for fopen implemented - this is very bad, since angr will service the fopen call but then your native libc will try to service the fscanf call. The data structures will not play nice together.

You will need to implement a fscanf simprocedure (it should be simple, just adapt the scanf simprocedure), or switch your sample code to use fread or something.
