### ISSUE TITLE
Extracting function-level CFG

### ISSUE THREAD

**Issue by aboudiz** [angr/angr#509]
Hi,
I would like to extract function-level CFG of functions (as much as possible) in the binary. 
I tried using `CFGFast`, which produced good results (`cfg.functions[...].graph`) for ~300kb binary, but for ~2mb binary it took ages (about an hour or so).

Is it supposed to be like that? Note that I'm only interested in the function-level CFG - I don't care about the relations between the functions themselves. Is there any other approach I can take?

**Comment by ltfish** [comment]
> but for ~2mb binary it took ages (about an hour or so).

We are always trying to make CFGFast faster. Supposedly CFGFast should work as fast as common disassemblers (like IDA Pro or Hopper). If it takes ages on a 2 MB binary, something is definitely not working as expected.

Before we get down to some known performance-impacting issues (like the current jump-table resolution implementation), you can try PyPy first (instead of CPython), which usually gives a significant speed boost for static analyses like CFGFast.

**Comment by ltfish** [comment]
Other tips including:

- Set `resolve_indirect_jumps` to False.
- Make sure `collect_data_references` is set to False.
- Set `force_complete_scan` to False.

If you can provide the binary, or give us a profiling output (using cProfile, for example), that would be great.
