### ISSUE TITLE
install in simuvex with pip resolved with an issue with pyvex

### ISSUE THREAD

**Issue by labba** [angr/angr#51]
Collecting simuvex
  Using cached simuvex-4.5.12.28.tar.gz
Collecting bintrees (from simuvex)
  Using cached bintrees-2.0.2-cp27-none-win32.whl
Collecting dpkt-fix (from simuvex)
  Using cached dpkt-fix-1.7.tar.gz
Collecting pyvex (from simuvex)
  Using cached pyvex-4.5.12.21.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "c:\users\user\appdata\local\temp\pip-build-pn9ogr\pyvex\setup.py", line 21, in <module>
        if subprocess.call(['tar', 'xzf', 'dev.tar.gz']) != 0:
      File "c:\python27\lib\subprocess.py", line 522, in call
        return Popen(_popenargs, *_kwargs).wait()
      File "c:\python27\lib\subprocess.py", line 710, in **init**
        errread, errwrite)
      File "c:\python27\lib\subprocess.py", line 958, in _execute_child
        startupinfo)
    WindowsError: [Error 2] The system cannot find the file specified

```
----------------------------------------
```

Command "python setup.py egg_info" failed with error code 1 in c:\users\user\appdata\local\temp\pip-build-pn9ogr\pyvex

**Comment by rhelmot** [comment]
Angr cannot be installed via pip on Windows. If you want to install angr on
Windows, get a mingw or Cygwin environment and then follow the instructions
in the readme for a development install.

**Comment by labba** [comment]
well in the angr example there is an "re400.exe" and there is a solution script ... so how this doesn't run  on windows ?

**Comment by ltfish** [comment]
We solved challenge on Linux :-) Note that you can load arbitrary binaries in angr no matter what your host operating system is.

Windows support is minimal at the moment - although there is interest in doing that, we simply don't have enough man power to do so. Development should work just fine (if not, feel free to open another issue), but we are not anywhere close to get it working via pip. Most likely, angr itself works (since it's almost pure Python), but getting all other supporting libraries on Windows is not an easy task.

**Comment by labba** [comment]
thanks! got it!

**Comment by ltfish** [comment]
Update: As for now, angr runs well on Windows. In fact, I exclusively develop angr on Windows.
