### ISSUE TITLE
Is windows PE binary supposed to run under angr

### ISSUE THREAD

**Issue by humeafo** [angr/angr#537]
I just tested a windows binary, but unfortunately, it refused to run under angr, so is windows PE binary supposed to run under angr?
there seems no libc win32api emulation layer, so is this a future work or just won't be supported in near future?

**Comment by rhelmot** [comment]
There is a branch `wip/sizzle` that improves windows support. However, it's very complicated and still not very good.

We currently don't implement any syscalls (SSDT entries) for windows, and even on wip/sizzle we only implement a small number of kernel32.dll simprocedures.

On top of that, most of our static analyses will not work because they assume caller-cleanup calling conventions.

On top of THAT, I've never successfully gotten a windows binary to execute all the way to main() before because for some reason it's incredibly common to statically link windows programs with their equivalent of libc, and their equivalent of `__libc_start_main` does a TON of crazy stuff.

**Comment by humeafo** [comment]
thanks for your info, this can be closed.
