### ISSUE TITLE
about abstraction of libc procedures

### ISSUE THREAD

**Issue by moliam** [angr/angr#547]
In angr, the calls into libc procedures such as atoi, strcmp, strlen, etc, are abstracted and simulated with expressions consisting of series of "if" and "else". Is this abstraction work difficult to realize or does it require much intelligence?
By the way, I did some experiments with angr and it seems that for "strcmp", angr can only solve the situation where the condition is like 0 == strcmp(a, b) or 0 != strcmp(a, b), but cannot solve 0 > strcmp(a, b) or 0 < strcmp(a, b). Is this due to the incompleteness of the procedure abstraction model?

Thank you very much!

**Comment by humeafo** [comment]
You can see the sim procedure implementation to see various limitations exposed by libc state plugin such as max_str_len etc, this may cause libc functions return unexpected result compared to real concrete execution on many inputs.
I'm new to angr too, so forgive me if I have wrong understandings.

**Comment by humeafo** [comment]
About current libc function abstraction, It seems that angr has only too modes:
1. use the libc func abstraction model
2. not using it at all

I think a third model maybe worth doing @zardus @rhelmot @ltfish :
concrete exec it when input data are concrete, use the abstraction only when symbols are involved.
simulating library codes would be tedious and error-prone with various corner cases and thus decrease scalability to real-world software. on the other side, due to path explosion, without abstraction, when symbolic data are involved, analysis may not be effective.
this mode perhaps can be implemented lazily, just concrete exec library function first, when symbolic values encountered, then backtrace to the function entry and using the abstraction to do the real work.
For I'm a noob to angr, so forgive me if I was wrong.

**Comment by moliam** [comment]
@humeafo    actually angr will give a concrete result when the input of an simulated function is concrete. It would help a lot to use a debugger(such as PyCharm) to learn the inner mechanism of angr. 
Maybe I don't make my question very clear.  My question is about the mathematical method for simulating an external function, and the logic equivalence between the simulated and the real procedure.

**Comment by humeafo** [comment]
@moliam What I mean is the simulation may not produce coherent result as real procedure on some inputs because of simulation's defects or limitations(this can be improved of course), and maybe it's hard to achieve strict equivalence on all inputs.  
As to symbolic inputs, I think the mathematical method is correct in logic but may not be totally  equivalent on some inputs(eg,very long strings) because of some practical limits, such as various libc size/length limits, or claripy's recursion limits.

**Comment by bennofs** [comment]
@humeafo using concrete execution is hard though. it may work for things like `strcmp` but it will definitely fail if you try to do it for `malloc` (as the heap structure will not be set up correctly when all the heap functions are hooked)

**Comment by zardus** [comment]
One idea we've bounced around is to support a concretization layer like what is proposed in "In-vivo Symbolic Execution". Basically, past some point on the callstack (i.e., inside the heap functions), any symbolic data they touch is automatically concretized (with the resulting possibility of then executing the functions in unicorn). For stuff like the heap, where you _usually_ aren't expecting symbolic data to be reasoned over, it would provide a very nice speedup, and allow us to more faithfully mirror actual execution.
