### ISSUE TITLE
Optimization of vsa_ddg (parallelization?)

### ISSUE THREAD

**Issue by gitttt** [angr/angr#59]
Hi!
I found this comment in the `vsa_ddg.py`

> `# TODO: The worklist algorithm can definitely use some optimizations. It is a future work.`

What optimization do you have in mind?
Would it make sense to parallelize the worklist algorithm?
Is is even possible in general to parallelize the task of creating def use chains?
In other words, is it a bad idea to think of parallelization or even distributed computing in this context?

**Comment by ltfish** [comment]
Hey, thanks for asking.

For work-list optimization, I was considering implementing a DFS based CFG traversal, instead of the current naïve traversal algorithm. DFS can reduce the number of iterations that required to come to the fix-point.

About parallelization, here are my two cents:

As I see it, parallelizing the algorithm should be doable. Obstacles for parallelization are mainly in implementation (Python doesn't have real multi-threading support, and multi-processing can make the code unnecessarily difficult to maintain). There should be a noticeable performance gain as long as elements in work-list are "properly" distributed to individual workers. By saying "properly", I'm talking about the dependence between analyzing individual basic blocks. For example, analysis of a basic block `B` requires the analysis result of its predecessor `A`, and if `A` and `B` are distributed onto two different workers, analysis of `B` will have to be stalled until `B` is analyzed. Fortunately, the CFG (or rather, VFG for `vsa_ddg`) is available, and it should be straightforward to figure out the dependence between basic blocks (or states).

Parallelization will be beneficial for all angr analyses, not on `VSA_DDG`. In the past few weeks, we worked on creating a unified data-flow analysis framework (called `ForwardAnalysis` right now), and refactored `CFG` as a subclass of `ForwardAnalysis`. The long-term goal is to make all work-list based analyses subclasses of `ForwardAnalysis`, and I think it might be worthwhile and easier to parallelize `ForwardAnalysis`, instead of parallelizing individual analysis.

However, I'm by no means an expert of program analysis. I bet there must be existing papers or implementation on parallel program dependence graph generation. It is greatly appreciated if you can post what you know or heard here so I can learn more :-)

**Comment by zardus** [comment]
"I'm by no means an expert of program analysis," says our foremost expert on program analysis :-)
