### ISSUE TITLE
Bug in CFGFast

### ISSUE THREAD

**Issue by Vectorlee** [angr/angr#617]
I compiled coreutils 8.27. In the **cp** program, function 0x402FB0 (target_directory_operand), CFGFast doesn't recover the CFG correctly.  Below is the binary:
[cp.zip](https://github.com/angr/angr/files/1262088/cp.zip)

The error is a very simple one. Here is the CFG recovered by angr:
![screenshot from 2017-08-29 17-36-44](https://user-images.githubusercontent.com/2527873/29850200-bd7c2cd4-8ce0-11e7-8db1-cccec109b99f.png)

Here is the CFG recovered by IDA, which is the correct one:
![screenshot from 2017-08-29 17-37-04](https://user-images.githubusercontent.com/2527873/29850213-d23f9782-8ce0-11e7-88e0-28b0ed7b898e.png)

As you can see, there is an edge missing in the angr's CFG, from node `0x402FEA` to node `0x402FF1`. Angr's analysis basically put a duplicated node `0x402FF1` inside the node `0x402FFA` (since the first one contains return statement). The node `0x402FEA` suppose to be 7 byte instead of 18.

**Comment by Vectorlee** [comment]
This function is a special case where it have more than one exit: one is return statement, another is a function call `call _error`, which will terminate the program and never return. This might be the primary reason for this problem.

**Comment by rhelmot** [comment]
It is extremely difficult to tell what's going on because your IDA cfg is missing its line prefixes and addresses, but as far as I can tell there are no bugs here. The notion of a "basic block" is "you start at this address and you run uninterrupted for some number of blocks, at which point you might jump somewhere". The basic block starting at 0x402fea runs uninterrupted until the return of the function.

What you want is called a normalized CFG. Pass `normalize=True` to the cfg constructor to make this happen.

Also, please don't capitalize the first letter of angr.

**Comment by rhelmot** [comment]
Actually from looking at this more carefully I think there is a bug here, but it's that 0x40300e doesn't have any successors - we're supposed to break basic blocks at callsites. I think this is similar to a bug I reported earlier this week to @ltfish. If so, angr's analysis fails to propogate the information that `quotearg_style` can return.

**Comment by Vectorlee** [comment]
I attached the binary, you can check it in IDA. There is a jump target in the middle of node `0x402FEA`, so the basic block should break into two and has an edge to node `0x402FF1`. This is a trivial mistake usually shouldn't occur in CFG analysis, so I guess it is a side effect of no successors issue of  `0x40300E`.

**Comment by Vectorlee** [comment]
Besides, the `CFGAccurate` result for this function is even worse, it basically includes another function entirely.

**Comment by rhelmot** [comment]
```
.text:0000000000402FEA mov     byte ptr [new_dst+0], 1
.text:0000000000402FEF xor     eax, eax
```

This is not a basic block ending with a jump target. If you want the cfg to break the node at this point, you need to say `normalize=True`, like I said.

**Comment by ltfish** [comment]
> Besides, the `CFGAccurate` result for this function is even worse, it basically includes another function entirely.

This is a different issue. I'm aware of a few bugs in CFGAccurate w.r.t. function grouping. I think it's related.

**Comment by Vectorlee** [comment]
@rhelmot  I see, thanks for the explanation. I think I should close this issue.

But before I close it, can you briefly tell me why do you distinguish the normalized version of CFG vs the no-normalized version? What's the benefit of having this no-normalized CFG? Thank you!

**Comment by ltfish** [comment]
> why do you distinguish the normalized version of CFG vs the no-normalized version

Because they are different.

> What's the benefit of having this no-normalized CFG?

The normalization of a CFG is the process of breaking bigger basic blocks in case there are overlapping basic blocks. A basic block `A` overlaps with a another basic block `B` if `A` starts in the middle of `B`, and during normalization, the block `B` will be split into two blocks: `B0` and `A`. However, you do not know whether you should break `B` or not until block `A` is recovered during CFG recovery. Therefore, without a full CFG of that function recovered, you cannot normalize the CFG of that function.

I agree that a normalized CFG feels more natural to human analysts, but most automated analyses do not care whether the CFG is normalized or not. CFGs in angr are intended to be used by both other analyses and humans. Therefore, we do not normalize CFGs by default, and you can always normalize it if you need to.

PS: In the graph view of angr management, we only display normalized CFGs, which is because that view is solely intended to be read and analyzed by human analysts.

**Comment by Vectorlee** [comment]
I see. Thank you very much Fish!

**Comment by ltfish** [comment]
You are welcome :-)
