### ISSUE TITLE
Got Unsupported CCall x86g_calculate_RCL

### ISSUE THREAD

**Issue by YHZX2013** [angr/angr#653]
Is it not implemented? If so, what other ccall have not been implemented? Thanks.

**Comment by zardus** [comment]
The ccalls are defined here: https://github.com/angr/angr/blob/master/angr/engines/vex/ccall.py, and called from here: https://github.com/angr/angr/blob/master/angr/engines/vex/expressions/ccall.py. Grepping for "unsupported" will give you an idea of the current state, though of course, it's hard to say exactly what is missing.

It does look like you're using an outdated version of angr -- rhelmot implemented RCL in commit bacf84d56be12cc6889f6347df5265c7f7606531 in July.

Finally, there are two fallbacks in the case of unsupported ccalls:

1. the `BYPASS_UNSUPPORTED_IRCCALL` state option will skip unsupported ccalls and return an unconstrained symbolic value instead. This will allow you to proceed, but at the cost of a potential path explosion caused by that symbolic value later.
2. The `Oppologist` exploration technique catches errors encountered while executing VEX and runs the offending basic block in Unicorn Engine instead. This gets through the error at the cost of concretizing symbolic data. See the test cases for an example: https://github.com/angr/angr/blob/master/tests/test_oppologist.py#L21
