### ISSUE TITLE
Missing function names, PPC64 ELF

### ISSUE THREAD

**Issue by drone-rites** [angr/angr#662]
After running a CFG analysis on a PPC64 ELF binary with symbols, all program-specific functions are missing the symbol-defined name.

This can be replicated by creating an angr project, running either CFGFast or CFGAccurate, and then looking at the functions listed in the knowledge base's function manager.

ELF binaries for other architectures I've tried don't have this problem, including: x86, x64, and ppc32.

**Comment by rhelmot** [comment]
If this is an `abiv1` ppc64 binary (check `readelf -h`), that would be more or less expected, since under that ABI the symbols don't actually point to the function but rather to a structure called the table of contents that points to that function.

One solution would be to change the logic where we import symbols into the `labels` kb plugin, to say if this binary is ppc64 abiv1 (there's a property in cle specifically for that check), add labels for both the function name and the toc, with the latter suffixed with `@toc` or `.toc` or something.

**Comment by rhelmot** [comment]
(this would require CFG to never do symbol lookup of its own, or at least just use the label data already in the kb - @ltfish?)

**Comment by mattrepl** [comment]
ABI version is listed as 0.

**Comment by rhelmot** [comment]
aaand that's what I was afraid of. None of the test binaries I have on hand are like that - could you send a sample?

**Comment by ltfish** [comment]
> this would require CFG to never do symbol lookup of its own, or at least just use the label data already in the kb

This can happen.
