### ISSUE TITLE
AttributeError: 'ExternObject' object has no attribute 'tls_block_offset'

### ISSUE THREAD

**Issue by abarbaro** [angr/angr#693]
Hi all,
I have just uploaded ```angr``` and I try to create a project for ```/bin/ls``` with the command ```b = angr.Project("/bin/ls", load_options={'skip_libs': ['libc.so.6'], 'auto_load_libs': True})``` i have the following error:

```
AttributeError: 'ExternObject' object has no attribute 'tls_block_offset'
```

Removing the ```skip_libs``` the error disappears.Can you have a look into it?

Thanks

**Comment by rhelmot** [comment]
This is a very complicated bug that has to do with the fact that there is an unresolved dependency on a thread-local symbol. Our extern object tries to provide it, but the extern object is not equipped to provide thread local storage objects. I'm genuinely unsure how to solve this.

A workaround would be to allow libc to be loaded and stub out all its exports with simprocedures to force angr to not analyze them.

**Comment by abarbaro** [comment]
Thanks @rhelmot , I'll wait the fix from you. In the meantime I'll replace all the export with a function that does nothing. is it correct?

Thanks

**Comment by ArtemShypotilov** [comment]
Hi Guys!

I'm also having this issue when trying to load binaries with relocations like:

```
 Offset     Info    Type            Sym.Value  Sym. Name
000467b8  00006911 R_ARM_TLS_DTPMOD3 00000000   _ZSt15__once_callable
000467bc  00006912 R_ARM_TLS_DTPOFF3 00000000   _ZSt15__once_callable
```

However, I use `angr.Project("bin_with_tls_vars_import", load_options={'auto_load_libs': False})`.

As a workaround I added to my `cle/backends/externs.py`:

```
class ExternObject(Backend):
    def __init__(self, loader, map_size=0x8000):
        super(ExternObject, self).__init__('cle##externs', loader=loader)
		...
        self.tls_module_id = 99999
        self.tls_block_offset = 0
```
		
Can we merge this to angr? This won't hurt anything, right?

**Comment by rhelmot** [comment]
This will, in fact, hurt things. Assigning that module ID will cause CLE to index into a guest-memory array at index 99999, which is distinctly an out-of-bounds value. Assigning that block offset will cause thread-local variables to be stored at the offset of thread pointer, which is necessarily overwriting a bunch of metadata used by guest code to handle thread-local stuff!

The correct way to get these values set up correctly in a backend is to do [pretty much this](https://github.com/angr/cle/blob/master/cle/backends/elf/elf.py#L688), where you basically specify a load from your binary image and set `.tls_used = True`, and then the tls object will see you and register you and set those values correctly, including updating metadata about your existence.

Obviously, this workflow doesn't work correctly for the extern object, but that's okay! Adding a special code path for where to assign addresses to extern is just a refactor. It has some issues to address such as how to figure out how much space to allocate and/or how to deal with dynamic loading, but those are the kind of issues that have been addressed before.

The _real_ problem here, the one preventing me from doing any of this, is #151. If we were to do the above without solving 151, it would create variables with totally bogus sizes, which would cause all sorts of horrifying corruption issues in the emulated guest. Once that issue is solved I will take a crack at doing this the right way.

**Comment by ArtemShypotilov** [comment]
Hi Audrey,

Yes, thats my bad, didn't notice that you have implementation of `__tls_get_addr` at first.

So do I understand correctly that the main problem is what to provide as the imported data when there are no libs?

And you have an idea to make some functionality similar to SimPocedure, but for the imported data symbols?

For example, if we encounter `stdout` symbol which has `R_X86_64_COPY` relocation, we should allocate all the appropriate memory, fill it with data and place pointers (or whatever should be placed) to the relocation place? So it would seem that data is copied to our binary like from the real libc?

Can we make that memory symbolic for now? For example, for `stdout` symbol, symbolize 8 bytes (size as shown by readelf) in `.bss` section at its address? If memory is symbolic, there won't be corrupted read\writes, right? And the same for tls imports, can we just give extern object piece of symbolic memory for TLS data so it could return addresses pointing in it whenever they are requested by `__tls_get_addr`?

**Comment by rhelmot** [comment]
Making it symbolic could work but it would have to be done in angr (cle has no notion of things being symbolic), but more importantly it would not do a very good job handling pointers, since usually when you concretize an unconstrained pointer angr will shrug and dereference null. You could theoretically do it with a concretization strategy that allocates a new memory region for each fully unconstrained pointer that gets concretized, but that sounds scary. You are right that for COPY relocations the size is absolutely known, but given the above concerns I would still want the full blown solution.

Actually, you know what. I'm going to do this right now. Your comment about "SimProcedures for data symbols" is a really nice insight, and I can work with that.

**Comment by rhelmot** [comment]
It is done.

I haven't really been able to test whether the extern-provided TLS symbols are correct, as there are about nine billion ways to screw up all the TLS parameters, but to my eyes it matches the way ELF and PE do it.
