### ISSUE TITLE
LoopLimiter does not work after the mega refactor

### ISSUE THREAD

**Issue by rain6851** [angr/angr#702]
p = proj.factory.entry_state(state = entr_state)
    pg = proj.factory.path_group(p)
    tech = angr.exploration_techniques.LoopLimiter(count = 2)
    pg.use_technique(tech)
    pg.explore()
--------------------------------------------------------
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/angr-dev/angr/angr/sim_state.py", line 201, in __getattr__
    raise AttributeError(v)
AttributeError: detect_loops

**Comment by ltfish** [comment]
We intentionally removed `detect_loops()` during the last huge refactor, but we did not notice that it broke `LoopLimiter`. That means we will have to reimplement `LoopLimiter`.

@tyb0807 I remember that you were talking about doing this (correct me if I'm wrong). Are you still interested?

**Comment by tyb0807** [comment]
Well, I'm doing another otie which computes the loop counter (I call it `LoopSeer`). I can eventually put the loop limiter inside. Or you really want to have another otie for this?

**Comment by tyb0807** [comment]
Btw, I think the logic of `block_counter` might not work if a function is called inside a loop? Oh well, maybe because `LoopFinder` doesn't consider the callee's basic blocks? @rhelmot @ltfish I can try to fix this issue but please tell me about the approach that you want me to follow.

I'm writing an otie that uses `LoopFinder` to detect loops, then increment a loop counter (attached to a given state) each time the back edge of the loop is taken. Then I can compare the loop counter to the user's loop limit at any time in order to stop the execution. Problem is, what to do when we run out of states (all states having their loop counter exceeding the limit). Also, what to do when the loop counter depends on a symbolic variable (so the loop _might_ be infinite)

**Comment by XiaoyuHe** [comment]
Maybe you could count the basic blocks and stack's function chain. If you try to fix it use back edge method, you must reconstruct the cfg graph.  It may have two drawbacks :1)slow 2)unstable because angr's cfg recovery is easy to be broken.

**Comment by mor619dx** [comment]
Is there any progress with this bug? 
It is still broken, is there a way to make sure simulation manager doesn't stuck in loops forever?

**Comment by rhelmot** [comment]
You can use the loopseer from the PR linked directly above your comment. It's not a drop-in replacement but it should give you the appropriate information.
