### ISSUE TITLE
Handling of fake_rets is not consistent

### ISSUE THREAD

**Issue by axt** [angr/angr#72]
I'm not sure about the conception of fake_rets in the CFG, but I think I found an issue. To demonstrate this, here is the cfg for ais3_crackme:

This is the CFG generated by angr:
![ais3_cfg_full_bad](https://cloud.githubusercontent.com/assets/759365/14010866/94d881ee-f199-11e5-9722-0749683fdce1.png)

This is the CFG it should generate IMO:
![ais3_cfg_full_good](https://cloud.githubusercontent.com/assets/759365/14010867/94d94dc2-f199-11e5-8f9f-5aa73c9d5e63.png)

The difference is only that in the second graph the 0x40060e -> 0x400618 fake_ret edge is not missing.

This is the check in CFGAccurate, that "removes" that edge:

```python
        # Let's check whether this address has been traced before.
        if pending_exit_tuple in self._nodes:
            node = self._nodes[pending_exit_tuple]
            if node in self.graph:
                pending_exit_addr = self._simrun_key_addr(pending_exit_tuple)
                # That block has been traced before. Let's forget about it
                l.debug("Target 0x%08x has been traced before. " + "Trying the next one...", pending_exit_addr)
                return None
```

Can you please validate this issue?

**Comment by ltfish** [comment]
It's too late for me to read the graph. I'll read it later this week and get back to you.

**Comment by zardus** [comment]
By the way, that graph looks pretty slick! It'd be awesome to get something similar into `angr-management` :-)

**Comment by ltfish** [comment]
I agree. Those graphs look really nice. How did you generate them?

And is it easy to make edges straight, not curved?

**Comment by rhelmot** [comment]
To me it looks like there's also an edge missing from the puts simprocedure to 0x400618? If I'm reading this graph right, at least.

also: https://github.com/axt/angr-utils

**Comment by axt** [comment]
I will create a smaller testcase for you, so the problem is easier to spot.

I've generated the graphs using pydot, you can check it here: https://github.com/axt/angr-utils

I just basically feed the cfg to pydot, and do the plotting. It just looks nice for small graphs. For bigger ones its pretty messy. I'm still experiencing with subgraphs in pydot, to make it nice for larger graphs.

**Comment by ltfish** [comment]
Ouch... `angr-utils`! I like the name (and everything in that repo, of course)!

**Comment by axt** [comment]
So here is the smaller example:
```c
int main(int argc, char **argv) {
	int a,b;
	if (a > 0 || b > 0) {
		printf("a");
	} else {
		printf("b");
	}
}
```

The CFG generated:
![simple_cfg_full_bad](https://cloud.githubusercontent.com/assets/759365/14011315/f37816c0-f19d-11e5-9fad-3314498b8bad.png)
The CFG it should generate:
![simple_cfg_full_good](https://cloud.githubusercontent.com/assets/759365/14011314/f375ea94-f19d-11e5-8dbd-30d235c7b3b2.png)

**Comment by rhelmot** [comment]
again, am I missing something or is there an additional error in this graph, that there's no edge from the simprocedure to 0x0804841d?

**Comment by axt** [comment]
Good catch, yes it should be. I think that the missing edge from the simprocedure is only a bug in my visualization.

**Comment by axt** [comment]
It seems its not the "visualization".
Here is the same CFG plotted with networkx.write_dot. The context sensitivity level is 3 in the analysis.

![cfg2](https://cloud.githubusercontent.com/assets/759365/14011869/252e2228-f1a2-11e5-8abd-97b52ccc83e3.png)

You also can note, that in the networkx plot, there is only 1 node with address 0x8048310, while if I do this 'query':
```python
    print cfg.get_all_nodes(0x9000010)
    print cfg.get_all_nodes(0x8048310)
```
I get these results:
```
[<CFGNode putchar (0x9000010) [0]>]
[<CFGNode 0x8048310 (6) [0]>, <CFGNode 0x8048310 (6) [0]>]
```
So since we can't trust any visualization :-)
```python
    for s,t in cfg.graph.edges():
        if s.addr == 0x9000010:
            print s,t
```
yields to this:
```
<CFGNode putchar (0x9000010) [0]> <CFGNode main+0x23 (0x8048440) [0]>
```
So there is only 1 edge. I can't really decide if that is a bug or not.

**Comment by ltfish** [comment]
Regarding the first issue (where a `FakeRet` edge was missing), right, it's a bug. I'll fix it.

Regarding the missing return from `putchar`, what's the value for `context_sensitivity` did you use when generating the CFG?

**Comment by axt** [comment]
I've used context_sensitivitiy level 3.

Attached a cfg with full debug info plotted (including predecessors, successors and callstack_key):
![simple_cfg_full_debug](https://cloud.githubusercontent.com/assets/759365/14035754/12cf5e0e-f232-11e5-831c-98c0fa2dbd4a.png)

**Comment by axt** [comment]
Is that right, that the callstack_key for 0x8048310 contains the call instruction's address?
```
[None, None, '0x804841d', --> '0x8048434', <-- '0x8048310']
[None, None, '0x804841d', --> '0x8048442', <-- '0x8048310']
```

Shouldn't it be only:
```
[None, None, None, '0x804841d', '0x8048310']
[None, None, None, '0x804841d', '0x8048310']
```

**Comment by ltfish** [comment]
So it's intended that address of the call site is included in the `callstack_key`, so you can tell apart when different call sites of the same function calling the same function. For instance, when a function A is called in different places of another function B, two different instances of `CFGNode` of the starting point of function A will be created.

Therefore the problem here is that you should see two copies of the `SimProcedure` `puts` that have different call stack key.

**Comment by axt** [comment]
It seems to me this part of code is responsible for the bug:
```
    def _create_new_call_stack(self, addr, all_entries, entry_wrapper, exit_target, jumpkind):
        [...]
        else:
            # although the jumpkind is not Ijk_Call, it may still jump to a new function... let's see
            if self.project.is_hooked(exit_target): # TODO: Check whether it's a simprocedure
                new_call_stack = entry_wrapper.call_stack_copy()
*                new_call_stack._stack[-1] = (addr, exit_target)
```
It is  overwriting the callsite's address, with 'addr', which is the address of the .plt entry in our case (0x8048310).

**Comment by ltfish** [comment]
Huh, thanks for pointing that out. I'll take a close look at it tomorrow.

**Comment by axt** [comment]
Take your time :-), i'm just enjoying getting a better understanding of it while digging through the code!

btw, this is the new CFG if I patch that, which seems okay to me (except the missing fake_ret edge)
![ais3_cfg_cs2](https://cloud.githubusercontent.com/assets/759365/14038941/421104a4-f257-11e5-86fd-4c079368e43a.png)

**Comment by ltfish** [comment]
It looks fine to me! Mind sending me a PR?

I'm having a headache tonight, so I'm not really in a good working state :-(

**Comment by axt** [comment]
Sent one, although not sure if the fix is universal enough.

**Comment by ltfish** [comment]
Umm... I thought about it on my way home, and I don't think your fix is universal. `CallStack` in `CFGAccurate` shows functions _called_ along a specific control flow. Since we _jump_ from the PLT entry of `puts` to SimProcedure `puts`, instead of _calling_ it, replacing the function address with address of the SimProcedure simply breaks the definition of `CallStack`.

From my point of view, I think the correct way of fixing this issue is to separate `the most recently called function` and `the current function` in `CallStack`. Currently there is an implicit assumption that `the most recently called function` == `the current function` (see the `CallStack` implementation in `entry_wrapper.py`), which apparently does not hold for situations like tail-call optimization, or PLT entries.

Therefore I propose the following fix:

- In `CallStack`, instead of representing a call frame using a 2-tuple `(call target, return address)`, use a 3-tuple `(call target, function address, return address)`.
- In situations where we _jump_ to a new function instead of _calling_ that function, we simply update the second element of that 3-tuple (which is the `function address`). Here it can be tricky to identify what a *new* function is. While most `SimProcedure`s are functions, it's difficult to identify a tail-call optimization on the fly. We need to be smart here.
- The `call stack key` will still use up to `N` pairs of `(call target, call site address)`, where `N` is specified by the user.

With the fix above, in your example, you will end up having two SimProcedure `puts` with the following `call stack key`s:
- `[ None, 0x804841d, 0x8048434, 0x8048310 ]`
- `[ None, 0x804841d, 0x8048442, 0x8048310 ]`
where the `current function address` are both `0x9000010` when executing inside `puts`.

What do you think of this fix?

**Comment by axt** [comment]
Your idea seems pretty reasonable for me, but to be honest I'm just playing with angr (and static/concolic analysis) since two weeks, so I don't have such a big insight. 

When I wrote that I'm not sure its universal, it was because I felt it is very specific for .plt entries. 

So without having a deep knowledge in angr, i think it addresses situations, the current code can't handle well, while keeps compatibility (callstack_key), and doesnt breaks the callstack concept. So definiatelly an improovement. The question is: does it handle all kind of situations well?  

Only one thing comes to my mind:
The current hash function of the CFGNode is based on [callstack_key, addr, looping_times ,simprocedure_name].  Is that enough to identify a node in the CFG, or should the whole callstack frame be represented in it? 

I can't come up with a situation, where the 'addr' in the hash is not enough, to distinguish between the different nodes, but not sure that this kind of situation doesn't exists.

**Comment by ltfish** [comment]
> Your idea seems pretty reasonable for me, but to be honest I'm just playing with angr (and static/concolic analysis) since two weeks, so I don't have such a big insight. 

I totally understand that you don't know angr as well as I do. However, you definitely did a good job in finding these issues (which I failed to do so :P). I will implement the fix addressing those issues tomorrow, and hopefully I can have enough time to thoroughly document it as well.

Thanks again for submitting this issue. I will let you know as soon as the fix is available.

>  Is that enough to identify a node in the CFG, or should the whole callstack frame be represented in it?

`CFGAccurate` is context-sensitive, however, as a design choice (mostly for performance), it only takes addresses of functions called and call sites into consideration. Therefore in `CFGAccurate`, it is enough to identify a `CFGNode` by `callstack_key, address, looping_times, simprocedure_name` without specifying the entire frame. You'll have to write your own analysis if you care about all content in each stack frames in CFG recovery.

**Comment by axt** [comment]
Cool! And thanks for the clarifications, I've definiately learned about angr from this conversation!

**Comment by ltfish** [comment]
The issue should be fixed by commit dd7c905. Please test it.

**Comment by axt** [comment]
Tested it! It looks fine to me! Thanks a lot! 

You've left some debug code in cfg_accurate.py :)
```python
            if src_node.addr == 0x4007c9 and dst_node.addr == 0x4007d3:
                import ipdb; ipdb.set_trace()
```

**Comment by ltfish** [comment]
Ouch... fixed. Thanks!
