### ISSUE TITLE
angr "IndexError : list index out of range"

### ISSUE THREAD

**Issue by dukup11ch1** [angr/angr#778]
hello i installed angr by git clone https://github.com/angr/angr.git

when i solving Defcon 2016 baby-re problem, i got an error.....

how can i fix it?

![default](https://user-images.githubusercontent.com/34093617/33406711-8f5022ec-d5b1-11e7-948a-c47dff78cefe.PNG)

**Comment by sraboy** [comment]
The index error is because `sm.found[0]` doesn't exist, meaning angr failed to find any path to reach `0x40294b`. 

Verify that `0x40294b` is the address you're looking for and that avoiding `0x402941` does what you think it does. You'll need to spend some more time in a disassembler to see how/why you can't reach that address.

I haven't done that challenge myself but I did someone else's angr solution elsewhere on Github... I won't spoil things for you (unless you want me to) but I'd take another look at the program and make sure those addresses are what you need.

**Comment by rhelmot** [comment]
this was fixed with https://github.com/angr/angr-doc/commit/1ff6df6fc053ed02840c69580f2a96e1a95965ba
