### ISSUE TITLE
angr not finding a path #2

### ISSUE THREAD

**Issue by Dinatrix** [angr/angr#80]
(continuing from the first issue because I wasn't sure how to reopen:)
Working my way through the addresses of the program it looks like the verification point I'm looking for is never reached due to a previous input check always failing. I also tried to avoid this other input check to force angr down the path that does have the authentication point using surveyors.Explorer rather than the pathgroup explorer, but am running into this result: 
![image](https://cloud.githubusercontent.com/assets/10760263/14254671/cc55bb82-fa5e-11e5-913b-0a798bf9d7b6.png)

Alternatively, would there be a way to test various badge IDs or lengths from within this angr program? I think part of my problem is trying to develop a backdoor finding angr script without relying on too much knowledge of the source code, but it is hard to avoid!

Thanks :)

**Comment by ltfish** [comment]
When angr raises a `SimMemoryAccessError`, it's mostly because the state is not satisfiable.

## Why is the state unsat?

The only way to check if a state is satisfiable or not is to ask the theorem prover (in angr we uses Z3). Sometimes this can be very time consuming. Hence angr provides an option called `LAZY_SOLVES`. With `LAZY_SOLVES` on, whenever a path branches into several at the end of a basic block, angr will not actively check whether each succeeding state is satisfiable or not. Instead, angr assumes they are all satisfiable, and goes ahead to create succeeding paths. If any of those succeeding state is unsat, and later on a solve must occur (like, concretizing a symbolic memory write target), the theorem prover will fail to find a solution to all gathered constraints in that state (since it's unsat), and an exception `SimMemoryAddressError` is raised. In short, `LAZY_SOLVES` is a balance between path explosion (more paths are created) and time spent in constraint solving (we solve less, and hopefully future constraints simply contradict with constraints in the past, which means we don't need to solve for that path at all).

If you disable `LAZY_SOLVES` in the initial state (`p.factory.entry_state(remove_options={simuvex.o.LAZY_SOLVES})`, where `p` is a `Project` object), you won't see that exception.

@zardus Do we want to revise the exception description to make it less confusing?

## Your problem

The problem you are facing is, that a previous input check always fail. How did you "try to avoid this other input check"?

It's likely that there isn't such a path that reaches the verification point without passing the "previous input check". If you make angr avoid that input check, maybe it'll never reach the verification point with a satisfiable state.

If you want, you can post the binary somewhere, let me know what your need is, and I can try to write an angr script for you.

**Comment by zardus** [comment]
Regarding revising the exception description, that sounds like a good idea.

Also, I think the whole `LAZY_SOLVES` thing just causes issues. I think we should really consider turning it off by default.

**Comment by Dinatrix** [comment]
Ah I wasn't sure what the LAZY_SOLVES was doing but left it in this script because I had adapted it from an example. Analyzing the disassembly and source code, there is a very clear path to this main authentication, provided the preliminary/ID length check passes. I tried to prevent angr going down that path by adding the address of this length check to my 'avoid' list in the explore. I had begun looking into 'hook'ing around this problem function and trying to constrain the size of the backdoor as it's known to be 10 chars, but I haven't gotten that to work yet either.

That would be great if you could take a look at it, thanks! Attaching it here:
[rfid_reader.zip](https://github.com/angr/angr/files/203282/rfid_reader.zip)

**Comment by ltfish** [comment]
@zardus I didn't dare to say "we should disable `LAZY_SOLVES`" since you were a huge fan of it, but I always disable it in my local branch :-)

**Comment by zardus** [comment]
I'm currently testing the LAZY_SOLVES disable. Maybe the nightmare will be over soon :-)

**Comment by Dinatrix** [comment]
Whoops realizing I never fully answered "let me know what your need is,"

I was trying to write an angr script that would traverse the program looking for hardcoded backdoor(s) after identifying in disassembly where the normal authentication points occurred. In the binary I was looking at, the only point at which the badge id is deemed authentic is occurs when 'bnez v1, 0x406a24' leads to the block that includes the 'open' strings. Should any other path lead to that 'open' block, I aimed to print the path and input necessary to reach that point which would presumably be a backdoor.

Thanks for taking a look at it!

**Comment by ltfish** [comment]
I'm putting this issue into my TODO list, and hopefully I can answer it as soon as I have some free time :-)

**Comment by ltfish** [comment]
@zardus Can we disable the LAZY_SOLVES by default now?

**Comment by gsingh93** [comment]
@ltfish @zardus Any updates on disabling LAZY_SOLVES by default?

**Comment by Dinatrix** [comment]
Hi again!
I mentioned this issue briefly at the recent Engagement but was wondering if you had a chance to look at it since? @ltfish @zardus 
Thanks!
