### ISSUE TITLE
situation of symbolic memory address

### ISSUE THREAD

**Issue by moliam** [angr/angr#812]
For the following code:
```
int main(int argc, char* argv[])
{
int i;

if(2 > argc)
   return 0;

char* p = argv[1];
if(strlen(p) < 310)
   return 0;

for (i = 0;i < 30;i++)
{
	if(p[0] > 10 || p[0] < 0)
		return 0;
	p = p + p[0];
}
if('Z' == p[0])
{
        printf("good");
       return 1;
}
return 0;
}
```
angr runs very slowly.   However, another symbolic tool KLEE can handle this situation easily.  
What is the reason or what is angr busy with when dealing with symbolic memory address?

**Comment by rhelmot** [comment]
what is `p`?

**Comment by moliam** [comment]
sorry...    code has been updated :-). @rhelmot

**Comment by rhelmot** [comment]
Comparing KLEE to angr is not a very fair comparison. KLEE operates on the source level and angr operates on the binary level.

Symbolic memory addresses are extremely complicated to reason about; I'm honestly surprised that angr can solve this at all. There are some improvements to be made with symbolic indexing, for example taking advantage of z3's theory of arrays, but these would be a very serious and difficult project to integrate at the moment.

**Comment by salls** [comment]
I don't really remember, but I think KLEE also does a different exploration strategy than angr's default one and might have different rules for concretizing symbolic memory.

**Comment by moliam** [comment]
@rhelmot  indeed, KLEE takes advantage of the arrays and updates supported by Z3 and STP to accelerate this kind of problem.

**Comment by ltfish** [comment]
> indeed, KLEE takes advantage of the arrays and updates supported by Z3 and STP to accelerate this kind of problem.

Any idea of why we cannot do the same in angr?

**Comment by rhelmot** [comment]
.........................because we model the entirety of memory as a continuous array and z3 probably can't handle gigabytes-long arrays? KLEE can do it because it can model individual variables as distinct memory regions, probably. If we could make the abstract memory model work during normal execution then it's a possibility.

**Comment by ltfish** [comment]
> because we model the entirety of memory as a continuous array and z3 probably can't handle gigabytes-long arrays?

That's not necessarily the case though. We've always had an upper bound limiting the sizes of all symbolic reads/writes (otherwise the whole thing will definitely not be scalable). At least we can create an array of size N in Z3, where N is the current upper bound of symbolic read/write.

Also, with some static analysis applied, we might be able to recognize buffers and their sizes, which essentially gives us the same level of information that KLEE sees from source code.

**Comment by ltfish** [comment]
@rhelmot and I had some heated discussions offline. The conclusion is that, it could be done, as long as anyone has a good idea of doing it, without hampering the existing capabilities in angr.

**Comment by rhelmot** [comment]
(The subtext there should be, none of us see good ways to do it.)

**Comment by moliam** [comment]
@rhelmot  As a matter of fact I am now building a tool based on KLEE for binary file and the memory access model adopted is a mixed one, that is, some time does the same as angr and sometime use the array and updates.   And I use the array and updates as often as possible because of the benefit in time consumption.   ltfish's idea is a good one for most part of symbolic execution (except for some extreme situation where needs some adjustment. ).
