### ISSUE TITLE
state memory load wrong endian

### ISSUE THREAD

**Issue by bannsec** [angr/angr#839]
I've run into this a few times before, and i've found it again now. Basically, poking at this AceBear chal with angr. I execute till right past the read of username, then load that memory pointer. The pointer that angr returns is wrong endian. Interestingly enough, if I manually reverse the endianness and load that memory area, i get the expected input. However, this is causing the program to also read the wrong memory area and go off the tracks.

This was started through a script that first set stdin input to start with a bunch of "A" values. Expected output would be that the read would have read in that bunch of "A" values. Yes, i seeked back to 0 :-p
```
In [1]: simgr.explore(find=0x08048841)
Out[1]: <SimulationManager with 1 found>

In [3]: s = simgr.found[0].copy()

In [4]: s
Out[4]: <SimState @ 0x8048841>

# This is wrong endian. Both to me, and to angr internals itself.
In [7]: s.memory.load(s.regs.ebp + 8)
Out[7]: <BV32 0x78fefe7f>

# Note here, the specified input ("AAA..." doesn't show up)
In [8]: s.memory.load(s.memory.load(s.regs.ebp + 8))
Out[8]: <BV32 Reverse(mem_78fefe7f_3_32)>

In [12]: s.se.any_str(s.memory.load(s.regs.ebp + 8))
Deprecation warning: Use eval(expr, cast_to=str) instead of any_str
Out[12]: 'x\xfe\xfe\x7f'

In [15]: s.posix.dumps(0)
Out[15]: 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\n2dfcfffbfffffffEfffffffffffffff4fffffffffff3ffffffffffffffffffff\n'

# Ask angr to tell me for real what the value is..
In [17]: hex(s.se.any_int(s.memory.load(s.regs.ebp + 8)))
Deprecation warning: Use eval() instead of any_int
Out[17]: '0x78fefe7f'

# I manually reverse endianness, load memory and find my expected "A" values.
In [19]: s.memory.load(0x7ffefe78)
Out[19]: <BV32 0x41414141>
```

I believe the last time I reported this, the claim was that internal to angr it reversed things correctly. In this binary it certainly does not. It ends up splitting and deadending with what is actually supposed to be fully concrete data.

Given this CTF is ongoing, I'm not posting my script. However, I will upload the file itself.

[secure_login.zip](https://github.com/angr/angr/files/1670415/secure_login.zip)

**Comment by bannsec** [comment]
I should mention, I'm running the mechaphish docker image that I pulled down last night.

**Comment by zardus** [comment]
We don’t automatically endian-correct for memory loads, because it’s hard
to tell whether or not the data _should_ be endian-corrected (for example,
if you are reading a string from memory, it should not be endian-corrected).

You can make angr correct the endianness by doing `s.memory.load(s.regs.ebp
+ 8, endness=“Iend_LE”)`.

Note to the dev team: maybe we should make angr endian-correct when a size
is not specified for the load (as in this example)? In that case, you’re
intentionally grabbing “data of the architecture width” rather than “data
of a width that might happen to match the architecture width”, and I feel
that it’s reasonable to, in that case, expect that the data will be
endian-corrected. Thoughts?

**Comment by bannsec** [comment]
That issue aside, angr still flies off the tracks. Angr internally is not able to properly symbolically execute that function. Basically what happens is:

1. It reads in my pre-populated concrete value "AAAA" into what is the expected correct addres
1. It checks if it ends in "\n".
1. It state splits (since it's not actually looking at the input it just read in).

Expected behavior regardless of correction is that it would _not_ state split given the input is concrete and specified ahead of time.

**Comment by zardus** [comment]
So, it’s definitely not impossible that there is some fundamental angr
issue here (especially if simprocedures are involved). I’m mobile at the
moment and can’t look at the binary, so for now, let’s explore the option
that the problem is how angr is being used.

One thing I noticed is that your dump of stdin actually contains two lines
— one with the As and one with what looks like it might be symbolic data
concretized to printable chars. Is this what you expect? Maybe the state
split happens on data from that extra line.

The best way to look into this is to see _why_ the state split. Check out
the guard conditions (in state.history).

**Comment by bannsec** [comment]
Gah. nvm. that memory load was throwing me off. It is running that part correctly. Note to self... use `mem.int` instead from now on...

Possibly ran into some weirdness in a different sim function, but will open a diff ticket if that's the case.

Thanks!
