### ISSUE TITLE
CFGAccurate only finds 4 nodes

### ISSUE THREAD

**Issue by 635bimmer** [angr/angr#849]
Analyzing an ELF file using CFGFast and CFGAccurate: 

CFGFast finds 5642 nodes, but CFG Accurate only finds 4 nodes. Anyone have hints on how to debug this? Any other CFGAccurate options that I should be using?

> file rom.elf 
> rom.elf: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), statically linked, not stripped

> cfg = proj.analyses.CFGFast()
> print len(cfg.nodes())
> 5642

> cfg = proj.analyses.CFGAccurate(context_sensitivity_level=2,keep_state=True)
> print len(cfg.nodes())
> 4
> print proj.loader.all_objects
> [<ELF Object rom.elf, maps [0x1000:0xe820fff]>, <ExternObject Object cle##externs, maps [0xf000000:0xf008000]>, <ELFTLSObject Object cle##tls, maps [0x10000000:0x1000c808]>, <KernelObject Object cle##kernel, maps [0x11000000:0x11008000]>]

**Comment by ltfish** [comment]
Usually it's because there is a missing SimProcedure support. You might want to specify a different start point for CFGAccurate to start analysis at. What's your binary look like?

**Comment by valour01** [comment]
I come across the same problem. My binary is elf file based on ARM. I try to use CFGAccurate, However I only get 1 node. I could obviously notice that are some branch jump command like `BEQ address` when I use IDAPro to disassemble the binary. However, when I use CFGFast to I found more than 10 thousand nodes. 

You mentioned that CFGAccurate will be slower but more accurate. Does it mean that CFGAccurate will include all the node in CFGFast but also add more nodes? 

Could you please explain SimProcedure in more detail and how to patch this problem? I am using the newest version of angr in develop mode. Also, It would be great if you have any sample binary(better in ARM) that can reflect the main differences between CFGFast and CFGAccurate. Many Thanks

**Comment by ltfish** [comment]
CFGAccurate recovers as much control-flow graph as possible by simulating the execution of programs. This means if the very first block of your program calls `exit()`, CFGAccurate will only contain a single block.

CFGFast works differently - the basic idea is recursive disassembly, without really simulating the execution.

> Could you please explain SimProcedure in more detail and how to patch this problem?

First, please refer to angr-doc and see what a SimProcedure is. Because of how CFGAccurate works, if there is a SimProcedure that is very important and simply skipping the call does not advance the execution of the program (i.e., the `__libc_start_main()` call, which creates three new exits whose addresses are passed as the first three arguments by the caller), you may want to implement it and make sure CFGAccurate picks it up when recovering the CFG.

> Does it mean that CFGAccurate will include all the node in CFGFast but also add more nodes?

"Accurate" is very different from "complete". So no, usually CFGAccurate contains way less nodes than CFGFast does.

**Comment by valour01** [comment]
@ltfish Thank you so much. Now I understand the differences. I guess the reason is there is some ARM co-processor instructions that angr doesn't understand. So it will terminate directly.

**Comment by valour01** [comment]
@ltfish Besides, It seems that CFGFast would also support jump table. According to the paper SoK, CFGAccurate will use the threshold 256 for the possible targets. I want to know whether CFGFast has the same strategy when handling the indirect jumps. If so, are there any flags to distinguish the nodes and edges created by direct jump(definitely exist) from those created by indirect jump, which might not exists.

**Comment by ltfish** [comment]
> I want to know whether CFGFast has the same strategy when handling the indirect jumps.

CFGFast uses indirect jump resolvers - you may take a look at [this](https://github.com/angr/angr/blob/master/angr/analyses/cfg/indirect_jump_resolvers/jumptable.py). It currently uses a different threshold internally. You should be able to set it up by passing argument `indirect_jump_target_limit` to `CFGFast.__init__()`.

> If so, are there any flags to distinguish the nodes and edges created by direct jump(definitely exist) from those created by indirect jump, which might not exists.

Good question. I think the answer is no at the moment, but you can manually check whether the basic block has an indirect-jump exit by checking if its address is in `cfg.indirect_jumps`. You can make a PR to add a special flag in graph edges so that we can differentiate direct and indirect jumps.
