### ISSUE TITLE
CFG construction issues

### ISSUE THREAD

**Issue by ViktorMKa** [angr/angr#91]
I recently updated angr to the most current version to try and play with CFGFast and CFGAccurate variations. 

I can execute CFGFast with no issues, but face breakdowns using `proj.analyses.CFG()` which is a synonym to CFGAccurate if i read the documents correctly. The following is what i used to access angr.
```

b=angr.Project(filename)
cfg=b.analyses.CFG(keep_state=True)

```
I recieve the following errors with a multitude of samples:

```

WARNING | 2016-04-21 17:54:26,626 | angr.entry_wrapper | Returning to an unexpected address 0x40008c
ERROR   | 2016-04-21 17:54:26,646 | angr.analyses.cfg | Caught an AngrError during CFG recovery at 0x400095 (No section)
<python stuff>
AngrMemoryError: No bytes in memory for block starting at 0x400095.

```
I have appended one sample in assembler. It was compiled and linked with gcc. 

To be honest I'm not even sure, whether i'm just misusing the function or whether there is an actual issue.

[fakecode.txt](https://github.com/angr/angr/files/230292/fakecode.txt)

**Comment by ltfish** [comment]
`CFGAccurate` makes the following assumptions:

- A `ret` should always return to a call site. Your code uses `push dest; ret` to make a jump, which breaks this assumptions. That's why you are seeing the first "returning to an unexpected address" error prompt. In this sense, it is expected, and `CFGAccurate` should have no problem in resuming the CFG recovery.
- A control flow is only terminated by non-returning syscalls or `SimProcedures`, like `exit`. Without seeing your binary, I would assume `CFGAccurate` tries to resume CFG recovery after the very last `syscall`, while there is no more instruction available. This is why you see the `AngrMemoryError`. This error is also expected.

In the end, you should still end up with a useable CFG out of `CFGAccurate`. If not, then that's an actual issue.

I think we should replace the `ERROR` with `WARNING` since they occur pretty often, and most of the time they are expected errors.

**Comment by ViktorMKa** [comment]
Hi! Sorry it took so long for me to get back to you. You are right, i still get a somewhat usable CFG despite Error/Warnings.

**Comment by ltfish** [comment]
I'm also interested to see how angr works on obfuscated binaries. You can adjust values of different options of `CFGAccurate` in order to generate a better CFG. I'll close this issue for now. Let me know if you need more help regarding CFG!
