### ISSUE TITLE
Question: CFG and DFG outputs

### ISSUE THREAD

**Issue by leojcollard** [angr/angr#926]
Quick question. When I generate a given functions CFG using `CFGFast`, and then generate a set of DFGs for the same function, there are more DFGs than basic blocks. For example:

- Chosen binary: Zlib 1.2.8, ARM, GCC, O2: 
[zlib.1.2.8-O2.libz.so.zip](https://github.com/angr/angr/files/1888178/zlib.1.2.8-O2.libz.so.zip)
- Extract CFG for function `gz_avail`; it contains `11` basic blocks
![zlib 1 2 8-o2 libz so_gz_avail_cfg](https://user-images.githubusercontent.com/6481665/38474572-56b679c2-3b6e-11e8-84b0-b7b4613675ee.png)
- Extract that functions set of DFGs and there are `41`, all eleven CFG ones are there [gz_avail.zip](https://github.com/angr/angr/files/1888181/gz_avail.zip)

All basic blocks identified in the CFG are present in the set of DFGs. However, what are the extra ones? I have checked the functions CFG in IDA Pro, and the one generated using `CFGFast` is accurate. Thanks!

**Comment by ltfish** [comment]
Hi, what do you use DFG for?

DFG is not something we want to keep supporting and it will be removed very soon(-ish).

If it has more blocks than the CFG, it's possible that its output contains the functions that the function calls.

**Comment by leojcollard** [comment]
Good to know thanks! 

I am currently playing with the framework and felt like testing out its capabilities. I found the built in DFG functionality interesting and decided to test it out. I found this behaviour weird and wanted to understand it.

Why are you removing this functionality in the near future? Is it due to the complexity required to extract DFGs? I found that it took quite some time to perform this task when utilizing the binary I provided in the original question. Thanks again for the very quick response!

**Comment by PariaSh** [comment]
Hi ... First, thanks for the great framework! 

Actually the given function (gz_avail with 10 basic blocks) has only one callee (gz_load) with 7 basic blocks. However, the total number of basic blocks in the generated dfg is 43. If we include the number of basic blocks of the callers as well (gz_look: 21 and gz_decomp:17), still it does not match. 

I am wondering is there any documentation on your data flow analysis that we could read more about it, or we should refer to the code and understand it?

Thanks!

**Comment by ltfish** [comment]
> I found this behaviour weird and wanted to understand it.

I read the code in dfg.py. It seems to me that each node in DFG is a statement, not a basic block.

> Why are you removing this functionality in the near future?

Because a) DFG was introduced as part of a research project, and no one seems to be using it ever since, b) the original author is not an active angr contributor and he would not maintain DFG, and c) `ReachingDefinitionAnalysis` (maybe it will have a better name in the future) on the `wip/nightmaRE` branch does way more than what DFG currently does. The plan is finish the `wip/nightmaRE` branch, merge it in, and then remove DFG for good.

> I am wondering is there any documentation on your data flow analysis that we could read more about it.

I wish it was properly documented as well ;)

My honest opinion is that, if you really want to use the static data-flow analysis, go work on the `wip/nightmaRE` branch. Things on that branch are the future of angr's static data-flow analysis.

**Comment by PariaSh** [comment]
Thank you so much! That's great ... will look into nightmaRE

**Comment by pingtinghao** [comment]
@leojcollard hello！I have a question how you could draw the visualize CFG？Please help me.
cfg = proj.analyses.CFGFast()
print("This is the graph:", cfg.graph)
This is the graph:
There is nothing.

**Comment by ltfish** [comment]
@pingtinghao Please do not reply to a one-year old issue. Open a new issue instead.
