### ISSUE TITLE
Solving file input

### ISSUE THREAD

**Issue by Vatueil** [angr/angr#968]
Hi,

at the moment i have problems with using angr and symbolic file input. Can someone help me out?

I work on the docker and my program is this:

```
#include <stdio.h>
#include <stdlib.h>

int correct(){
  printf("YOU WON\n");
  return(0);
}

int main(int argc, char *argv[]) {
    FILE *fp;
    char *filename; 

    char * buffer = 0;
    char * tocomp = "deadbeef\x0A";
    long length;

    int i;
    int response = 0;
   
    i = 0;

    // Check if a filename has been specified in the command
    if (argc < 2)   {
       printf("Missing Filename\n");
       return(1);
    } else {
       filename = argv[1];
       printf("Filename : %s\n", filename);
    } 

    // Open file in read-only mode
    fp = fopen(filename,"r");

    // read file into buffer
    if (fp){
       fseek (fp, 0, SEEK_END);
       length = ftell (fp);
       fseek (fp, 0, SEEK_SET);
       buffer = malloc (length);
       if (buffer) {
          fread (buffer, 1, length, fp);
       }
       fclose (fp);
    }

    //compare
    for (i=0; buffer[i]!=0 && tocomp[i]!=0; i++) {
        if (buffer[i] > tocomp[i])
            response = +1;
        if (buffer[i] < tocomp[i])
            response = -1;
    }

    if (tocomp[i] != 0)
        response = +1;
    if (tocomp[i] != 0)
        response = -1;
   
    printf("respone: %i\n", response);
    if (response == 0){
       correct();
    } else {
       printf("Failed\n");
    }

return(0);
}
```

What is the correct way to solve the input for this File?
At the moment i try the following:

```
import angr
import claripy

p = angr.Project('/home/angr/angr-dev/test_symex')  #, use_sim_procedures=True)

SimfileName = '/home/angr/angr-dev/test.txt'

data = claripy.BVS('data', 9*8)
simfile = angr.SimFile(SimfileName, content=data)

state = p.factory.full_init_state(args=['./home/angr/angr-dev/test_symex', SimfileName], fs={SimfileName: simfile},
                                  add_options={angr.options.LAZY_SOLVES})

simfile.set_state(state)

state.fs.insert(SimfileName, simfile)
simfile.set_state(state)

sm = p.factory.simulation_manager(state)

print "start exploration"
sm.explore(find=0x400766)

print "start concretize"
test = simfile.concretize()
print repr(test)
```

Can someone help me out please?

**Comment by rhelmot** [comment]
The correct debugging technique for issues like this is the following:

- turn on simulation manager logging. `logging.getLogger('angr.sim_manager').setLevel('INFO')
- watch the output. notice anything that seems questionable. in this case the presence of errored states is sketchy and there is also a visible path explosion.
- run your program and get a debug shell somewhere near the problematic point. for state-explosion problems, my favorite way to do this is `ipython --pdb test_script.py` and hit ctrl-c when things get hairy
- investigate the content of the simulation manager. here, I looked at the list of errored states and found that all of them had errored with `Unimplemented format specifier 'i'`, indicating that part of the problem is just that angr doesn't support `printf("%i")` yet. You can report this to us or you can fix it yourself. I've fixed this in the current master.
- try again after that bug has been fixed. this time you should notice that you just have a huge state explosion problem.

If you must submit an issue, please include more diagnostic information than "it doesn't work", for example "the script never finished and ate all my memory".

I wasn't able to get your script to work in the end. You have too nasty of a state explosion problem. I tried enabling veritesting but there seems to be a bug in it. One thing you could do would be to add an `avoid` condition to your explore, either blacklisting all the parts where response is set to nonzero, or actively introspecting the stack frame and extracting the value of `response`, testing if it's nonzero, and avoiding the state if it is.

Here's a better version of your script, since I noticed you were a little confused about how to use simfiles. The critical part is that you can't use the original simfile for concretization, since it's attached to the original state, not the found state. You can either concretize the input BVS against the found state (since variables are independent of states but files are not), or you can get the file from the found state and concretize that.

```python
import angr
import claripy
import logging

p = angr.Project('test_symex')

data = claripy.BVS('data', 9*8)
filename = '/home/angr/angr-dev/test.txt'
simfile = angr.SimFile(filename, content=data)

state = p.factory.full_init_state(
        args=['./home/angr/angr-dev/test_symex', filename],
        fs={filename: simfile},
        add_options={angr.options.LAZY_SOLVES})
sm = p.factory.simulation_manager(state)

print "start exploration"
logging.getLogger('angr.sim_manager').setLevel('INFO')
sm.explore(find=p.loader.find_symbol('correct').rebased_addr)

print "start concretize"
test = sm.one_found.fs.get(filename).concretize()
print repr(test)
```

**Comment by Vatueil** [comment]
Thank you very much!
This cleared many problems I had.

If I do have further problems I promise to write a better report.
