### ISSUE TITLE
Exit state has over 257 possible solutions. Likely unconstrained; skipping.

### ISSUE THREAD

**Issue by phros** [angr/angr#97]
Hi, I'm executing blocks to get the values stored in registers after this block has been executed (always starting with an empty state). Sometimes I get the error/warning written in the Title of this issue. When this happens, I cannot get the successor state and cannot get register values even if they wouldn't be symbolic.

I can imagine why this happens, but don't understand why it is working for most cases. Two examples:

This basic block is executed fine:
```
0x400e9c:	ldr	r2, [r4]
0x400e9e:	ldr	r1, [pc, #0x94]
0x400ea0:	movs	r6, #0xa7
0x400ea2:	lsls	r6, r6, #2
0x400ea4:	ldr	r3, [r2, r6]
0x400ea6:	str	r0, [sp, #0x2c]
0x400ea8:	add	r1, pc
0x400eaa:	adds	r0, r4, #0
0x400eac:	blx	r3
```

This doesn't work:
```
0x400eae:	ldr	r2, [r4]
0x400eb0:	ldr	r1, [pc, #0x84]
0x400eb2:	str	r0, [sp, #0x30]
0x400eb4:	ldr	r3, [r2, r6]
0x400eb6:	adds	r0, r4, #0
0x400eb8:	add	r1, pc
0x400eba:	blx	r3
```

Is there a way to get for instance the value form R1 after execution without an exit state? Every help is much appreciated!

Thanks

**Comment by rhelmot** [comment]
This message shows up whenever the instruction pointer at the end of a block has become a symbolic value with more than 257 ways to satisfy the constraints applied to it. Usually, this means that it's unconstrained, and we have no way of continuing execution.

If you'd like to get at the successor state regardless of the fact that it can't be continued, like it seems like you want, there should be an `unconstrained_successors` attribute on `Path`, or something similar.

I am exhausted and can't really analyze that ARM right now, but I don't see any concrete difference between the construction of the successor address in the two snippets. Realistically, both of them should produce that message, since they both perform reads from memory at an unconstrained symbolic address (since you're starting from a blank state) to get the value of r3.

**Comment by phros** [comment]
Thanks for your answer!!! I don't see much difference neither... that's why I asked. Anyway the `unconstrained_states` list gives me what I need.
